.libPaths(c(.libPaths(), '/home/ed/R/x86_64-pc-linux-gnu-library/4.5'))
suppressPackageStartupMessages({library(dplyr);library(tidyr);library(purrr);library(readr);library(stringr);library(forcats);library(fixest);library(magrittr)})
source('R/distance/spec.R'); source('R/reduced-form/context.R')
old <- readRDS('build/realized/context/analysis-context.rds')
error <- tryCatch({takeup_validate_analysis_context(old); NULL},error=conditionMessage)
print(error);stopifnot(grepl('Expected-distance controls do not match',error));cat('Old cache rejected:',error,'\n')
fresh <- takeup_build_analysis_context('realized')
saveRDS(fresh,'build/introduction-pvalue-audit-20260929/corrected-context.rds')
models <- readRDS('build/introduction-pvalue-audit-20260929/model-frames.rds')
stopifnot(identical(fresh$data$cov_analysis_data$mu_d,models$takeup$new$mu_d))
source('scripts/checks/test-distance-spec.R')
cat('Corrected context validated; corrected rerun input matches production loader.\n')
