---
title: "Balance Tables"
output:
  pdf_document:
    keep_tex: yes
knit: (function(input, ...) rmarkdown::render(input, knit_root_dir = here::here(), ...))
header-includes:
    - \usepackage{booktabs}
    - \usepackage{longtable}
    - \usepackage{array}
    - \usepackage{multirow}
    - \usepackage{wrapfig}
    - \usepackage{float}
    - \usepackage{colortbl}
    - \usepackage{tabu}
    - \usepackage{threeparttable}
    - \usepackage{threeparttablex}
    - \usepackage[normalem]{ulem}
    - \usepackage[utf8]{inputenc}
    - \usepackage{makecell}
    - \usepackage{xcolor}
    - \usepackage{pdflscape}
    - \newcommand{\blandscape}{\begin{landscape}}
    - \newcommand{\elandscape}{\end{landscape}}
params:
    fit_version: 95
    rf_fit_version: 95
    input_path: data/stan_analysis_data
    output_path: temp-data
    table_output_path: presentations/tables
    struct_models: STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP_FOB
    rf_models: REDUCED_FORM_NO_RESTRICT
    cache: FALSE
    width: 0.95
---



```{r, "startup", include=FALSE}
library(tidyverse)
library(broom)
library(data.table)
library(knitr)
library(kableExtra)
library(ggthemes)
library(fixest)
library(magrittr)
library(stringr)

if (interactive()) {
    params = lst(
        fit_version = 95,
        rf_fit_version = 95,
        input_path = "data/stan_analysis_data",
        output_path = "temp-data",
        table_output_path = "presentations/tables",
        struct_models = "STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP_FOB",
        rf_models = "REDUCED_FORM_NO_RESTRICT",
        show_probs = FALSE,
        width = 0.95,
        cache = FALSE
    )
    # source(file.path("rct-design-fieldwork", "takeup_rct_assign_clusters.R"))
    # source(file.path("R/common/analysis.R"))
    # source(file.path( "R/structural/legacy-utils.R"))
    # source(file.path("multilvlr", "multilvlr_util.R"))
} else {
    # source(file.path("rct-design-fieldwork", "takeup_rct_assign_clusters.R"))
    # source(file.path("R/common/analysis.R"))
    # source(file.path( "R/structural/legacy-utils.R"))
    # source(file.path("multilvlr", "multilvlr_util.R"))
}

options(
    dplyr.show_progress = FALSE,
    digits = 4,
    knitr.kable.NA = '')

knitr::opts_chunk$set(
    echo = FALSE,
    cache = params$cache,
    warnings = FALSE,
    warning = FALSE,
    cache.path = stringr::str_glue("takeup-{params$struct_models}{params$fit_version}-balance-table-cache/"),
    fig.path = str_glue("takeup-{params$struct_models}{params$fit_version}-balance-table-fig-cache/"),
    fig.align = "center")

dir.create("presentations/tables", showWarnings = FALSE)

ci_width = as.numeric(params$width)
```



```{r, "load_analysis_data"}

treat_levels_c = c("control", "ink", "calendar", "bracelet")
treat_levels = c("ink", "calendar", "bracelet")
dist_levels = c("close", "far")


col_order = c(
  "lhs",
  "control_combined",
  paste0(treat_levels_c, "_close"),
  "close_joint_p",
  paste0(treat_levels_c, "_far"),
  "far_joint_p",
  "joint_p"
)

diff_names = c(
  "con",
  "ink - con",
  "cal - con",
  "bra - con",
  "bra - cal"
)

col_diff_order = c(
  "lhs",
  "con_combined",
  paste0(diff_names, "_close"),
  "close_joint_p",
  paste0(diff_names, "_far"),
  "far_joint_p",
  "joint_p"
)
#' Save Latex table
#'
#' This function saves a latex table to file whilst removing the table environment
#' this means we can just use \input{table} in the main tex file whilst controlling
#' placement/notes in the tex file itself (Anne doesn't use Rmd for everything :<( )
custom_save_latex_table = function(table, table_name){
  table_conn = file(
    file.path(
      params$table_output_path, paste0(table_name, ".tex")
    )
  )
  attr(table, "kable_meta")$contents = str_replace_all(attr(table, "kable_meta")$contents, "removeme12345", " ")
  table[1] = str_replace_all(table[1], "removeme12345", " ")

  clean_table = table %>%
    str_remove(
      .,
      fixed("\\begin{table}")
    ) %>%
    str_remove(
      .,
      "\\\\caption\\{.*\\}"
    ) %>%
    str_remove(
      .,
      "\\\\end\\{table\\}"
    )

    clean_table %>%
      writeLines(
        table_conn
      )
    close(table_conn)

    return(table)
}


# Format column names for kable (strip _close/_far suffixes, title-case, etc.)
comp_table_col_names = function(wide_df) {
  nms = colnames(wide_df) %>%
    str_replace("_close", "") %>%
    str_replace("_far", "") %>%
    str_replace("con_combined", "Sample mean") %>%
    str_to_title()
  nms[1] = ""
  nms[nms == "Joint_p"]       = "Joint Test"
  nms[nms == "Far_joint_p"]   = "Joint Test"
  nms[nms == "Close_joint_p"] = "Joint Test"
  nms
}

# Build the wide comp df for a given set of lhs variables + their joint tests.
# lhs_df   : rows of lhs_translation_df for the desired sample(s)
# fits      : named list (boot_fits), keyed by lhs name
build_comp_wide = function(comp_tidy, lhs_df, fits) {
  lhs_names = lhs_df$lhs

  get_pval = function(name, field) {
    f = fits[[name]]
    if (is.null(f)) NA_real_ else round(f[[field]], 4)
  }

  joint_pvals = tibble(
    lhs           = lhs_names,
    close_joint_p = map_dbl(lhs_names, get_pval, field = "close_pval"),
    far_joint_p   = map_dbl(lhs_names, get_pval, field = "far_pval"),
    joint_p       = map_dbl(lhs_names, get_pval, field = "joint_pval")
  )

  create_balance_input(
    comp_tidy %>%
      filter(lhs %in% lhs_names) %>%
      filter(comp_type == "treatment" | term == "sample_mean") %>%
      mutate(estimate = if_else(
        str_detect(lhs, "pct_") & lhs_treatment == "control",
        pmin(1, estimate), estimate
      )),
    col_order = col_order,
    digits    = 3,
    comp_df   = TRUE,
    show_pval = TRUE
  ) %>%
    left_join(joint_pvals, by = "lhs") %>%
    select(all_of(col_diff_order)) %>%
    mutate(across(where(is.character), ~if_else(.x == "", "-", .x))) %>%
    mutate(across(where(is.character), replace_na, "-")) %>%
    inner_join(lhs_df %>% select(lhs, clean_name, sample, row_num), by = "lhs") %>%
    mutate(lhs = clean_name) %>%
    select(-clean_name) %>%
    arrange(sample, row_num) %>%
    select(-sample, -row_num)
}

# Render a wide comp df as a kable and optionally save it.
render_comp_balance_table = function(wide_df, panel_list, caption, save_name = NULL) {
  tbl = wide_df %>%
    knitr::kable(
      format    = "latex",
      escape    = FALSE,
      booktabs  = TRUE,
      col.names = comp_table_col_names(wide_df),
      caption   = caption,
      align     = paste0("l", strrep("c", ncol(wide_df) - 1))
    ) %>%
    kable_styling(latex_options = "scale_down") %>%
    add_header_above(c("", "", "Close" = 6, "Far" = 6, "")) %>%
    pack_rows(
      index        = panel_list,
      italic       = TRUE,
      escape       = FALSE,
      hline_after  = TRUE,
      hline_before = TRUE,
      bold         = TRUE
    )
  if (!is.null(save_name)) tbl = tbl %>% custom_save_latex_table(save_name)
  tbl
}

build_dist_comp_wide = function(comp_tidy, lhs_df) {
  lhs_names = lhs_df$lhs

  levels_df = comp_tidy %>%
    filter(lhs %in% lhs_names, comp_type == "distance", is.na(rhs_treatment)) %>%
    mutate(estimate = if_else(
      str_detect(lhs, "pct_") & lhs_treatment == "control", pmin(1, estimate), estimate
    )) %>%
    select(lhs, lhs_treatment, estimate, std.error) %>%
    mutate(
      lhs_treatment = factor(lhs_treatment, treat_levels_c),
      across(c(estimate, std.error), round, 3),
      lhs_treatment = str_to_title(str_sub(lhs_treatment, 1, 3)),
      estim_std     = linebreak(paste0(estimate, "\n", str_glue("({std.error})")), align = "c")
    ) %>%
    select(-estimate, -std.error) %>%
    pivot_wider(names_from = lhs_treatment, values_from = estim_std)

  diffs_df = comp_tidy %>%
    filter(lhs %in% lhs_names, comp_type == "distance", !is.na(rhs_treatment)) %>%
    select(lhs, lhs_treatment, estimate, p.value) %>%
    mutate(
      lhs_treatment = factor(lhs_treatment, treat_levels_c),
      across(c(estimate, p.value), round, 3),
      lhs_treatment = paste0(
        "$\\textrm{", str_to_title(str_sub(lhs_treatment, 1, 3)), "}_{\\text{far - close}}$"
      ),
      estim_std = linebreak(paste0(estimate, "\n", str_glue("{{[{p.value}]}}")), align = "c")
    ) %>%
    select(-estimate, -p.value) %>%
    pivot_wider(names_from = lhs_treatment, values_from = estim_std)

  inner_join(levels_df, diffs_df, by = "lhs") %>%
    select(lhs, contains("Con"), contains("Ink"), contains("Cal"), contains("Bra")) %>%
    inner_join(lhs_df %>% select(lhs, clean_name, sample, row_num), by = "lhs") %>%
    mutate(lhs = clean_name) %>%
    select(-clean_name) %>%
    arrange(sample, row_num) %>%
    select(-sample, -row_num)
}

render_dist_comp_table = function(wide_df, panel_list, caption, save_name = NULL) {
  tbl = wide_df %>%
    knitr::kable(
      format    = "latex",
      col.names = c("", colnames(wide_df)[2:ncol(wide_df)]),
      escape    = FALSE,
      booktabs  = TRUE,
      align     = paste0("l", strrep("c", ncol(wide_df) - 1)),
      linesep   = "",
      caption   = caption
    ) %>%
    kable_styling(latex_options = "scale_down") %>%
    pack_rows(
      index        = panel_list,
      italic       = TRUE,
      escape       = FALSE,
      hline_after  = TRUE,
      hline_before = TRUE,
      bold         = TRUE
    )
  if (!is.null(save_name)) tbl = tbl %>% custom_save_latex_table(save_name)
  tbl
}

create_balance_input = function(tidy_df,
                                col_order,
                                digits = 3,
                                comp_df = FALSE,
                                show_pval = FALSE) {
  if (comp_df) {
    col_order_we_want = col_diff_order
  } else {
    col_order_we_want = col_order
  }
  bal_input_df = tidy_df %>%
      mutate(
      estimate = round(estimate, digits),
      std.error = round(std.error, digits),
      p.value = round(p.value, digits)
      )
  if (show_pval == TRUE) {
    bal_input_df = bal_input_df %>%
      mutate(below_val = p.value)
  } else {
    bal_input_df = bal_input_df %>%
      mutate(below_val = std.error)
  }

    if (comp_df == FALSE) {
      bal_input_df = bal_input_df %>%
        mutate(lhs_treat = str_extract(term, "(?<=disttreat: ).*(?=\\,)")) %>%
        mutate(lhs_dist = str_extract(term, "(?<=dist: ).*$"))
        # TODO RHS treat
    } else {
      bal_input_df = bal_input_df %>%
        mutate(
          lhs_treat = lhs_treatment,
          lhs_dist = lhs_dist,
          rhs_dist = rhs_dist,
          rhs_treat = rhs_treatment
        )
    }

  bal_input_df = bal_input_df %>%
      mutate(
        estim_std = case_when(
          # control close far, have SEs
          lhs_treat == "control" & lhs_dist != "combined" ~ linebreak(paste0(estimate, "\n", str_glue("({std.error})")), align = "c"),
          # sample mean (control, combined) just point estimate
          lhs_treat == "control" & lhs_dist == "combined" ~ linebreak(paste0(signif(estimate, digits = 3)), align = "c"),
          # treatment close far, have below_val (depending on fn option)
          TRUE ~ linebreak(paste0(estimate, "\n", "{[", below_val, "]}"), align = "c")
        )
      )

  if (comp_df == TRUE) {
    wide_bal_input_df = bal_input_df %>%
      select(term, lhs, lhs_treat, rhs_treat, lhs_dist, estim_std) %>%
      unique()  %>%
      mutate(
        treat_diff = paste0(str_sub(lhs_treat, 1, 3), " - ", str_sub(rhs_treat, 1,3)),
        treat_diff = if_else(is.na(rhs_treat),  str_sub(lhs_treat, 1, 3), treat_diff)
        )  %>%
      mutate(
        treat_diff = factor(treat_diff, levels = c(
          "con",
          "ink - con",
          "cal - con",
          "bra - con",
          "bra - cal"
        )),
        lhs_treat = factor(lhs_treat, treat_levels_c) %>% fct_rev(),
        lhs_dist = factor(lhs_dist, c(dist_levels, "combined")) %>% fct_rev()
      ) %>%
      select(lhs, treat_diff, lhs_dist, estim_std) %>%
      pivot_wider(
      names_from = c(treat_diff, lhs_dist),
      values_from = estim_std,
      )   %>%
      select(
      any_of(col_order_we_want)
      )

  } else {

    wide_bal_input_df = bal_input_df %>%
      select(lhs, lhs_treat, estim_std, lhs_dist) %>%
      mutate(
        col_name = paste0(lhs_treat, "_", lhs_dist)
      ) %>%
      select(lhs, estim_std, col_name) %>%
      spread(col_name, estim_std) %>%
      select(
        lhs,

        control_combined,

        control_close,
        ink_close,
        calendar_close,
        bracelet_close,

        control_far,
        ink_far,
        calendar_far,
        bracelet_far
      )
  }
  return(wide_bal_input_df)
}

```

```{r}
#| label: baseline-covariate-naming
lhs_translation_df = tribble(
  ~lhs, ~clean_name, ~sample,

  "lhs: adults_can_get_worms", "Know adults get worms", "baseline_worm",
  "lhs: know_children_get_worms", "Know children get worms", "baseline_worm",
  "lhs: sick_worms_only", "Believe deworming is for the sick", "baseline_worm",
  "lhs: know_medicine_stops_worms", "Know medication treats worms", "baseline_worm",
  "lhs: treated_lgl", "Dewormed in the past", "baseline_worm",
  "lhs: treated_past_year", "Dewormed in the past year", "baseline_worm",
  "lhs: correct_when_treat", "Know bi-yearly treatment recommended", "baseline_worm",
  "lhs: externality_omnibus", "Know worms impose externality", "baseline_worm",
  "lhs: family_treated_lgl", "$\\geq 1$ Family member dewormed", "baseline_worm",
  "lhs: adult_in_family_treated", "Adults in family dewormed", "baseline_worm",


  "lhs: floor_tile_cement", "Floor made of tile/cement", "pretreat",
  "lhs: completed_primary", "Completed primary schooling", "pretreat",
  "lhs: partially_aware_externalities", "Partially understands externalities", "baseline_worm",

  "lhs: age.census", "Age", "takeup_sample",
  "lhs: female", "Female", "takeup_sample",
  "lhs: have_phone_lgl", "Phone owner", "takeup_sample",
  "lhs: n_per_cluster", "Number of individuals per community", "takeup_sample",
  "lhs: cluster.dist.to.pot", "Distance to PoT", "takeup_sample",



  "lhs: belief_sample_age.census", "Age", "endline_belief_sample",
  "lhs: belief_sample_female", "Female", "endline_belief_sample",
  "lhs: belief_sample_have_phone_lgl", "Phone owner", "endline_belief_sample",
  "lhs: belief_sample_n_per_cluster", "Number of individuals per community", "endline_belief_sample",
  "lhs: belief_sample_cluster.dist.to.pot", "Distance to PoT", "endline_belief_sample",


  "lhs: years_schooling", "Years schooling", "pretreat",
  "lhs: ethnicity_luhya", "Main ethnicity/Luhya", "pretreat",
  "lhs: religion_christianity", "Christian", "pretreat",
  "lhs: know_deworm", "Know about community-based MDA?", "implementation",
  "lhs: treat_begin", "Know when MDA starts?", "implementation",
  "lhs: treat_end", "Know about MDA ends?", "implementation",
  "lhs: days_available", "Know length of MDA?", "implementation",
  "lhs: chv_visit", "Did a CHV visit you?", "implementation",

  "lhs: stigma_dewor", "Would you judge: Not deworming?", "social_image_concerns",
  "lhs: stigma_immuniz", "Would you judge: Not immunizing a child?", "social_image_concerns",
  "lhs: praise_dewor", "Would you praise: Deworming?", "social_image_concerns",
  "lhs: praise_immuniz", "Would you praise: Immunizing a child?", "social_image_concerns",

  "lhs: pct_announce", "Announcement about MDA in your community?", "implementation",
  "lhs: pct_knowledge_message", "CHV share deworming practices?", "implementation",
  "lhs: pct_avail_message", "CHV share where to get dewormed?", "implementation"
) %>%
  mutate(
    lhs_no_prefix = str_remove(lhs, "lhs: ")
  ) %>%
    mutate(
      row_num = row_number(),
      sample = factor(
        sample,
        levels =
        c(
          "takeup_sample",
          "pretreat",
          "baseline_worm",
          "social_image_concerns",
          "census",
          "implementation",
          "endline_belief_sample"
          ))) %>%
    arrange(sample, row_num)


```


```{r}
#| label: balance-reading

comp_balance_tidy_df = read_csv(
  file.path("temp-data", "comp_balance_tidy_df.csv")
)

balance_data = read_rds(
  file.path(
    "temp-data",
    "saved_balance_data.rds"
  )
)

balance_analysis_data = balance_data$analysis_data
baseline_worm_data = balance_data$baseline_worm_data
endline_vars = balance_data$endline_vars
endline_and_baseline_worm_data = balance_data$endline_and_baseline_worm_data
pretreat_data = balance_data$pretreat_data
clean_census_data = balance_data$clean_census_data

```



```{r}
#| label: joint-tests

boot_fits = read_rds(
  file.path("temp-data",
            "cluster_balance_fits.rds")
)

joint_signif_fstats = map_dbl(
  boot_fits, "joint_pval"
) %>% round(4)

close_joint_signif_fstats = map_dbl(
  boot_fits, "close_pval"
) %>% round(4)

far_joint_signif_fstats = map_dbl(
  boot_fits, "far_pval"
) %>%
  round(4)





stratum_map = balance_analysis_data %>%
  mutate(stratum = county) %>%
  mutate(stratum_id = as.integer(stratum)) %>%
  distinct(stratum_id, stratum)


N_pretreat = nrow(baseline_worm_data)
N_census = nrow(clean_census_data)
N_takeup = nrow(balance_analysis_data)
N_baseline_worm = nrow(baseline_worm_data)
N_social_image = N_pretreat
N_endline = nrow(balance_data$endline_worm_data)
N_endline_belief = balance_data$N_endline_belief


N_baseline_worm_obs  = baseline_worm_data  %>%
  group_by(treat_dist) %>%
  summarise(
    N_indiv = n_distinct(KEY),
    N_pot = n_distinct(cluster.id)
  ) %>%
  mutate(
    type = "baseline"
  )



```


```{r}
#| label: balance-creation
#| dependson: balance-setup
#| eval: false



comp_wide_indiv_bal_df = create_balance_input(
    comp_balance_tidy_df %>%
      filter(comp_type == "treatment" | term == "sample_mean") %>%
      mutate(estimate = if_else(str_detect(lhs, "pct_") & lhs_treatment == "control", pmin(1, estimate), estimate)),
    col_order = col_order,
    digits = 3,
    comp_df = TRUE,
    show_pval = TRUE
)  %>%
  mutate(
    close_joint_p = close_joint_signif_fstats,
    far_joint_p = far_joint_signif_fstats,
    joint_p = joint_signif_fstats
  ) %>%
 select(all_of(col_diff_order)) %>%
  mutate(across(where(is.character), ~if_else(.x == "", "-", .x))) %>%
  mutate(across(where(is.character), replace_na, "-")) %>%
  inner_join(lhs_translation_df %>% select(lhs, clean_name, sample, row_num)) %>%
  mutate(lhs = clean_name) %>%
  select(-clean_name) %>%
  arrange(sample, row_num) %>%
  select(-sample, -row_num)



1+1

```

## Balance

```{r, results="asis"}
#| label: comp-balance-table
#| dependson: [balance-setup, balance-creation]

main_lhs_df = lhs_translation_df %>%
  filter(!sample %in% c("endline_belief_sample", "social_image_concerns"))

comp_wide_indiv_bal_df = build_comp_wide(comp_balance_tidy_df, main_lhs_df, boot_fits)

main_panel_label_map = c(
  takeup_sample  = str_glue("Panel A: Takeup sample, $N={format(N_takeup, big.mark = ',')}$"),
  pretreat       = str_glue("Panel B: Baseline demographics, $N={format(N_pretreat, big.mark = ',')}$"),
  baseline_worm  = str_glue("Panel C: Deworming knowledge, $N={format(N_baseline_worm, big.mark = ',')}$"),
  implementation = str_glue("Panel D: Implementation, $N={format(N_endline, big.mark = ',')}$")
)

main_panel_list = main_lhs_df %>%
  filter(clean_name %in% comp_wide_indiv_bal_df$lhs) %>%
  count(sample) %>%
  arrange(sample) %>%
  { setNames(.$n, main_panel_label_map[as.character(.$sample)]) }

render_comp_balance_table(
  comp_wide_indiv_bal_df,
  main_panel_list,
  caption   = "Balance Table",
  save_name = "comp-balance-table"
)

```


```{r, results="asis"}
#| label: pretreat-baseline-balance-table
#| dependson: [balance-setup, balance-creation]

pretreat_baseline_lhs_df = lhs_translation_df %>%
  filter(sample %in% c("pretreat", "baseline_worm", "social_image_concerns"))

pretreat_baseline_wide = build_comp_wide(comp_balance_tidy_df, pretreat_baseline_lhs_df, boot_fits)

pretreat_baseline_panel_list = pretreat_baseline_lhs_df %>%
  filter(clean_name %in% pretreat_baseline_wide$lhs) %>%
  count(sample) %>%
  arrange(sample) %>%
  { setNames(.$n, c(
      pretreat              = str_glue("Panel A: Baseline sample - demographics, $N={format(N_pretreat, big.mark = ',')}$"),
      baseline_worm         = str_glue("Panel B: Baseline sample - deworming knowledge, $N={format(N_baseline_worm, big.mark = ',')}$"),
      social_image_concerns = str_glue("Panel C: Social image concerns, $N={format(N_social_image, big.mark = ',')}$")
    )[as.character(.$sample)]) }

render_comp_balance_table(
  pretreat_baseline_wide,
  pretreat_baseline_panel_list,
  caption   = "Baseline sample demographics and deworming knowledge balance",
  save_name = "baseline-demo-deworming-knowledge-balance-table"
)

```

```{r, results="asis"}
#| label: implementation-balance-table
#| dependson: [balance-setup, balance-creation]

impl_lhs_df = lhs_translation_df %>%
  filter(sample == "implementation")

impl_wide = build_comp_wide(comp_balance_tidy_df, impl_lhs_df, boot_fits)

impl_panel_list = setNames(
  nrow(impl_wide),
  str_glue("Panel A: Endline sample - implementation, $N={format(N_endline, big.mark = ',')}$")
)

render_comp_balance_table(
  impl_wide,
  impl_panel_list,
  caption   = "Implementation Balance Table",
  save_name = "implementation-balance-table"
)

```

```{r, results="asis"}
#| label: implementation-dist-balance-table
#| dependson: [balance-setup, balance-creation]

impl_dist_wide = build_dist_comp_wide(comp_balance_tidy_df, impl_lhs_df)

impl_dist_panel_list = setNames(
  nrow(impl_dist_wide),
  str_glue("Panel A: Endline sample - implementation, $N={format(N_endline, big.mark = ',')}$")
)

render_dist_comp_table(
  impl_dist_wide,
  impl_dist_panel_list,
  caption   = "Implementation Balance Table: Distance Differentials",
  save_name = "implementation-dist-balance-table"
)

```

```{r, results="asis"}
#| label: dist-comp-balance-table

dist_comp_wide = build_dist_comp_wide(comp_balance_tidy_df, main_lhs_df)

render_dist_comp_table(
  dist_comp_wide,
  main_panel_list,
  caption   = "Distance Comparison Balance table",
  save_name = "dist-comp-balance-table"
)

```



```{r, results="asis"}
#| label: endline-beliefs-table

belief_lhs_df = lhs_translation_df %>%
  filter(sample == "endline_belief_sample")

belief_wide = build_comp_wide(comp_balance_tidy_df, belief_lhs_df, boot_fits)

belief_panel_list = setNames(
  nrow(belief_wide),
  str_glue("Belief sample, $N=1,441$")
)

render_comp_balance_table(
  belief_wide,
  belief_panel_list,
  caption   = "Belief Sample Balance",
  save_name = "belief-sample-balance-table"
)

belief_dist_wide = build_dist_comp_wide(comp_balance_tidy_df, belief_lhs_df)

render_dist_comp_table(
  belief_dist_wide,
  belief_panel_list,
  caption   = "Belief Sample Distance Comparison",
  save_name = "belief-sample-dist-comp-table"
)

```


```{r}
#| label: endline-table
#| eval: false


endline_balance_df = create_balance_input(
    endline_tidy_df %>% filter(!str_detect(term, "county")),
    col_order = col_order[!str_detect(col_order, "_p$")],
    digits = 3
)   %>%
  mutate(type = "fit") %>%
  bind_rows(
    endline_p_val_df %>%
      mutate(across(where(is.numeric), round, 3)) %>%
      mutate_all(as.character) %>%
      mutate(type = "pval")
  ) %>%
  mutate(lhs = str_remove(lhs, "lhs: ")) %>%
  left_join(lhs_translation_df %>% select(lhs = lhs_no_prefix, clean_name)) %>%
  mutate(lhs = clean_name) %>%
  select(-clean_name) %>%
  arrange(lhs, type) %>%
  mutate(lhs = if_else(type == "pval", paste0("$\\Delta$", lhs, ", $p$-value"), lhs)) %>%
  select(-type) %>%
  mutate(across(where(is.character), ~if_else(.x == "", "-", .x))) %>%
  mutate(across(where(is.character), replace_na, "-")) %>%
  select(all_of(col_order))

treat_colnames = str_to_title(treat_levels_c)
endline_bal_table = endline_balance_df %>%
knitr::kable(
    format = "latex",
    escape = FALSE,
    col.names = c("", treat_colnames, "F-test $p$-value", treat_colnames, "F-test $p$-value", "Joint F-test $p$-value"),
    booktabs = TRUE,
    caption = "Endline Table",
    align = "lccccccccccc",
    linesep = "",
) %>%
kable_styling(
  latex_options = c("scale_down")
) %>%
add_header_above(c("", "Close" = 5, "Far" = 5, ""))

endline_bal_table %>%
  custom_save_latex_table("endline-table")


```



```{r}
#| label: cts-distance-pval-table
#| eval: false
1+1


rename_lhs = function(data, name_var = term) {
  data %>%
    mutate({{name_var}} := str_remove({{name_var}}, "lhs: ")) %>%
      mutate(
        {{ name_var }} := str_replace_all({{ name_var }}, "_", " ") %>%
          str_to_title()
      )  %>%
  mutate(
    {{name_var}} := case_when(
      {{ name_var  }} == "N Indiv" ~ "N individuals",
      {{ name_var }} == "N Pot" ~ "N points of treatment",
     {{ name_var}}  == "Cluster Dist To Pot" ~ "Cluster distance to PoT",
     {{ name_var}}  == "Baseline Neighbours Worm Knowledge" ~ "Understand deworming externality, baseline",
     {{ name_var}}  == "Treated Lgl" ~ "Dewormed self",
     {{ name_var}}  == "Months Since Treatment" ~ "Months since last dewormed",
     {{ name_var}}  == "Know deworming stops worms" ~ "Knowledge of deworming medication",
     {{ name_var}}  == "All Can Get Worms" ~ "Know everyone can be infected",
     {{ name_var}}  == "Correct When Treat" ~ "Know bi-yearly treatment recommended",
     {{ name_var}}  == "Num Recognised" ~ "Number of individuals recognised in community",
      TRUE ~ {{name_var}}
    )
  )
}

 cts_distance_pval_df = read_rds(
  file.path(
    "temp-data",
    "discrete_cts_dist_balance.rds"
  )
) %>%
  enframe(name = "lhs")  %>%
  left_join(
    lhs_translation_df %>%
    select(lhs, clean_name)) %>%
  mutate(lhs = clean_name) %>%
  select(-clean_name)

```


```{r}
#| label: baseline-perception-balance
#| eval: false

baseline_perception_data = read_rds(
  "temp-data/praise_stigma_baseline.rds"
)

baseline_perception_fits = baseline_perception_data[[1]]
baseline_perception_pvals = baseline_perception_data[[2]]


tidy_b_p_fits = map_dfr(
  baseline_perception_fits,
  tidy,
  .id = "sample"
)  %>%
  mutate(
    topic = str_extract(sample, "(?<=sample: )\\w+$")
  ) %>%
  filter(str_detect(term, "treat_dist")) %>%
  mutate(
    sample = rep(c("praise", "stigma"), each = n()/2)
  ) %>%
  mutate(
    treatment = str_extract(term, "(?<=disttreat: )\\w+"),
    distance = str_extract(term, "(?<=, dist: )\\w+$")
  ) %>%
  select(
    sample, topic, treatment, distance, estimate, std.error
  ) %>%
  mutate(
    across(where(is.numeric), round, 3),
    estim_std = linebreak(
      paste0(
        estimate, "\n",
        str_glue(
          "({std.error})"
        )
      ),
      align = "c"
    )
  )  %>%
  select(-estimate, -std.error)

wide_tidy_b_p_fits = tidy_b_p_fits %>%
  pivot_wider(
    names_from = c(treatment, distance),
    values_from = estim_std
  ) %>%
  select(
    sample,
    topic,


    control_close,
    ink_close,
    calendar_close,
    bracelet_close,


    control_far,
    ink_far,
    calendar_far,
    bracelet_far
  )


joint_baseline_perception_pvals = map_dbl(baseline_perception_pvals, "joint_pval") %>%
  enframe() %>%
  mutate(
    sample = rep(c("praise", "stigma"), each = n()/2)
  ) %>%
  mutate(
    topic = str_extract(name, "(?<=sample: )\\w+$")
  ) %>%
  select(
    sample,
    topic,
    p_val = value
  ) %>%
  mutate(
    p_val = round(p_val, 3)
  )

wide_tidy_b_p_fits = wide_tidy_b_p_fits %>%
  left_join(
    joint_baseline_perception_pvals,
    by = c("sample", "topic")
  ) %>%
  mutate(
    topic = case_when(
      topic == "clothe" & sample == "praise" ~ "Wearing nice clothes to church",
      topic == "defecat" & sample == "praise" ~ "Use latrine",
      topic == "dewor" & sample == "praise" ~ "Deworming during MDA",
      topic == "immuniz" & sample == "praise" ~ "Immunizing children",

      topic == "clothe" & sample == "stigma" ~ "Not wearing nice clothes to church",
      topic == "defecat" & sample == "stigma" ~ "Open defecation",
      topic == "dewor" & sample == "stigma" ~ "Not deworming during MDA",
      topic == "immuniz" & sample == "stigma" ~ "Not immunizing children",
    )
  ) %>%
  mutate(
    sample = str_to_title(sample)
  )

baseline_perception_tbl = wide_tidy_b_p_fits %>%
  select(-sample) %>%
  kbl(
    col.names = c(
      "Topic",

      "Control",
      "Ink",
      "Calendar",
      "Bracelet",

      "Control",
      "Ink",
      "Calendar",
      "Bracelet",

      "Joint Test"
    ),
    format = "latex",
    booktabs = TRUE,
    escape = FALSE,
    align = "lccccccccc",
    caption = "Baseline Perception Balance"
  )  %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(
    c(
      " " = 1,
      "Close" = 4,
      "Far" = 4,
      " " = 1
      )
  ) %>%
  pack_rows(
    index = c(
      "Panel A: Praise" = 4,
      "Panel A: Stigma" = 4
    ),
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space,
    hline_after = TRUE,
    hline_before = TRUE,
    bold = TRUE
  )

baseline_perception_tbl %>%
  custom_save_latex_table(
    "baseline-perception-table"
  )


```



```{r}
#| label: main-sample-balance
main_balance_samples = read_rds(
  file.path(
    "temp-data",
    "main-balance-samples.rds"
  )
)
names(main_balance_samples)

takeup_bal_fit = main_balance_samples$takeup_sample
endline_know_bal_fit = main_balance_samples$endline_know_sample

takeup_bal_jt = main_balance_samples$takeup_bal_joint_test
endline_know_bal_jt = main_balance_samples$endline_know_bal_joint_test


takeup_bal_comp_df = read_csv(
  file.path("temp-data", 
    "comp_takeup_balance_tidy_df.csv")
)

endline_know_comp_df = read_csv(
  file.path("temp-data", 
    "comp_endline_know_balance_tidy_df.csv")
)

endline_know_close_pvals = map_dbl(endline_know_bal_jt, "close_pval") %>% round(4)
endline_know_far_pvals = map_dbl(endline_know_bal_jt, "far_pval") %>% round(4)
endline_know_joint_pvals = map_dbl(endline_know_bal_jt, "joint_pval") %>% round(4)


takeup_close_pvals = map_dbl(takeup_bal_jt, "close_pval") %>% round(4)
takeup_far_pvals = map_dbl(takeup_bal_jt, "far_pval") %>% round(4)
takeup_joint_pvals = map_dbl(takeup_bal_jt, "joint_pval") %>% round(4)

takeup_treat_wide = create_balance_input(
  takeup_bal_comp_df %>%
    filter(comp_type == "treatment" | term == "sample_mean") %>%
    mutate(estimate = if_else(str_detect(lhs, "pct_") & lhs_treatment == "control", pmin(1, estimate), estimate)),
  col_order = col_order,
  digits = 3,
  comp_df = TRUE,
  show_pval = TRUE
) %>%
  mutate(
    close_joint_p = takeup_close_pvals,
    far_joint_p = takeup_far_pvals,
    joint_p = takeup_joint_pvals
  ) %>%
  select(all_of(col_diff_order)) %>%
  mutate(across(where(is.character), ~if_else(.x == "", "-", .x))) %>%
  mutate(across(where(is.character), replace_na, "-")) %>%
  inner_join(lhs_translation_df %>% select(lhs, clean_name, sample, row_num)) %>%
  mutate(lhs = clean_name) %>%
  select(-clean_name) %>%
  arrange(sample, row_num) %>%
  select(-sample, -row_num)

clean_bal_names = function(data) {
  colnames(data) = colnames(data) %>%
    str_replace("_close", "") %>%
    str_replace("_far", "") %>%
    str_replace("con_combined", "Sample mean") %>%
    str_to_title()
  return(data)
}

create_colnames = function(data) {
   col_names = colnames(data)
   col_names[1] = ""
   col_names[col_names == "Joint_p"] = "Joint Test"
   col_names[col_names == "Far_joint_p"] = "Joint Test"
   col_names[col_names == "Close_joint_p"] = "Joint Test"
   return(col_names)
}

takeup_treat_wide = clean_bal_names(takeup_treat_wide)
takeup_col_names = create_colnames(takeup_treat_wide)


takeup_bal_tbl = takeup_treat_wide %>%
  knitr::kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    col.names = takeup_col_names,
    caption = "Takeup Sample Balance",
    align = paste0("l", strrep("c", ncol(takeup_treat_wide) - 1))
  ) %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(c("", "", "Close" = 6, "Far" = 6, "")) 


takeup_bal_tbl %>%
  custom_save_latex_table("takeup-sample-only-balance-table")

# now do the same for endline know sample balance
endline_treat_wide = create_balance_input(
  endline_know_comp_df %>%
    filter(comp_type == "treatment" | term == "sample_mean") %>%
    mutate(estimate = if_else(str_detect(lhs, "pct_") & lhs_treatment == "control", pmin(1, estimate), estimate)),
  col_order = col_order,
  digits = 3,
  comp_df = TRUE,
  show_pval = TRUE
) %>%
  mutate(
    close_joint_p = endline_know_close_pvals,
    far_joint_p = endline_know_far_pvals,
    joint_p = endline_know_joint_pvals
  ) %>%
  select(all_of(col_diff_order)) %>%
  mutate(across(where(is.character), ~if_else(.x == "", "-", .x))) %>%
  mutate(across(where(is.character), replace_na, "-")) %>%
  inner_join(lhs_translation_df %>% select(lhs, clean_name, sample, row_num)) %>%
  mutate(lhs = clean_name) %>%
  select(-clean_name) %>%
  arrange(sample, row_num) %>%
  select(-sample, -row_num)

endline_treat_wide = clean_bal_names(endline_treat_wide)
endline_col_names = create_colnames(endline_treat_wide)

endline_bal_tbl = endline_treat_wide %>%
  knitr::kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    col.names = endline_col_names,
    caption = "Endline Sample Balance",
    align = paste0("l", strrep("c", ncol(endline_treat_wide) - 1))
  ) %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(c("", "", "Close" = 6, "Far" = 6, ""))

endline_bal_tbl %>%
  custom_save_latex_table("endline-sample-only-balance-table")


stacked_sample_wide = rbind(
  takeup_treat_wide,
  endline_treat_wide 
) 


stacked_sample_tbl = stacked_sample_wide %>%
  knitr::kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    col.names = endline_col_names,
    caption = "Endline Sample Balance",
    align = paste0("l", strrep("c", ncol(endline_treat_wide) - 1))
  ) %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(c("", "", "Close" = 6, "Far" = 6, "")) %>%
  pack_rows(
    index = c(
      "Panel A: Take-up analysis sample, $N=9,805$" = nrow(takeup_treat_wide),
      "Panel B: Endline observability sample, $N=1,141$" = nrow(endline_treat_wide)
    ),
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space,
    hline_after = TRUE,
    hline_before = TRUE,
    bold = TRUE
  )

stacked_sample_tbl %>%
  custom_save_latex_table("stacked-sample-balance-table")

```

```{r, results="asis"}
#| label: stacked-sample-dist-balance

takeup_lhs_df = lhs_translation_df %>%
  filter(lhs %in% unique(takeup_bal_comp_df$lhs))

endline_know_lhs_df = lhs_translation_df %>%
  filter(lhs %in% unique(endline_know_comp_df$lhs))

takeup_dist_wide = build_dist_comp_wide(takeup_bal_comp_df, takeup_lhs_df)
endline_know_dist_wide = build_dist_comp_wide(endline_know_comp_df, endline_know_lhs_df)

stacked_dist_wide = rbind(takeup_dist_wide, endline_know_dist_wide)

stacked_dist_tbl = stacked_dist_wide %>%
  knitr::kable(
    format    = "latex",
    col.names = c("", colnames(stacked_dist_wide)[2:ncol(stacked_dist_wide)]),
    escape    = FALSE,
    booktabs  = TRUE,
    linesep   = "",
    align     = paste0("l", strrep("c", ncol(stacked_dist_wide) - 1)),
    caption   = "Sample Balance: Distance Differentials"
  ) %>%
  kable_styling(latex_options = "scale_down") %>%
  pack_rows(
    index = c(
      "Panel A: Take-up analysis sample, $N=9,805$"       = nrow(takeup_dist_wide),
      "Panel B: Endline observability sample, $N=1,141$"  = nrow(endline_know_dist_wide)
    ),
    italic       = TRUE,
    escape       = FALSE,
    hline_after  = TRUE,
    hline_before = TRUE,
    bold         = TRUE
  )

stacked_dist_tbl %>%
  custom_save_latex_table("stacked-sample-dist-balance-table")

```

```{r}
#| label: attrition-treat-balance

attrition_treat_comp_df = read_csv(
  file.path("temp-data", "attrition_treat_comp_df.csv")
)

attrition_treat_data = read_rds(
  file.path("temp-data", "attrition_treat_joint_tests.rds")
)
attrition_treat_joint_tests = attrition_treat_data$joint_tests
N_attrition = attrition_treat_data$n_attrition

attrition_treat_joint_signif = map_dbl(attrition_treat_joint_tests, "joint_pval") %>% round(4)
attrition_treat_close_joint = map_dbl(attrition_treat_joint_tests, "close_pval") %>% round(4)
attrition_treat_far_joint = map_dbl(attrition_treat_joint_tests, "far_pval") %>% round(4)

attrition_treat_wide = create_balance_input(
  attrition_treat_comp_df %>%
    filter(comp_type == "treatment" | term == "sample_mean") %>%
    mutate(estimate = if_else(str_detect(lhs, "pct_") & lhs_treatment == "control", pmin(1, estimate), estimate)),
  col_order = col_order,
  digits = 3,
  comp_df = TRUE,
  show_pval = TRUE
) %>%
  mutate(
    close_joint_p = attrition_treat_close_joint,
    far_joint_p = attrition_treat_far_joint,
    joint_p = attrition_treat_joint_signif
  ) %>%
  select(all_of(col_diff_order)) %>%
  mutate(across(where(is.character), ~if_else(.x == "", "-", .x))) %>%
  mutate(across(where(is.character), replace_na, "-")) %>%
  inner_join(lhs_translation_df %>% select(lhs, clean_name, sample, row_num)) %>%
  mutate(lhs = clean_name) %>%
  select(-clean_name) %>%
  arrange(sample, row_num) %>%
  select(-sample, -row_num)


colnames(attrition_treat_wide) = colnames(attrition_treat_wide) %>%
  str_replace("_close", "") %>%
  str_replace("_far", "") %>%
  str_replace("con_combined", "Sample mean") %>%
  str_to_title()

att_treat_col_names = colnames(attrition_treat_wide)
att_treat_col_names[1] = ""
att_treat_col_names[att_treat_col_names == "Joint_p"] = "Joint Test"
att_treat_col_names[att_treat_col_names == "Far_joint_p"] = "Joint Test"
att_treat_col_names[att_treat_col_names == "Close_joint_p"] = "Joint Test"

att_treat_panel_df = lhs_translation_df %>%
  filter(clean_name %in% attrition_treat_wide$Lhs) %>%
  count(sample) %>%
  mutate(sample = factor(
    sample,
    levels = c("takeup_sample", "pretreat", "baseline_worm", "social_image_concerns", "census", "implementation")
  )) %>%
  filter(!is.na(sample)) %>%
  arrange(sample) %>%
  data.table::data.table()

N_att_fmt = format(N_attrition, big.mark = ",")
att_treat_panel_names = att_treat_panel_df$sample %>%
  as.character() %>%
  recode(
    "takeup_sample" = str_glue("Panel A: Takeup sample, $N={N_att_fmt}$"),
    "pretreat" = str_glue("Panel B: Baseline demographics, $N={N_att_fmt}$"),
    "baseline_worm" = str_glue("Panel C: Deworming knowledge, $N={N_att_fmt}$"),
    "implementation" = str_glue("Panel D: Implementation, $N={N_att_fmt}$")
  )

att_treat_panel_list = att_treat_panel_df$n
names(att_treat_panel_list) = att_treat_panel_names

attrition_treat_bal_table = attrition_treat_wide %>%
  knitr::kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    col.names = att_treat_col_names,
    caption = "Attrition Treatment Balance",
    align = paste0("l", strrep("c", ncol(attrition_treat_wide) - 1))
  ) %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(c("", "", "Close" = 6, "Far" = 6, "")) %>%
  pack_rows(
    index = att_treat_panel_list,
    italic = TRUE,
    escape = FALSE,
    hline_after = TRUE,
    hline_before = TRUE,
    bold = TRUE
  )

attrition_treat_bal_table %>%
  custom_save_latex_table("attrition-treat-balance-table")

```


```{r}
#| label: non-attrition-treat-balance

non_attrition_treat_comp_df = read_csv(
  file.path("temp-data", "non_attrition_treat_comp_df.csv")
)

non_attrition_treat_data = read_rds(
  file.path("temp-data", "non_attrition_treat_joint_tests.rds")
)
non_attrition_treat_joint_tests = non_attrition_treat_data$joint_tests
N_non_attrition = non_attrition_treat_data$n_non_attrition

non_attrition_treat_joint_signif = map_dbl(non_attrition_treat_joint_tests, "joint_pval") %>% round(4)
non_attrition_treat_close_joint = map_dbl(non_attrition_treat_joint_tests, "close_pval") %>% round(4)
non_attrition_treat_far_joint = map_dbl(non_attrition_treat_joint_tests, "far_pval") %>% round(4)

non_attrition_treat_wide = create_balance_input(
  non_attrition_treat_comp_df %>%
    filter(comp_type == "treatment" | term == "sample_mean") %>%
    mutate(estimate = if_else(str_detect(lhs, "pct_") & lhs_treatment == "control", pmin(1, estimate), estimate)),
  col_order = col_order,
  digits = 3,
  comp_df = TRUE,
  show_pval = TRUE
) %>%
  mutate(
    close_joint_p = non_attrition_treat_close_joint,
    far_joint_p = non_attrition_treat_far_joint,
    joint_p = non_attrition_treat_joint_signif
  ) %>%
  select(all_of(col_diff_order)) %>%
  mutate(across(where(is.character), ~if_else(.x == "", "-", .x))) %>%
  mutate(across(where(is.character), replace_na, "-")) %>%
  inner_join(lhs_translation_df %>% select(lhs, clean_name, sample, row_num)) %>%
  mutate(lhs = clean_name) %>%
  select(-clean_name) %>%
  arrange(sample, row_num) %>%
  select(-sample, -row_num)

colnames(non_attrition_treat_wide) = colnames(non_attrition_treat_wide) %>%
  str_replace("_close", "") %>%
  str_replace("_far", "") %>%
  str_replace("con_combined", "Sample mean") %>%
  str_to_title()

non_att_treat_col_names = colnames(non_attrition_treat_wide)
non_att_treat_col_names[1] = ""
non_att_treat_col_names[non_att_treat_col_names == "Joint_p"] = "Joint Test"
non_att_treat_col_names[non_att_treat_col_names == "Far_joint_p"] = "Joint Test"
non_att_treat_col_names[non_att_treat_col_names == "Close_joint_p"] = "Joint Test"

non_att_treat_panel_df = lhs_translation_df %>%
  filter(clean_name %in% non_attrition_treat_wide$Lhs) %>%
  count(sample) %>%
  mutate(sample = factor(
    sample,
    levels = c("takeup_sample", "pretreat", "baseline_worm", "social_image_concerns", "census", "implementation")
  )) %>%
  filter(!is.na(sample)) %>%
  arrange(sample) %>%
  data.table::data.table()

N_non_att_fmt = format(N_non_attrition, big.mark = ",")
non_att_treat_panel_names = non_att_treat_panel_df$sample %>%
  as.character() %>%
  recode(
    "takeup_sample" = str_glue("Panel A: Takeup sample, $N={N_non_att_fmt}$"),
    "pretreat" = str_glue("Panel B: Baseline demographics, $N={N_non_att_fmt}$"),
    "baseline_worm" = str_glue("Panel C: Deworming knowledge, $N={N_non_att_fmt}$"),
    "implementation" = str_glue("Panel D: Implementation, $N={N_non_att_fmt}$")
  )

non_att_treat_panel_list = non_att_treat_panel_df$n
names(non_att_treat_panel_list) = non_att_treat_panel_names

non_attrition_treat_bal_table = non_attrition_treat_wide %>%
  knitr::kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    col.names = non_att_treat_col_names,
    caption = "Non-Attrited Treatment Balance",
    align = paste0("l", strrep("c", ncol(non_attrition_treat_wide) - 1))
  ) %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(c("", "", "Close" = 6, "Far" = 6, "")) %>%
  pack_rows(
    index = non_att_treat_panel_list,
    italic = TRUE,
    escape = FALSE,
    hline_after = TRUE,
    hline_before = TRUE,
    bold = TRUE
  )

non_attrition_treat_bal_table %>%
  custom_save_latex_table("non-attrition-treat-balance-table")

```


```{r}
#| label: monitoring-attrition-treat-balance

mon_attrition_comp_df = read_csv(
  file.path("temp-data", "monitoring_attrition_comp_df.csv")
)

mon_attrition_data = read_rds(
  file.path("temp-data", "monitoring_attrition_joint_tests.rds")
)
mon_attrition_joint_tests = mon_attrition_data$joint_tests
N_mon_attrition = mon_attrition_data$n_mon_attrition

mon_attrition_joint_signif = map_dbl(mon_attrition_joint_tests, "joint_pval") %>% round(4)
mon_attrition_close_joint = map_dbl(mon_attrition_joint_tests, "close_pval") %>% round(4)
mon_attrition_far_joint = map_dbl(mon_attrition_joint_tests, "far_pval") %>% round(4)

mon_attrition_lhs_df = tribble(
  ~lhs, ~clean_name, ~sample, ~row_num,
  "lhs: age.census", "Age", "census", 1L,
  "lhs: female", "Female", "census", 2L,
  "lhs: n_per_cluster", "Number of individuals per community", "census", 4L,
  "lhs: cluster.dist.to.pot", "Distance to PoT", "census", 5L
) %>%
  mutate(lhs_no_prefix = str_remove(lhs, "lhs: "))

mon_attrition_wide = create_balance_input(
  mon_attrition_comp_df %>%
    filter(comp_type == "treatment" | term == "sample_mean"),
  col_order = col_order,
  digits = 3,
  comp_df = TRUE,
  show_pval = TRUE
) %>%
  mutate(
    close_joint_p = mon_attrition_close_joint,
    far_joint_p = mon_attrition_far_joint,
    joint_p = mon_attrition_joint_signif
  ) %>%
  select(all_of(col_diff_order)) %>%
  mutate(across(where(is.character), ~if_else(.x == "", "-", .x))) %>%
  mutate(across(where(is.character), replace_na, "-")) %>%
  inner_join(mon_attrition_lhs_df %>% select(lhs, clean_name, sample, row_num)) %>%
  mutate(lhs = clean_name) %>%
  select(-clean_name) %>%
  arrange(sample, row_num) %>%
  select(-sample, -row_num)

colnames(mon_attrition_wide) = colnames(mon_attrition_wide) %>%
  str_replace("_close", "") %>%
  str_replace("_far", "") %>%
  str_replace("con_combined", "Sample mean") %>%
  str_to_title()

mon_att_col_names = colnames(mon_attrition_wide)
mon_att_col_names[1] = ""
mon_att_col_names[mon_att_col_names == "Joint_p"] = "Joint Test"
mon_att_col_names[mon_att_col_names == "Far_joint_p"] = "Joint Test"
mon_att_col_names[mon_att_col_names == "Close_joint_p"] = "Joint Test"

N_mon_att_fmt = format(N_mon_attrition, big.mark = ",")
mon_att_panel_list = c(length(unique(mon_attrition_lhs_df$lhs)))
names(mon_att_panel_list) = str_glue("Panel A: Census variables, $N={N_mon_att_fmt}$")

mon_attrition_bal_table = mon_attrition_wide %>%
  knitr::kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    col.names = mon_att_col_names,
    caption = "Monitoring Attrition Treatment Balance",
    align = paste0("l", strrep("c", ncol(mon_attrition_wide) - 1))
  ) %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(c("", "", "Close" = 6, "Far" = 6, "")) %>%
  pack_rows(
    index = mon_att_panel_list,
    italic = TRUE,
    escape = FALSE,
    hline_after = TRUE,
    hline_before = TRUE,
    bold = TRUE
  )

mon_attrition_bal_table %>%
  custom_save_latex_table("monitoring-attrition-balance-table")

```


```{r}
#| label: mon-non-attrition-treat-balance

mon_non_attrition_comp_df = read_csv(
  file.path("temp-data", "mon_non_attrition_comp_df.csv")
)

mon_non_attrition_data = read_rds(
  file.path("temp-data", "mon_non_attrition_joint_tests.rds")
)
mon_non_attrition_joint_tests = mon_non_attrition_data$joint_tests
N_mon_non_attrition = mon_non_attrition_data$n_mon_non_attrition

mon_non_attrition_joint_signif = map_dbl(mon_non_attrition_joint_tests, "joint_pval") %>% round(4)
mon_non_attrition_close_joint = map_dbl(mon_non_attrition_joint_tests, "close_pval") %>% round(4)
mon_non_attrition_far_joint = map_dbl(mon_non_attrition_joint_tests, "far_pval") %>% round(4)

mon_non_attrition_wide = create_balance_input(
  mon_non_attrition_comp_df %>%
    filter(comp_type == "treatment" | term == "sample_mean"),
  col_order = col_order,
  digits = 3,
  comp_df = TRUE,
  show_pval = TRUE
) %>%
  mutate(
    close_joint_p = mon_non_attrition_close_joint,
    far_joint_p = mon_non_attrition_far_joint,
    joint_p = mon_non_attrition_joint_signif
  ) %>%
  select(all_of(col_diff_order)) %>%
  mutate(across(where(is.character), ~if_else(.x == "", "-", .x))) %>%
  mutate(across(where(is.character), replace_na, "-")) %>%
  inner_join(mon_attrition_lhs_df %>% select(lhs, clean_name, sample, row_num)) %>%
  mutate(lhs = clean_name) %>%
  select(-clean_name) %>%
  arrange(sample, row_num) %>%
  select(-sample, -row_num)

colnames(mon_non_attrition_wide) = colnames(mon_non_attrition_wide) %>%
  str_replace("_close", "") %>%
  str_replace("_far", "") %>%
  str_replace("con_combined", "Sample mean") %>%
  str_to_title()

mon_non_att_col_names = colnames(mon_non_attrition_wide)
mon_non_att_col_names[1] = ""
mon_non_att_col_names[mon_non_att_col_names == "Joint_p"] = "Joint Test"
mon_non_att_col_names[mon_non_att_col_names == "Far_joint_p"] = "Joint Test"
mon_non_att_col_names[mon_non_att_col_names == "Close_joint_p"] = "Joint Test"

N_mon_non_att_fmt = format(N_mon_non_attrition, big.mark = ",")
mon_non_att_panel_list = c(length(unique(mon_attrition_lhs_df$lhs)))
names(mon_non_att_panel_list) = str_glue("Panel A: Census variables, $N={N_mon_non_att_fmt}$")

mon_non_attrition_bal_table = mon_non_attrition_wide %>%
  knitr::kable(
    format = "latex",
    escape = FALSE,
    booktabs = TRUE,
    col.names = mon_non_att_col_names,
    caption = "Monitoring Non-Dropped Treatment Balance",
    align = paste0("l", strrep("c", ncol(mon_non_attrition_wide) - 1))
  ) %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(c("", "", "Close" = 6, "Far" = 6, "")) %>%
  pack_rows(
    index = mon_non_att_panel_list,
    italic = TRUE,
    escape = FALSE,
    hline_after = TRUE,
    hline_before = TRUE,
    bold = TRUE
  )

mon_non_attrition_bal_table %>%
  custom_save_latex_table("mon-non-attrition-balance-table")

```


```{r, results="asis"}
#| label: sms-balance-table

sms_balance      <- read_rds(file.path("temp-data", "sms_balance.rds"))
sms_comp_rmd     <- sms_balance$sms_comp_df
N_sms_control    <- sms_balance$N_sms_control
N_sms_treat      <- sms_balance$N_sms_treat

sms_itt_balance       <- read_rds(file.path("temp-data", "sms_itt_balance.rds"))
sms_itt_comp_rmd      <- sms_itt_balance$sms_itt_comp_df
N_sms_itt_control     <- sms_itt_balance$N_sms_control
N_sms_itt_treat       <- sms_itt_balance$N_sms_treat

sms_lhs_df = tribble(
  ~lhs,                             ~clean_name,
  "lhs: age",                       "Age",
  "lhs: female",                    "Female",
  "lhs: have_phone_lgl",            "Phone owner",
  "lhs: n_per_cluster",             "Individuals per community",
  "lhs: cluster.dist.to.pot",       "Distance to PoT (km)"
)

fmt3 = function(x) formatC(round(x, 3), format = "f", digits = 3)
build_sms_wide = function(comp_df) {
  con_wide = comp_df %>%
    # filter(comp_type == "treatment", lhs_treatment == "smscontrol", is.na(rhs_treatment), is.na(term)) %>%
    filter(comp_type == "control_mean") %>%
    mutate(con_cell = linebreak(paste0(fmt3(estimate), "\n(", fmt3(std.error), ")"), align = "c")) %>%
    select(lhs, con_cell)

  diff_wide = comp_df %>%
    filter(comp_type == "treatment", lhs_treatment == "smstreatment") %>%
    mutate(diff_cell = linebreak(paste0(fmt3(estimate), "\n{[", fmt3(p.value), "]}"), align = "c")) %>%
    select(lhs, diff_cell)

  sms_lhs_df %>%
    left_join(con_wide,  by = "lhs") %>%
    left_join(diff_wide, by = "lhs") %>%
    select(clean_name, con_cell, diff_cell) %>%
    filter(clean_name != "Phone owner")
}

sms_itt_table_df  = build_sms_wide(sms_itt_comp_rmd)
sms_table_df      = build_sms_wide(sms_comp_rmd)

stacked_sms_df = rbind(sms_itt_table_df, sms_table_df)

sms_itt_panel_label = paste0(
  "Panel A: SMS ITT sample, $N_{\\mathrm{control}}=", format(N_sms_itt_control, big.mark = ","),
  "$, $N_{\\\\mathrm{treat}}=", format(N_sms_itt_treat, big.mark = ","), "$"
)
sms_enrolled_panel_label = paste0(
  "Panel B: SMS enrolled sample, $N_{\\mathrm{control}}=", format(N_sms_control, big.mark = ","),
  "$, $N_{\\\\mathrm{treat}}=", format(N_sms_treat, big.mark = ","), "$"
)

sms_bal_tbl = stacked_sms_df %>%
  knitr::kable(
    format    = "latex",
    escape    = FALSE,
    booktabs  = TRUE,
    col.names = c(
      "",
      linebreak("Control\n(SE)", align = "c"),
      linebreak("SMS Treat $-$ Control", align = "c")
    ),
    caption   = "SMS Sample Balance",
    align     = "lcc",
    linesep   = ""
  ) %>%
  kable_styling(latex_options = "scale_down") %>%
  pack_rows(
    index        = setNames(
      c(nrow(sms_itt_table_df), nrow(sms_table_df)),
      c(sms_itt_panel_label, sms_enrolled_panel_label)
    ),
    italic       = TRUE,
    bold         = TRUE,
    escape       = FALSE,
    hline_after  = TRUE,
    hline_before = TRUE
  )

sms_bal_tbl %>%
  custom_save_latex_table("sms-balance-table")

```


```{r, results="asis"}
#| label: sms-enrollment-balance-table

sms_enrollment_balance <- read_rds(file.path("temp-data", "sms_enrollment_balance.rds"))
comp_sms_enrollment    <- sms_enrollment_balance$enrollment_balance_comp
enrollment_jt          <- sms_enrollment_balance$enrollment_balance_joint_tests

enrollment_lhs_df = tribble(
  ~lhs,                ~clean_name,              ~sample,       ~row_num,
  "lhs: sms_enrolled", "Enrolled in SMS study",  "enrollment",  1L
) %>%
  mutate(sample = factor(sample))

comp_sms_enrollment_lhs = comp_sms_enrollment %>%
  mutate(
    lhs  = "lhs: sms_enrolled",
    term = NA_character_
  )

enrollment_fits = list("lhs: sms_enrolled" = enrollment_jt)

enrollment_wide = build_comp_wide(comp_sms_enrollment_lhs, enrollment_lhs_df, enrollment_fits)

enrollment_panel_list = setNames(
  nrow(enrollment_wide),
  str_glue("Panel A: SMS treatment sample, $N={format(N_sms_itt_treat, big.mark = ',')}$")
)

sms_enrol_tbl = render_comp_balance_table(
  enrollment_wide,
  enrollment_panel_list,
  caption   = "SMS Enrollment Balance",
  save_name = "sms-enrollment-balance-table"
)
sms_enrol_tbl %>%
  custom_save_latex_table("sms-enrollment-balance-table")
```


```{r, sample_n, results="asis"}

# sample_meta_df = N_by_treat_dist_df %>%
#   gather(variable, value, -type, -lhs) %>%
#   group_by(
#     type, lhs
#   ) %>%
#   summarise(
#     n = sum(value, na.rm = TRUE)
#   ) %>%
#   ungroup() %>%
#   spread(lhs, n) %>%
#   mutate(
#     sample = case_when(
#       type == "beliefs" ~ "Beliefs",
#       type == "takeup" ~ "Takeup",
#       type == "WTP" ~ "WTP"
#     )
#   ) %>%
#   select(-type) %>%
#   select(sample, everything())



# sample_meta_tbl = sample_meta_df %>%
#     kbl(
#         booktabs = TRUE,
#         format = "latex",
#         caption = "Sample Size Across Experiments",
#         align = "lcc",
#         col.names = c("Experiment", "N Individuals", "N PoTs")
#     )  %>%
#     kable_styling()
# sample_meta_tbl

```
