---
title: "Tables"
output: 
  pdf_document:
    keep_tex: yes
header-includes:
    - \usepackage{booktabs}
    - \usepackage{longtable}
    - \usepackage{array}
    - \usepackage{multirow}
    - \usepackage{wrapfig}
    - \usepackage{float}
    - \usepackage{colortbl}
    - \usepackage{tabu}
    - \usepackage{threeparttable}
    - \usepackage{threeparttablex}
    - \usepackage[normalem]{ulem}
    - \usepackage[utf8]{inputenc}
    - \usepackage{makecell}
    - \usepackage{xcolor}
    - \usepackage{pdflscape}
    - \newcommand{\blandscape}{\begin{landscape}}
    - \newcommand{\elandscape}{\end{landscape}}
params:
    fit_version: 95
    rf_fit_version: 95
    input_path: data/stan_analysis_data
    output_path: temp-data 
    optim_input_path: "optim/data/STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP/agg-full-many-pots"
    table_output_path: presentations/tables
    struct_models: STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP_FOB
    rf_models: REDUCED_FORM_NO_RESTRICT
    show_probs: FALSE
    cache: FALSE
    width: 0.95
---



```{r, "startup", include=FALSE}
library(tidyverse)
library(posterior)
library(tidybayes)
library(marginaleffects)
library(broom)
library(data.table)
library(knitr)
library(kableExtra)
library(ggthemes)
library(fixest)
library(magrittr)
library(stringr)

if (interactive()) {
    params = lst(
        fit_version = 95,
        rf_fit_version = 95,
        input_path = "data/stan_analysis_data",
        output_path = "temp-data",
        optim_input_path =  "optim/data/STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP/agg-full-many-pots",
        table_output_path = "presentations/tables",
        struct_models = "STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP_FOB",
        rf_models = "REDUCED_FORM_NO_RESTRICT",
        show_probs = FALSE,
        width = 0.95,
        cache = TRUE
    )
    source(file.path("rct-design-fieldwork", "takeup_rct_assign_clusters.R"))
    source(file.path("analysis_util.R"))
    source(file.path( "dist_structural_util.R"))
    source(file.path("multilvlr", "multilvlr_util.R"))
} else {
    source(file.path("rct-design-fieldwork", "takeup_rct_assign_clusters.R"))
    source(file.path("analysis_util.R"))
    source(file.path( "dist_structural_util.R"))
    source(file.path("multilvlr", "multilvlr_util.R"))
}

models_we_want = c(params$struct_models, params$rf_models)

options(
    dplyr.show_progress = FALSE, 
    digits = 4, 
    knitr.kable.NA = '')

knitr::opts_chunk$set(
    echo = FALSE, 
    cache = params$cache, 
    warnings = FALSE,
    warning = FALSE,
    cache.path = stringr::str_glue("takeup-{params$struct_models}{params$fit_version}-table-cache/"), 
    fig.path = str_glue("takeup-{params$struct_models}{params$fit_version}-table-fig-cache/"), 
    fig.align = "center")

dir.create("presentations/tables", showWarnings = FALSE)


ci_width = as.numeric(params$width)
```




```{r, "load_analysis_data"}

fit_version = params$fit_version

treat_levels_c = c("control", "ink", "calendar", "bracelet")
treat_levels = c("ink", "calendar", "bracelet")
dist_levels = c("close", "far")
model_level_order = c("reduced form", "structural")

quant_probs <- c(0.01, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99)

output_basepath = file.path(
  params$output_path,
  str_glue("output_dist_fit{params$fit_version}")
)


canva_palette_vibrant <- "Primary colors with a vibrant twist"

theme_set(theme_minimal() +
            theme(legend.position = "bottom"))

wgs.84 <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
kenya.proj4 <- "+proj=utm +zone=36 +south +ellps=clrk80 +units=m +no_defs"
rct.schools.data <- read_rds(file.path("data", "takeup_rct_schools.rds"))
rct.cluster.selection <- read_rds(file.path("data", "rct_cluster_selection_2.0.rds"))
cluster.strat.data <- read_rds(file.path("data", "takeup_processed_cluster_strat.rds"))
load(file.path("data", "takeup_village_pot_dist.RData"))
load(file.path("data", "analysis.RData"))


standardize <- as_mapper(~ (.) / sd(.))
unstandardize <- function(standardized, original) standardized * sd(original)

nosms_data <- analysis.data %>% 
  filter(sms.treatment.2 == "sms.control") %>% 
  left_join(village.centers %>% select(cluster.id, cluster.dist.to.pot = dist.to.pot),
            by = "cluster.id") %>% 
  mutate(standard_cluster.dist.to.pot = standardize(cluster.dist.to.pot)) %>% 
  group_by(cluster.id) %>% 
  mutate(cluster_id = cur_group_id()) %>% 
  ungroup()

monitored_nosms_data <- analysis.data %>% 
  filter(mon_status == "monitored", sms.treatment.2 == "sms.control") %>% 
  left_join(village.centers %>% select(cluster.id, cluster.dist.to.pot = dist.to.pot),
            by = "cluster.id") %>% 
  mutate(standard_cluster.dist.to.pot = standardize(cluster.dist.to.pot)) %>% 
  group_by(cluster.id) %>% 
  mutate(cluster_id = cur_group_id()) %>% 
  ungroup()


analysis_data <- monitored_nosms_data

#' Save Latex table 
#' 
#' This function saves a latex table to file whilst removing the table environment
#' this means we can just use \input{table} in the main tex file whilst controlling 
#' placement/notes in the tex file itself (Anne doesn't use Rmd for everything :<( )
custom_save_latex_table = function(table, table_name){
  table_conn = file(
    file.path(
      params$table_output_path, paste0(table_name, ".tex")
    )
  )
  # Create space in latex due to rmd bug with \\ immediately followed by [
  # table = table  %>%
  #   str_replace_all(., "removeme12345", "  ")

  attr(table, "kable_meta")$contents = str_replace_all(attr(table, "kable_meta")$contents, "removeme12345", " ")
  table[1] = str_replace_all(table[1], "removeme12345", " ")


  clean_table = table %>%
    str_remove(
      ., 
      fixed("\\begin{table}")
    ) %>%
    str_remove(
      .,
      "\\\\caption\\{.*\\}"
    ) %>%
    str_remove(
      ., 
      "\\\\end\\{table\\}"
    ) 
    
    
    clean_table %>%
      writeLines(
        table_conn
      )
    close(table_conn)

    return(table)
}
```



```{r, tidy_output_loading}

tidy_fit_param_df = bind_rows(
  read_rds(
    file.path(
      "temp-data",
      str_glue(
          "tidy_processed_dist_fit{params$fit_version}_{params$struct_model}_1-4.rds"
      )
    )
  ),
  read_rds(
    file.path(
      "temp-data",
      str_glue(
          "tidy_processed_dist_fit{params$rf_fit_version}_{params$rf_model}_1-4.rds"
      )
    )
  )
)
tidy_prior_param_df = bind_rows(
  read_rds(
    file.path(
      "temp-data",
      str_glue(
          "tidy_processed_dist_prior{params$fit_version}_{params$struct_model}_1-4.rds"
      )
    )
  ),
  read_rds(
    file.path(
      "temp-data",
      str_glue(
          "tidy_processed_dist_prior{params$rf_fit_version}_{params$rf_model}_1-4.rds"
      )
    )
  ),

)
tidy_param_df = bind_rows(
  tidy_fit_param_df,
  tidy_prior_param_df
)

tidy_param_df = tidy_param_df %>%
  mutate(
    model_type = if_else(str_detect(model, "STRUCT"), "structural", "reduced form") %>% factor(),
    fit_type = factor(fit_type),
    model = factor(model)
  )

tidy_param_df = tidy_param_df %>%
  mutate(
    dist_group_present = map_lgl(tidy_draws, ~"dist_group" %in% colnames(.x)),
    param = factor(param)
    ) %>%
  mutate(
    tidy_draws = map_if(
      tidy_draws,
      dist_group_present,
      ~mutate(
        .x,
        dist_group = factor(dist_group, levels = c("combined", "close", "far")),
        dist_group = fct_relabel(dist_group, str_to_title)
        )
      ),
      model_name = if_else(model_type == "structural", "Structural", "Reduced Form"),
  ) %>%
  left_join(tribble(
    ~ fit_type,        ~ model_color,
      "fit",           "black", 
      "prior-predict", "darkgrey",
  ), by = "fit_type") 



```



## Sample Info
```{r, sample_table, eval=FALSE}

stan_data = (dist_fit_data %>%
  filter(fct_match(model_type, "structural")) %>%
  select(stan_data) %>%
  pull())[[1]]

```


```{r}



# rf_analysis_data <- dist_fit_data %>% 
#   filter(
#     fct_match(model_type, "reduced form"),
#     fct_match(fit_type, "fit"),
#   ) %$% 
#   stan_data[[1]]$analysis_data 

rf_N = analysis_data %>%
  select(dewormed, assigned.treatment, dist.pot.group) %>%
  complete.cases() %>%
  sum()
print(
  str_glue("RF N: {rf_N}")
)
```




```{r}
#| create-te-df

ate_rvar_struct = read_rds(
      file.path(
        "temp-data",
        str_glue("rvar_processed_dist_fit{params$fit_version}_ates_{params$struct_models}_1-4.rds")
      ) 
  )
ate_rvar_rf = read_rds(
      file.path(
        "temp-data",
        str_glue("rvar_processed_dist_fit{params$rf_fit_version}_ates_{params$rf_models}_1-4.rds")
      ) 
  )
# weird bind_rows() bug with rvar cols
ate_rvar_df = bind_rows(
    ate_rvar_struct %>% 
      select(-value),
    ate_rvar_rf %>%
      select(-value)
)
ate_rvar_df$value = c(ate_rvar_struct$value, ate_rvar_rf$value)

create_cis = function(.data, .width = 0.95) {
  med_fun = function(x) {
    mean_x = mean(x) %>% round(3)
    conf.low = quantile(x, (1 - .width)/2) %>% round(3)
    conf.high = quantile(x, 1 - (1 - .width)/2) %>% round(3)
  
    return_val = linebreak(
      paste0(
        mean_x, "\n", str_glue(
          "({conf.low}, {conf.high})"
        )
      ), align = "c"
    )
    return(return_val)
  }
  .data %>%
    mutate(across(where(is_rvar), med_fun))
}


create_ate_table = function(.data, .estimand, group_var = treatment) {
  .data %>%
    filter(estimand == .estimand) %>%
    select(
      model,
      {{ group_var }},
      dist_group,
      value
    ) %>%
    pivot_wider(
      names_from = dist_group,
      values_from = value
    ) %>%
    select(model, {{ group_var }}, any_of(c("combined", "close", "far"))) %>%
    arrange({{ group_var }}) %>%
    bind_rows(
      # bracelet minus calendar row
      .data %>%
        filter({{ group_var }} %in% c("Bracelet", "Calendar")) %>%
        filter(estimand == .estimand) %>%
        pivot_wider(names_from = {{ group_var }}, values_from = value) %>%
        mutate(
          bracelet_minus_calendar = Bracelet - Calendar
        ) %>%
        select(model, dist_group, bracelet_minus_calendar) %>%
        pivot_wider(
          names_from = dist_group,
          values_from = bracelet_minus_calendar
        ) %>%
        mutate("{{ group_var }}" := "bracelet_minus_calendar")
    )
}

incentive_ate_df =  ate_rvar_df %>%
  create_ate_table(
    .estimand = "overall",
    group_var = treatment
  )





signal_ate_df = ate_rvar_df %>%
  filter(model == params$struct_models) %>%
  mutate(mu_treatment = str_to_title(mu_treatment)) %>%
  create_ate_table(
    .estimand = "signal",
    group_var = mu_treatment
  )

private_ate_df = ate_rvar_df %>%
  filter(model == params$struct_models) %>%
  create_ate_table(
    .estimand = "private",
    group_var = treatment
  )


ate_tbl_levels = c(
    "Bracelet",
    "Calendar",
    "Ink",
    "bracelet_minus_calendar",
    "Control"
)

recode_control_mean = function(data) {
  data %>%
    mutate(
      treatment = fct_recode(treatment, "Control mean" = "Control", "Bracelet - Calendar" = "bracelet_minus_calendar")
    )
}

spread_rf = function(data) {
  data %>%
    mutate(model_type = case_when(
      model == params$struct_models ~ "struct",
      model == params$rf_models ~ "rf"
    )) %>%
    select(-model) %>%
    pivot_wider(
      names_from = model_type,
      id_cols = treatment,
      names_glue = "{model_type}_{.value}",
      values_from = any_of(c("combined", "close", "far", "far_minus_close"))
    ) %>%
    select(treatment, starts_with("rf"), starts_with("struct"))
}

incentive_ate_tbl = incentive_ate_df %>%
  mutate(treatment = factor(treatment, levels = 
    ate_tbl_levels
  )) %>%
  mutate(far_minus_close = far - close) %>%
  arrange(treatment)   %>%
  create_cis(.width = params$width) %>%
  recode_control_mean()  %>%
  spread_rf() %>%
  mutate(estimand = "overall")

private_ate_tbl = private_ate_df %>%
  mutate(treatment = factor(treatment, levels = 
    ate_tbl_levels
  )) %>%
  arrange(treatment)   %>%
  create_cis(.width = params$width) %>%
  recode_control_mean() %>%
  spread_rf() %>%
  mutate(estimand = "private")

signal_ate_tbl = signal_ate_df %>%
  rename(treatment = mu_treatment) %>%
  mutate(treatment = factor(treatment, levels = 
    ate_tbl_levels
  )) %>%
  mutate(far_minus_close = far - close) %>%
  arrange(treatment)   %>%
  create_cis(.width = params$width) %>%
  recode_control_mean() %>%
  spread_rf() %>%
  mutate(estimand = "signal")



all_ate_tbl = bind_rows(
  incentive_ate_tbl,
  signal_ate_tbl,
  private_ate_tbl
) %>%
  mutate(estimand = factor(estimand, levels = c('private', 'signal', 'overall')) %>% fct_rev) %>%
  select(estimand, treatment, everything())


```


```{r}
latex_group_gap_space = "2em"
1+2
```


```{r, results="asis"}
1+3

te_kbl_df = all_ate_tbl %>% 
  arrange(estimand, treatment) %>%
  select(-estimand) %>%
  kbl(
    col.names = c(
      # "Estimand", 
      # "Treatment", 
      "Dependent variable: Take-up",
      paste0("(", 1:8, ")")
    ), 
    format = "latex", 
    linesep = "\\addlinespace \\addlinespace \\addlinespace",
    booktabs = TRUE, 
    escape = FALSE, 
    align = "lcccccccc", 
    caption = "Results"
  )  %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(
    c(" ", 
      "Combined", 
      "Close", 
      "Far", 
      "Far - Close",
      "Combined",
      "Close", 
      "Far",
      "Far - Close"
      ), 
    line = FALSE
  ) %>%
  add_header_above(
    c(
      " " = 1,
      "Reduced Form" = 4, 
      "Structural" = 4
      )
  ) %>%
  pack_rows(
    index = c(
      "Panel A: Overall" = 5, 
      "Panel B: Signalling" = 5, 
      "Panel C: Private" = 5
    ), 
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space, 
    hline_after = TRUE, 
    hline_before = TRUE,
    bold = TRUE
  )  %>%
  row_spec(c(3, 8, 13), hline_after = TRUE) 


te_kbl_df %>%
  custom_save_latex_table(
    "te-table"
  )

x = 1 + 5
```


#### Split Table ####
```{r}
#| overall-table-only
overall_te_kbl_df = all_ate_tbl %>% 
  arrange(estimand, treatment) %>%
  filter(estimand == "overall") %>%
  select(-estimand) %>%
  kbl(
    col.names = c(
      "Dependent variable: Take-up",
      paste0("(", 1:8, ")")
    ), 
    format = "latex", 
    linesep = "\\addlinespace \\addlinespace \\addlinespace",
    booktabs = TRUE, 
    escape = FALSE, 
    align = "lcccccccc", 
    caption = "Overall Results") %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(
    c(" ", 
      "Combined", 
      "Close", 
      "Far", 
      "Far - Close",
      "Combined",
      "Close", 
      "Far",
      "Far - Close"
      ), 
    line = FALSE
  ) %>%
  add_header_above(
    c(
      " " = 1,
      "Reduced Form" = 4, 
      "Structural" = 4
      )
  ) %>%
  pack_rows(
    index = c(
      "Panel A: Overall" = 5
    ), 
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space, 
    hline_after = TRUE, 
    hline_before = TRUE,
    bold = TRUE
  )  %>%
  row_spec(c(3), hline_after = TRUE) 


overall_te_kbl_df %>%
  custom_save_latex_table(
    "overall-te-table"
  )

```


```{r}
#|
struct_overall_tbl = all_ate_tbl %>% 
  arrange(estimand, treatment) %>%
  filter(estimand == "overall") %>%
  select(-estimand) %>%
  select(-contains("rf_")) %>%
  kbl(
    col.names = c(
      "Dependent variable: Take-up",
      paste0("(", 1:4, ")")
    ), 
    format = "latex", 
    linesep = "\\addlinespace \\addlinespace \\addlinespace",
    booktabs = TRUE, 
    escape = FALSE, 
    align = "lcccc", 
    caption = "Overall Results") %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(
    c(" ", 
      "Combined", 
      "Close", 
      "Far", 
      "Far - Close"
      ), 
    line = FALSE
  ) %>%
  add_header_above(
    c(
      " " = 1,
      "Structural" = 4
      )
  ) %>%
  pack_rows(
    index = c(
      "Panel A: Overall" = 5
    ), 
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space, 
    hline_after = TRUE, 
    hline_before = TRUE,
    bold = TRUE
  )  %>%
  row_spec(c(3), hline_after = TRUE) 


struct_overall_tbl %>%
  custom_save_latex_table(
    "struct-overall-te-table"
  )


```

```{r}
#| rf-table-only
rf_overall_tbl = all_ate_tbl %>% 
  arrange(estimand, treatment) %>%
  filter(estimand == "overall") %>%
  select(-estimand) %>%
  select(-contains("struct_")) %>%
  kbl(
    col.names = c(
      "Dependent variable: Take-up",
      paste0("(", 1:4, ")")
    ), 
    format = "latex", 
    linesep = "\\addlinespace \\addlinespace \\addlinespace",
    booktabs = TRUE, 
    escape = FALSE, 
    align = "lcccc", 
    caption = "Overall Results") %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(
    c(" ", 
      "Combined", 
      "Close", 
      "Far", 
      "Far - Close"
      ), 
    line = FALSE
  ) %>%
  add_header_above(
    c(
      " " = 1,
      "Reduced Form" = 4
      )
  ) %>%
  pack_rows(
    index = c(
      "Panel A: Overall" = 5
    ), 
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space, 
    hline_after = TRUE, 
    hline_before = TRUE,
    bold = TRUE
  )  %>%
  row_spec(c(3), hline_after = TRUE) 


rf_overall_tbl %>%
  custom_save_latex_table(
    "rf-overall-te-table"
  )


```

```{r}
#| private-signal-tbl, results="asis"


decomposed_te_kbl_df = all_ate_tbl %>% 
  arrange(estimand, treatment) %>%
  filter(estimand %in% c("signal", "private")) %>%
  select(estimand, treatment, contains('struct')) %>%
  select(-estimand) %>%
  kbl(
    col.names = c(
      "Dependent variable: Take-up",
      paste0("(", 1:4, ")")
    ), 
    # format = "latex", 
    linesep = "\\addlinespace \\addlinespace \\addlinespace",
    booktabs = TRUE, 
    escape = FALSE, 
    align = "lcccccccc", 
    caption = "Overall Results") %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(
    c(" ", 
      "Combined", 
      "Close", 
      "Far", 
      "Far - Close"
      ), 
    line = FALSE
  ) %>%
  add_header_above(
    c(
      " " = 1,
      "Structural" = 4
      )
  ) %>%
  pack_rows(
    index = c(
      "Panel A: Signal" = 5,
      "Panel B: Private" = 5
    ), 
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space, 
    hline_after = TRUE, 
    hline_before = TRUE,
    bold = TRUE
  )  %>%
  row_spec(c(3, 8), hline_after = TRUE) 

# Q for Anne:
# do we want control mean signal/private value or overall control mean at bottom

decomposed_te_kbl_df %>%
  custom_save_latex_table(
    "private-signal-te-table"
  )
```


```{r}
#| beliefs

belief_df = bind_rows(
tidy_param_df %>%
  filter(
  fct_match(fit_type, "fit"), 
  fct_match(model, params$struct_model), 
  fct_match(model_type, "structural"),
  param %in% c('belief_probs')
  ) %>%
  select(model, tidy_draws) %>%
  unnest(tidy_draws) %>%
  filter(.width == params$width) %>%
  filter(treatment == "Control") %>%
  mutate(
    across(where(is.numeric), round, 3),
    estim_std = linebreak(
      paste0(
        value, "\n",
        str_glue(
          "({conf.low}, {conf.high})"
        )
      ),
      align = "c"
    )
  ) %>%
  select(treatment, dist_group, variable, estim_std)  ,
tidy_param_df %>%
  filter(
  fct_match(fit_type, "fit"), 
  fct_match(model, params$struct_model), 
  fct_match(model_type, "structural"),
  param %in% c('belief_ates')
  ) %>%
  select(model, tidy_draws) %>%
  unnest(tidy_draws) %>%
  filter(.width == params$width) %>%
  mutate(
    across(where(is.numeric), round, 3),
    estim_std = linebreak(
      paste0(
        value, "\n",
        str_glue(
          "({conf.low}, {conf.high})"
        )
      ),
      align = "c"
    )
  ) %>%
  select(treatment, dist_group, variable, estim_std)  
) %>%
  mutate(order = if_else(str_detect(variable, "1"), 1, 2)) %>%
  select(-variable)


wide_belief_df = belief_df %>%
  pivot_wider(
    names_from = c(dist_group, order), 
    values_from = estim_std
  ) %>%
  select(
    treatment,
    Combined_1,
    Close_1,
    Far_1,

    Combined_2,
    Close_2,
    Far_2
  ) %>%
  mutate(treatment = factor(treatment, levels = str_to_title(treat_levels_c)) %>% fct_rev) %>%
  mutate(treatment = fct_recode(treatment, "Control mean" = "Control")) %>%
  arrange(treatment)


wide_belief_tbl = wide_belief_df %>%
  kbl(
    col.names = c(
      # "Estimand", 
      # "Treatment", 
      "",
      paste0("(", 1:6, ")")
    ), 
    # format = "latex", 
    booktabs = TRUE, 
    escape = FALSE, 
    align = "lcccccc", 
    linesep = "\\addlinespace \\addlinespace \\addlinespace",
    caption = "Beliefs Results"
  ) %>%
  kable_styling(
    # latex_options = c("scale_down")
  ) %>%
  add_header_above(
    c(" ", 
      "Combined",
      "Close", 
      "Far", 
      "Combined",
      "Close", 
      "Far"
      ), 
    line = FALSE
  )  %>%
  add_header_above(
    c(
      " " = 1,
      "First-Order Beliefs" = 3, 
      "Second-Order Beliefs" = 3
      )
  ) %>%
  footnote(
    escape = FALSE,
    threeparttable = TRUE
  )


wide_belief_tbl %>%
  custom_save_latex_table(
    "beliefs-table"
  )
```



```{r}
#| disagg-beliefs

disagg_base_belief_data = analysis_data %>%
  mutate(assigned_treatment = assigned.treatment, assigned_dist_group = dist.pot.group) %>%
  nest_join(
    endline.know.table.data %>% 
      filter(fct_match(know.table.type, "table.A")),
    by = "KEY.individ", 
    name = "knowledge_data"
  ) %>% 
  mutate(
    map_dfr(knowledge_data, ~ {
      tibble(
        obs_know_person = sum(.x$num.recognized),
        obs_know_person_prop = mean(.x$num.recognized),
        knows_other_dewormed = sum(fct_match(.x$dewormed, c("yes", "no")), na.rm = TRUE),
        knows_other_dewormed_yes = sum(fct_match(.x$dewormed, "yes"), na.rm = TRUE),
        knows_other_dewormed_no = sum(fct_match(.x$dewormed, "no"), na.rm = TRUE),
        thinks_other_knows = sum(fct_match(.x$second.order, c("yes", "no")), na.rm = TRUE),
        thinks_other_knows_yes = sum(fct_match(.x$second.order, "yes"), na.rm = TRUE),
        thinks_other_knows_no = sum(fct_match(.x$second.order, "no"), na.rm = TRUE),
      )
    }
  )) %>%
    filter(obs_know_person > 0)  %>%
    select(
      KEY.individ, 
      contains("know"), 
      assigned.treatment, 
      dist.pot.group, 
      assigned_dist_group,
      cluster.id,
      county
      ) %>%
    mutate(
        doesnt_know_other_dewormed = obs_know_person - knows_other_dewormed, 
        doesnt_think_other_knows = obs_know_person - thinks_other_knows
    ) %>% 
    select(KEY.individ, 
           assigned.treatment,
           assigned_dist_group,
           obs_know_person,
           knows_other_dewormed_yes,
           knows_other_dewormed_no,
           doesnt_know_other_dewormed, 
           thinks_other_knows_yes, 
           thinks_other_knows_no, 
           doesnt_think_other_knows,
           cluster.id,
           county
           ) %>%
    gather(variable, value, 
        knows_other_dewormed_yes:doesnt_think_other_knows)   %>%
    mutate(knowledge_type = case_when(
        str_detect(variable, "_yes") ~ "yes",
        str_detect(variable, "_no") ~ "no",
        str_detect(variable, "doesnt") ~ "doesn't know"
    )) %>%
    mutate(belief_type = if_else(str_detect(variable, "think"), "2ord", "1ord")) %>%
    mutate(prop = value/obs_know_person) 

cv = function(alpha){
  qnorm(1 - (alpha/2))
}

close_far_disagg_belief = disagg_base_belief_data  %>%
    group_by(assigned.treatment, assigned_dist_group, knowledge_type, belief_type)  %>%
    summarise(
        mean_est = mean(prop), 
        std.error = sd(prop)/sqrt(n()),
        per_0.5 = mean(prop), 
        per_0.05 = per_0.5 - cv(0.05)*std.error, 
        per_0.95 = per_0.5 + cv(0.05)*std.error,
        per_0.975 = per_0.5 + cv(0.025)*std.error,
        per_0.025 = per_0.5 - cv(0.025)*std.error,
        per_0.1 =  per_0.5 - cv(0.1)*std.error,
        per_0.9 =  per_0.5 + cv(0.1)*std.error,
        per_0.25 =  per_0.5 - cv(0.5)*std.error,
        per_0.75 =  per_0.5 + cv(0.5)*std.error
    ) %>%
    mutate(
      knowledge_type = factor(knowledge_type, levels = c("yes", "no", "doesn't know")), 
      knowledge_type = fct_relabel(knowledge_type, str_to_title) %>% fct_rev
    ) %>%
    mutate(
      assigned.treatment = factor(assigned.treatment, 
                                  levels = c("bracelet",
                                             "calendar", 
                                             "ink",
                                             "control")) %>%
                          fct_relabel(str_to_title) %>%
                          fct_rev
    )


cv = function(alpha){
  qnorm(1 - (alpha/2))
}

combined_disagg_belief = disagg_base_belief_data  %>%
    group_by(assigned.treatment, knowledge_type, belief_type)  %>%
    summarise(
        mean_est = mean(prop), 
        std.error = sd(prop)/sqrt(n()),
        per_0.5 = mean(prop), 
        per_0.025 = per_0.5 - cv(0.025)*std.error,
        per_0.975 = per_0.5 + cv(0.025)*std.error,
        per_0.05 = per_0.5 - cv(0.05)*std.error, 
        per_0.95 = per_0.5 + cv(0.05)*std.error,
        per_0.1 =  per_0.5 - cv(0.1)*std.error,
        per_0.9 =  per_0.5 + cv(0.1)*std.error,
        per_0.25 =  per_0.5 - cv(0.5)*std.error,
        per_0.75 =  per_0.5 + cv(0.5)*std.error
    ) %>%
    mutate(
      knowledge_type = factor(knowledge_type, levels = c("yes", "no", "doesn't know")), 
      knowledge_type = fct_relabel(knowledge_type, str_to_title) %>% fct_rev
    ) %>%
    mutate(
      assigned.treatment = factor(assigned.treatment, 
                                  levels = c("bracelet",
                                             "calendar", 
                                             "ink",
                                             "control")) %>%
                          fct_relabel(str_to_title) %>%
                          fct_rev
    ) %>%
    mutate(
      assigned_dist_group = "Combined"
    )
    

comp_belief_data = bind_rows(
  combined_disagg_belief,
  close_far_disagg_belief
)
```


```{r}
wide_disagg_belief_input_df = comp_belief_data %>%
  select(
    treatment = assigned.treatment, 
    distance = assigned_dist_group, 
    knowledge_type,
    mean_est, 
    per_0.025, 
    per_0.975, 
    ord = belief_type
  )  %>%
  mutate(across(where(is.numeric), round, 3)) %>%
  mutate(
    estim_value = linebreak(
      paste0(mean_est, "\n", "(", per_0.025, ", ", per_0.975, ")"), 
      align = "c"
      )
  ) %>%
  select( 
    treatment,
    distance, 
    knowledge_type, 
    ord, 
    estim_value
  ) %>%
  mutate(ord = factor(ord, levels = c("1ord", "2ord"))) %>%
  pivot_wider(
    names_from = c(ord, distance), 
    values_from = estim_value
  ) %>%
  select(
    treatment, knowledge_type, 
    contains("1ord"), 
    contains("2ord")
  ) %>%
  mutate(
    treatment = fct_rev(treatment)
  ) %>%
  select(
    treatment, knowledge_type, `1ord_Combined`, `1ord_close`, `1ord_far`, 
    `2ord_Combined`, `2ord_close`, `2ord_far`
  )

all_wide_disagg_belief_tbl = wide_disagg_belief_input_df %>%
  arrange(treatment) %>%
  ungroup() %>%
  select(-treatment) %>%
  kbl(
    col.names = c(
      "Knowledge",
      paste0("(", 1:6, ")")
    ), 
    format = "latex", 
    booktabs = TRUE, 
    escape = FALSE, 
    align = "lcccccc", 
    linesep = "",
    caption = "Beliefs Results"
  ) %>%
  kable_styling(
    # latex_options = c("scale_down")
  ) %>%
  add_header_above(
    c(" ", 
      "Combined", 
      "Close", 
      "Far", 
      "Combined",
      "Close", 
      "Far"
      ), 
    line = FALSE
  )  %>%
  add_header_above(
    c(
      " " = 1,
      "First-Order Beliefs" = 3, 
      "Second-Order Beliefs" = 3
      )
  ) %>%
  group_rows(
    index = c(
      "Bracelet" = 3,
      "Calendar" = 3,
      "Ink" = 3,
      "Control" = 3
    ), 
    hline_after = TRUE,
    hline_before = TRUE
  ) %>%
  footnote(
    escape = FALSE,
    threeparttable = TRUE
  )

all_wide_disagg_belief_tbl %>%
  custom_save_latex_table(
    "all-disagg-beliefs-table"
  )

```



```{r}

wide_disagg_belief_sob_tbl = wide_disagg_belief_input_df %>%
  select(-contains("1")) %>%
  arrange(treatment) %>%
  ungroup() %>%
  select(-treatment) %>%
  kbl(
    col.names = c(
      "Knowledge",
      paste0("(", 1:3, ")")
    ), 
    format = "latex", 
    booktabs = TRUE, 
    escape = FALSE, 
    align = "lcccccc", 
    linesep = "",
    caption = "Beliefs Results"
  ) %>%
  kable_styling(
    # latex_options = c("scale_down")
  ) %>%
  add_header_above(
    c(" ", 
      "Combined", 
      "Close", 
      "Far"
      ), 
    line = FALSE
  )  %>%
  add_header_above(
    c(
      " " = 1,
      "Second-Order Beliefs" = 3
      )
  ) %>%
  group_rows(
    index = c(
      "Bracelet" = 3,
      "Calendar" = 3,
      "Ink" = 3,
      "Control" = 3
    ), 
    hline_after = TRUE,
    hline_before = TRUE
  ) %>%
  footnote(
    escape = FALSE,
    threeparttable = TRUE,
  )


wide_disagg_belief_sob_tbl %>%
  custom_save_latex_table(
    "sob-disagg-beliefs-table"
  )

```

```{r}

wide_disagg_belief_tbl = wide_disagg_belief_input_df %>%
  select(-contains("2")) %>%
  arrange(treatment) %>%
  ungroup() %>%
  select(-treatment) %>%
  kbl(
    col.names = c(
      # "Estimand", 
      # "Treatment", 
      "Knowledge",
      paste0("(", 1:3, ")")
    ), 
    format = "latex", 
    booktabs = TRUE, 
    escape = FALSE, 
    align = "lcccccc", 
    linesep = "",
    caption = "Beliefs Results"
  ) %>%
  kable_styling(
    # latex_options = c("scale_down")
  ) %>%
  add_header_above(
    c(" ", 
      "Combined", 
      "Close", 
      "Far"
      ), 
    line = FALSE
  )  %>%
  add_header_above(
    c(
      " " = 1,
      "First-Order Beliefs" = 3
      )
  ) %>%
  group_rows(
    index = c(
      "Bracelet" = 3,
      "Calendar" = 3,
      "Ink" = 3,
      "Control" = 3
    ), 
    hline_after = TRUE,
    hline_before = TRUE
  ) %>%
  footnote(
    escape = FALSE,
    threeparttable = TRUE,
  )

wide_disagg_belief_tbl %>%
  custom_save_latex_table(
    "fob-disagg-beliefs-table"
  )
```



#### WTP Table ####


```{r}
#| eval=TRUE
1+1

wtp_input_df = tidy_param_df %>%
  filter(
    param == "wtp_params"
  ) %>%
  filter(fit_type == "fit") %>%
  unnest(tidy_draws) %>%
  filter(.width ==  params$width) %>%
  left_join(tibble(pref_value_diff_idx = 1:21, val_diff = -seq(-100, 100, 10)), by = "pref_value_diff_idx")   %>%
  filter(val_diff %in% c(-50, 0, 50))  %>%
  mutate(
    across(where(is.numeric), round, 3),
    estim_std = linebreak(
      paste0(
        value, "\n",
        "(", conf.low, ", ", conf.high, ")"
      ), align = "c"
    )
  ) %>%
  select(variable, val_diff, estim_std) %>%
  filter(variable == "prob_prefer_calendar" | val_diff == 0) %>%
  arrange(variable) %>%
  mutate(val_diff = if_else(variable == "hyper_wtp_mu", NA_real_, val_diff)) %>%
  mutate(name = str_glue("Pr(Prefer calendar), offered {val_diff}KSh")) %>%
  mutate(name = if_else(variable == "hyper_wtp_mu", str_glue("Valuation difference (KSh), mean"), name)) %>%
  select(name, estim_std) 
  
wtp_summ_tbl = wtp_input_df %>%
  kbl(
    col.names = c("Parameter", "Posterior estimates"), 
    booktabs = TRUE, 
    escape = FALSE,
    format = "latex",
    align = "lc"
  ) %>%
  pack_rows(
    index = c(
      "Panel A: Model parameters" = 1, 
      "Panel B: Estimated preferences" = 3
    ), 
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space, 
    hline_after = TRUE, 
    hline_before = TRUE,
    bold = TRUE
  )  %>%
  footnote(
    escape = FALSE,
    threeparttable = TRUE,
  )



wtp_summ_tbl %>%
  custom_save_latex_table(
    "wtp-summ-table"
  )
  
  

```

```{r}
#| optim-table-main,
#| eval=TRUE
x = 1+1
all_optim_df = read_csv(
  file.path(
    params$optim_input_path,
    "posterior-clean-summ-optim.csv"
  )
)  %>%
  mutate(fix_type = replace_na(fix_type, "no-fix"))



optim_group_vars = c(
        "private_benefit_z",
        "visibility_z", 
        "static_vstar",
        "allocation_type",
        "distance_constraint",
        "fix_type",
        "fix_distance",
        "rep_type",
        "model",
        "cutoff_type"
)

summ_optim_df = all_optim_df %>%
        group_by(
          across(optim_group_vars)
        ) %>%
        mutate(mean_dist = mean_dist/1000) %>%
        filter(
            model %in% c(models_we_want, "STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP")
        ) %>%
        filter(
            cutoff_type  == "cutoff"
        ) %>%
        summarise(
            across(
                .cols = c(mean_dist, mean_demand),
                list(
                    estimate = ~mean(.x, na.rm = TRUE) %>% round(3),
                    CI = ~paste0("(", round(quantile(.x, 0.025, na.rm = TRUE), 3), ", ", round(quantile(.x, 0.975, na.rm = TRUE), 3), ")")
                )
            ),
            across(
                .cols = c(n_pot),
                list(
                    estimate = ~mean(.x, na.rm = TRUE) %>% round(0),
                    CI = ~paste0("(", round(quantile(.x, 0.025, na.rm = TRUE), 0), ", ", round(quantile(.x, 0.975, na.rm = TRUE), 0), ")")
                )
            )
        )   %>%
        ungroup() %>%
        select(-model, -cutoff_type) %>%
        arrange(
            private_benefit_z,
            visibility_z,
            rep_type
        ) %>%
    rename(
        B_z = private_benefit_z, 
        mu_z = visibility_z
    )



wide_summ_df_rep = summ_optim_df %>%
  filter(rep_type == "rep") %>%
  gather(variable, value, -any_of(optim_group_vars), -B_z, -mu_z)   %>%
  mutate(CI = if_else(str_detect(variable, "CI"), "ci", "estim")) %>%
  mutate(variable = str_remove(variable, "_CI")) %>%
  mutate(variable = str_remove(variable, "_estimate"))  %>%
  pivot_wider(
    id_cols = c(B_z, mu_z, variable, any_of(optim_group_vars)), 
    names_from = CI, 
    values_from = value
  )   %>%
  mutate(estim = if_else(
    variable %in% c("n_pot"), as.numeric(estim), 
    as.numeric(estim) %>% round(2)
  ))  %>%
  mutate(
    estim_value = 
    linebreak(
      paste0(
        estim, "\n", 
        ci
      ), 
      align = "c"
    )
  ) %>%
  select(
    -estim, -ci
  )  %>%
  spread(variable, estim_value)


wide_summ_df_sup_rep = summ_optim_df %>%
  filter(rep_type == "suppress_rep")  %>%
  gather(variable, value, -any_of(optim_group_vars), -B_z, -mu_z)   %>%
  mutate(CI = if_else(str_detect(variable, "CI"), "ci", "estim")) %>%
  mutate(variable = str_remove(variable, "_CI")) %>%
  mutate(variable = str_remove(variable, "_estimate")) %>%
  pivot_wider(
    id_cols = c(B_z, mu_z, variable, rep_type, static_vstar, allocation_type, distance_constraint), 
    names_from = CI, 
    values_from = value
  )    %>%
  # mutate(estim = if_else(
  #   variable %in% c("n_pot"), as.numeric(estim) %>% round(1), 
  #   as.numeric(estim) %>% round(2)
  # ))  %>%
  mutate(
    estim_value = 
    linebreak(
      paste0(
        estim, "\n", 
        ci
      ), 
      align = "c"
    )
  ) %>%
  select(
    -estim, -ci
  )  %>%
  spread(variable, estim_value)



optim_summ_input_df = bind_rows(
  wide_summ_df_rep %>% 
    mutate(rep_type = "rep") %>%
    filter(B_z == "control"),
  wide_summ_df_sup_rep %>% mutate(rep_type = "suppress_rep") %>% filter(B_z == mu_z)
) %>%
filter(fix_type == "no-fix" | is.na(fix_type)) %>%
  mutate(
    mu_z = if_else(rep_type == "suppress_rep", "No visibility", mu_z), 
    mu_z = if_else(static_vstar == TRUE & mu_z == "bracelet", "Signal value fixed at 0.5km", mu_z), 
  ) %>%
  mutate(mu_z = factor(
    mu_z, 
    c("bracelet", 
      "calendar", 
      "ink", 
      "control", 
      "No visibility", 
      "Signal value fixed at 0.5km"
      )))  %>%
  mutate(B_z = factor(B_z, c("bracelet", "calendar", "ink", "control")))  %>%
  mutate(B_z = fct_relabel(B_z, str_to_title)) %>%
  mutate(mu_z = fct_relabel(mu_z, str_to_title))  %>%
  mutate(
    mu_z = recode_factor(mu_z, "Signal Value Fixed At 0.5km" = "Signal value fixed at bracelet 0.5km")
  ) %>%
  mutate(
    mu_z = fct_relevel(mu_z, 
    c("Control", "Ink", "Calendar", "Signal value fixed at bracelet 0.5km", "Bracelet",  "No Visibility"))
  )  %>%
  mutate(
    mean_dist = if_else(
      allocation_type == "experimental", 
      str_remove(mean_dist, "\\\\\\(([^)]+)\\)") %>%
      str_replace(.,   '\\\\\\}', "}"), 
      mean_dist
    ), 
    n_pot = if_else(
      allocation_type == "experimental", 
      str_remove(n_pot, "\\\\\\(([^)]+)\\)") %>%
      str_replace(.,   '\\\\\\}', "}"), 
      n_pot
    ) 
  ) 



optim_summ_tbl = optim_summ_input_df %>%
  filter(distance_constraint == 3500 | allocation_type == "experimental") %>%
  arrange(rep_type, mu_z, B_z) %>%
  select(B_z, mu_z, n_pot, mean_demand, mean_dist) %>%
  knitr::kable(
    col.names = c(
      "Private benefit", 
      "Visibility",
      "Assigned PoTs", 
      "Mean take-up", 
      "Mean distance (km)"
    ),
    align = "llccc",
    booktabs = TRUE,
    # format = "latex",
    linesep = "",
    escape = FALSE
    ) %>%
  kableExtra::kable_styling(
    # latex_options =  c("scale_down")
  ) %>%
  pack_rows(
    index = c(
      "Panel A: Random allocation" = 1, 
      "Panel B: Policymaker allocation" = 4
    ), 
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space, 
    hline_after = TRUE, 
    hline_before = TRUE,
    bold = TRUE
  ) 


optim_summ_tbl %>%
  custom_save_latex_table("optim-summ-table")


```



```{r}
#| fixing-optim-table

  fix_optim_tbl = wide_summ_df_rep %>% 
    mutate(rep_type = "rep") %>%
    filter(B_z == "bracelet") %>%
    filter(mu_z == "bracelet")  %>%
    select(fix_type, fix_distance, n_pot, mean_demand, mean_dist) %>%
    mutate(fix_type = factor(fix_type, levels = c("no-fix", "fix-mu", "fix-delta"))) %>%
    arrange(fix_type) %>%
    select(-fix_type) %>%
  knitr::kable(
    col.names = c(
      "Fix distance",
      "Assigned PoTs", 
      "Mean take-up", 
      "Mean distance (km)"
    ),
    align = "cccc",
    booktabs = TRUE,
    # format = "latex",
    escape = FALSE
    ) %>%
  kableExtra::kable_styling(
    # latex_options =  c("scale_down")
  ) %>%
  pack_rows(
    index = c(
      "Panel A: No Fixing" = 1, 
      "Panel B: Fix $\\mu$" = 3, 
      "Panel C: Fix $\\Delta(w^*)$" = 3
    ), 
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space, 
    hline_after = TRUE, 
    hline_before = TRUE,
    bold = TRUE
  ) 



fix_optim_tbl %>%
  custom_save_latex_table("fix-optim-summ-table")

```

```{r, eval=TRUE}
#|optim-summ-table-robust,
#| dependson = c("optim-summ-table"), eval=FALSE
optim_summ_robust_tbl = optim_summ_input_df %>%
  arrange(allocation_type, distance_constraint, rep_type, mu_z, B_z) %>%
  select(B_z, mu_z, distance_constraint, n_pot, mean_demand, mean_dist) %>%
  mutate(distance_constraint = distance_constraint/1000) %>%
  knitr::kable(
    col.names = c(
      "Private benefit", 
      "Visibility",
      "\\makecell{Maximum \\\\ distance constraint (km)}",
      "Assigned PoTs", 
      "Mean take-up", 
      "Mean distance (km)"
    ),
    align = "llcccc",
    booktabs = TRUE,
    escape = FALSE,
    format = "latex"
    ) %>%
  kableExtra::kable_styling(
    # latex_options =  c("scale_down")
  ) %>%
  pack_rows(
    index = c(
      "Panel A: Random allocation" = 1, 
      "Panel B: Policymaker allocation, 2.5km" = 4,
      "Panel C: Policymaker allocation, 3.5km" = 4,
      "Panel D: Policymaker allocation, 4.5km" = 4,
      "Panel E: Policymaker allocation, 5.5km" = 4,
      "Panel F: Policymaker allocation, 10km" = 4
    ), 
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space, 
    hline_after = TRUE, 
    hline_before = TRUE,
    bold = TRUE
  ) 



optim_summ_robust_tbl %>%
  custom_save_latex_table("optim-summ-robust-table")

```

# Mechanism Stuff 

```{r}
#| mechanism-full-regression-table, results="asis"
y = 1+3



writeLines(
  c(
    "\\begin{table}[htbp]",
    readLines("presentations/tables/rf-mechanism-full-regression-table.tex"), 
    "\\end{table}"
  )
)

writeLines(
  c(
    "\\begin{table}[htbp]",
    readLines("presentations/tables/rf-mechanism-control-regression-table.tex"), 
    "\\end{table}"
    )
)

writeLines(
  c(
    "\\begin{table}",
    readLines("presentations/tables/rf-mechanism-het-knowledge-regression-table.tex"),
    "\\end{table}"
  )
)


    # file = "temp-data/rf-mechanism-control-regression-table.tex"
    # file = "temp-data/rf-mechanism-het-knowledge-regression-table.tex"
    # file = "temp-data/rf-mechanism-incentive-regression-table.tex"

```

\newpage
\blandscape

```{r}
#| mechanism-incentive-regression-table, results="asis"
x = 1+3
writeLines(
  c(
    "\\begin{table}",
    readLines("presentations/tables/rf-mechanism-incentive-regression-table.tex"), 
    "\\end{table}"
  )
)

```

\elandscape

```{r}
#| sob-gpt-reason-table

sob_gpt_reason_df = read_csv(
        "temp-data/second-order-gpt-reason-distribution.csv"
)


gpt_N_df = sob_gpt_reason_df %>%
  group_by(var) %>%
  summarise(N = unique(N)) %>%
  mutate(
    sample_var = c("yes", "no")
  ) %>%
  mutate(sample_var = factor(sample_var, levels = c("yes", "no"))) %>%
  spread(
    var, N
  ) %>%
  mutate(
    term = "N"
  ) %>%
  select(
    sample_var,
    term,
    campaign, 
    communication,
    relationship, 
    signal, 
    type, 
    circumstances, 
    other
  ) 


2+3
digits = 3

gpt_table = sob_gpt_reason_df %>%
  mutate(
    estimate = round(estimate, digits),
    std.error = round(std.error, digits),
    stars = case_when(
      term != "(Intercept)" & p.value < 0.01 ~ "***",
      term != "(Intercept)" & p.value < 0.05 ~ "**", 
      term != "(Intercept)" & p.value < 0.1 ~ "*" , 
      TRUE ~ ""
    )
  ) %>%
  mutate(
    estim_std = linebreak(paste0(estimate, stars, "\n", str_glue("({std.error})")), align = "c") 
  )  %>%
  mutate(
    sample_var = str_remove(sample, "sample.var: second.order; sample: ") 
  ) %>%
  mutate(sample_var = factor(sample_var, levels = c("yes", "no"))) %>%
  mutate(term = str_remove(term, "assigned.treatment")) %>%
  mutate(term = if_else(term == "(Intercept)", "Control mean", term)) %>%
  mutate(term = factor(term, levels = c('Control mean', treat_levels_c))) %>%
  select(sample_var, term, estim_std, var) %>%
  spread(var, estim_std)  %>%
  select(
    sample_var,
    term, 
    campaign, 
    communication,
    relationship, 
    signal, 
    type, 
    circumstances, 
    other
  ) %>%
  bind_rows(gpt_N_df %>% mutate(across(where(is.numeric), as.character))) %>%
  mutate(term = factor(term, levels = c('N', 'Control mean', treat_levels_c))) %>%
  mutate(term = fct_relabel(term, str_to_title) %>% fct_rev) %>%
  arrange(
    sample_var, term
  ) %>%
  select(-sample_var)  %>%
  knitr::kable(
      format = "latex",
      col.names = c(
        "", 
        "General Visibility", 
        "Communication", 
        "Social Proximity", 
        "Incentive", 
        "Type", "Circumstances", "Other"),
      escape = FALSE, 
      booktabs = TRUE,
      align = "lccccccc", 
      caption = "Second Order Beliefs: Reasons (GPT)"
  ) %>%
  kable_styling(
    latex_options = c("scale_down")
  )  %>%
  pack_rows(
    index = c(
      "Panel A: Why do they think that you came for deworming?" = 5,
      "Panel B: Why don't they think that you came for deworming?" = 5
    ), 
    hline_after = TRUE, 
    hline_before = TRUE, 
    bold = TRUE
  )  %>%
  row_spec(c(3, 8), hline_after = TRUE)



gpt_table %>%
  custom_save_latex_table("why-deworm-gpt-reason-table")


```



```{r}

gpt_know_notknow_df = read_csv(
        "temp-data/second-order-know-notknow-gpt-reason-distribution.csv"
)

gpt_pval_dist_df = read_csv(
        "temp-data/second-order-know-notknow-gpt-reason-dist-pval.csv"
)


gpt_know_N_df = gpt_know_notknow_df %>%
  group_by(var) %>%
  summarise(N = unique(N)) %>%
  mutate(
    sample_var = c("Know", "Don't Know")
  ) %>%
  mutate(sample_var = factor(sample_var, levels = c("Know", "Don't Know"))) %>%
  spread(
    var, N
  ) %>%
  mutate(
    term = "N"
  ) %>%
  select(
    sample_var,
    term,
    campaign, 
    communication,
    relationship, 
    signal, 
    type, 
    circumstances, 
    other
  ) 


2+3
digits = 3

gpt_know_table = gpt_know_notknow_df %>%
  mutate(
    estimate = round(estimate, digits),
    std.error = round(std.error, digits),
    stars = case_when(
      term != "(Intercept)" & p.value < 0.01 ~ "***",
      term != "(Intercept)" & p.value < 0.05 ~ "**", 
      term != "(Intercept)" & p.value < 0.1 ~ "*" , 
      TRUE ~ ""
    )
  ) %>%
  mutate(
    estim_std = linebreak(paste0(estimate, stars, "\n", str_glue("({std.error})")), align = "c") 
  )  %>%
  mutate(
    sample_var = str_remove(sample, "sample.var: knowledge; sample: ") 
  )  %>%
  mutate(sample_var = if_else(
    str_detect(sample_var, "TRUE"), 
    "Know",
    "Don't Know"
  )) %>%
  mutate(
    sample_var = factor(
      sample_var, 
      levels = c("Know", "Don't Know"))) %>%
  mutate(term = str_remove(term, "assigned.treatment")) %>%
  mutate(term = if_else(term == "(Intercept)", "Control mean", term)) %>%
  mutate(term = factor(term, levels = c('Control mean', treat_levels_c))) %>%
  select(sample_var, term, estim_std, var) %>%
  spread(var, estim_std)  %>%
  select(
    sample_var,
    term, 
    campaign, 
    communication,
    relationship, 
    signal, 
    type, 
    circumstances, 
    other
  ) %>%
  bind_rows(gpt_know_N_df %>% mutate(across(where(is.numeric), as.character))) %>%
  mutate(term = factor(term, levels = c('N', 'Control mean', treat_levels_c))) %>%
  mutate(term = fct_relabel(term, str_to_title) %>% fct_rev) %>%
  arrange(
    sample_var, term
  ) %>%
  select(-sample_var)  %>%
  knitr::kable(
      format = "latex",
      col.names = c(
        "", 
        "General Visibility", 
        "Communication", 
        "Social Proximity", 
        "Incentive", 
        "Type", "Circumstances", "Other"),
      escape = FALSE, 
      booktabs = TRUE,
      align = "lccccccc", 
      caption = "Second Order Beliefs: Reasons (GPT)"
  ) %>%
  kable_styling(
    latex_options = c("scale_down")
  )  %>%
  pack_rows(
    index = c(
      "Panel A: Why do they know you came for deworming?" = 5,
      "Panel B: Why don't they know that you came for deworming?" = 5
    ), 
    hline_after = TRUE, 
    hline_before = TRUE, 
    bold = TRUE
  )  %>%
  row_spec(c(3, 8), hline_after = TRUE)

gpt_know_table %>%
  custom_save_latex_table("know-table-why-deworm-gpt-reason-table")



```

```{r}
#| sob-reason-table

sob_reason_df = read_csv(
        "temp-data/second-order-reason-distribution.csv"
)


N_df = sob_reason_df %>%
  group_by(var) %>%
  summarise(N = unique(N)) %>%
  mutate(
    sample_var = c("yes", "no")
  ) %>%
  mutate(sample_var = factor(sample_var, levels = c("yes", "no"))) %>%
  spread(
    var, N
  ) %>%
  mutate(
    term = "N"
  ) %>%
  select(
    sample_var,
    term,
    campaign, 
    communication,
    relationship, 
    signal, 
    type, 
    circumstances, 
    other
  ) 


2+3
digits = 3

sob_reason_df %>%
  mutate(
    estimate = round(estimate, digits),
    std.error = round(std.error, digits),
    stars = case_when(
      p.value < 0.01 ~ "***",
      p.value < 0.05 ~ "**", 
      p.value < 0.1 ~ "*" , 
      TRUE ~ ""
    )
  ) %>%
  mutate(
    estim_std = linebreak(paste0(estimate, stars, "\n", str_glue("({std.error})")), align = "c") 
  )  %>%
  mutate(
    sample_var = str_remove(sample, "sample.var: second.order; sample: ") 
  ) %>%
  mutate(sample_var = factor(sample_var, levels = c("yes", "no"))) %>%
  mutate(term = str_remove(term, "assigned.treatment")) %>%
  mutate(term = if_else(term == "(Intercept)", "Control mean", term)) %>%
  mutate(term = factor(term, levels = c('Control mean', treat_levels_c))) %>%
  select(sample_var, term, estim_std, var) %>%
  spread(var, estim_std)  %>%
  select(
    sample_var,
    term, 
    campaign, 
    communication,
    relationship, 
    signal, 
    type, 
    circumstances, 
    other
  ) %>%
  bind_rows(gpt_N_df %>% mutate(across(where(is.numeric), as.character))) %>%
  mutate(term = factor(term, levels = c('N', 'Control mean', treat_levels_c))) %>%
  mutate(term = fct_relabel(term, str_to_title) %>% fct_rev) %>%
  arrange(
    sample_var, term
  ) %>%
  select(-sample_var)  %>%
  knitr::kable(
      format = "latex",
      col.names = c(
        "", 
        "General Visibility", 
        "Communication", 
        "Social Proximity", 
        "Incentive", 
        "Type", "Circumstances", "Other"),
      escape = FALSE, 
      booktabs = TRUE,
      align = "lccccccc", 
      caption = "Second Order Beliefs: Reasons"
  ) %>%
  kable_styling(
    latex_options = c("scale_down")
  )  %>%
  pack_rows(
    index = c(
      "Panel A: Why do they think that you came for deworming?" = 5,
      "Panel B: Why don't they think that you came for deworming?" = 5
    ), 
    hline_after = TRUE, 
    hline_before = TRUE, 
    bold = TRUE
  )  %>%
  row_spec(c(3, 8), hline_after = TRUE)



```


```{r}
#| endline-data,
#| eval=TRUE

# Some initial endline knowledge checks

library(haven)
endline_data = read_dta("data/endline_data.dta") %>%
  mutate(
    assigned_treatment = as_factor(assigned_treatment)
  )

n_function = function(data, treat_no, ...) {
  data %>%
  group_by(
    assigned_treatment, ...
  ) %>% 
  filter(assigned_treatment == treat_no) %>%
  summarise(
    n = n()
  ) %>%
  na.omit() %>%
  mutate(
    pct = 100*n/sum(n)
  ) 
}


endline_data = endline_data %>%
  # harmonising
  mutate(
    have_ink = ink_visible
  )

mean_deworm_string_f = function(string) {
  str_detect(str_to_lower(string), "drug|medicine|tablet|deworm|Deworm|worm|treat")
}

endline_data = endline_data %>%
  mutate(
    meandeworm_bracelet = mean_deworm_string_f(bracelet_meaning),
    meandeworm_ink = mean_deworm_string_f(ink_meaning),
    meandeworm_cal = mean_deworm_string_f(cal_meaning)
  )


got_vars = c(
  "got_bracelet", 
  "got_ink", 
  "got_cal"
)
have_vars = c(
  "have_bracelet", 
  "have_cal", 
  "have_ink"
)
seen_vars = c(
  "seen_bracelet", 
  "seen_ink", 
  "seen_cal"
)
mean_vars = c(
  "meandeworm_bracelet", 
  "meandeworm_ink", 
  "meandeworm_cal"
)

long_incentive_check_df = endline_data %>%
  select(all_of(c(got_vars, have_vars, seen_vars, mean_vars)), assigned_treatment)  %>%
  pivot_longer(
    cols = all_of(c(got_vars, have_vars, seen_vars, mean_vars))
  ) %>%
  mutate(
    variable_type = str_extract(name, "(\\w+)(?=_)"),
    name = str_extract(name, "(?<=_)\\w+"), 
    name = if_else(name == "cal", "calendar", name)
    )   %>%
  filter(name == assigned_treatment)  %>%
  mutate(
    treat_type = paste0(assigned_treatment, "_", variable_type)
  ) %>%
  select(-name)

tidy_incentive_check_df = long_incentive_check_df %>%
  feols(
    value ~ i(assigned_treatment, "ink"),
    split = ~variable_type
  ) %>%
  map_dfr(
    ~tidy(.x) %>%
    mutate(n = nobs(.x)), 
    .id = "lhs"
  ) %>%
  mutate(
    treatment = str_extract(
      term, "(?<=assigned_treatment::)\\w+"
    ),
    treatment = replace_na(treatment, "ink")
  ) %>%
  mutate(
    variable_type = str_extract(
      lhs, 
      "(?<=sample: )\\w+$"
    )
    ) %>%
  select(
    -lhs,
    -term
  )

# tidy_incentive_check_df = long_incentive_check_df %>%
#   feols(
#     value ~ 1,
#     split = ~ treat_type  
#   )  %>%
#   map_dfr(
#     ~tidy(.x) %>% 
#     mutate(n = nobs(.x)), 
#     .id = "lhs"
#   )  %>%
#   mutate(
#     treatment = str_extract(
#       lhs, 
#       "(?<=sample: )\\w+(?=_)"
#     ), 
#     variable_type = str_extract(
#       lhs, 
#       "(?<=sample: \\w{1,10}_)\\w+$"
#     )
#   ) %>%
#   select(-lhs) %>%
#   select(-term)

wide_incentive_check_input_df = tidy_incentive_check_df %>%
  mutate(across(c(estimate, std.error), round, 3)) %>%
  mutate(
    stars = case_when(
      treatment != "ink" & p.value < 0.01 ~ "***",
      treatment != "ink" & p.value < 0.05 ~ "**", 
      treatment != "ink" & p.value < 0.1 ~ "*" , 
      TRUE ~ ""
    ),
    estim_std = linebreak(paste0(estimate, stars, "\n", str_glue("({std.error})")), align = "c") 
  ) %>%
  mutate(treatment = str_replace(treatment, "ink", "ink (levels)")) %>%
  select( 
    treatment, 
    variable_type, 
    estim_std
  ) %>%
  mutate(treatment = str_to_title(treatment)) %>%
  spread(
    variable_type, 
    estim_std
  ) %>%
  select(
    treatment,
    got, # "Did you receive X when you went for deworming?"
    have, # "Do you still have X?"
    seen, # "have you seen people wearing these "X"?"/ "have you seen people these calendars before"
    meandeworm # "What does it mean if a person has a bracelet?" -> coded into deworm mentions
  )


incentive_check_tbl = wide_incentive_check_input_df %>%
  knitr::kable(
    format = "latex",
      col.names = c(
        "", 
        "Received incentive when treated", 
        "Have incentive currently", 
        "Seen incentive", 
        "Link incentive to deworming"),
      escape = FALSE, 
      booktabs = TRUE,
      align = "lcccc", 
      caption = "Incentive Check: Endline"
  ) 

incentive_check_tbl

incentive_check_tbl %>%
  custom_save_latex_table("incentive-check-tbl")


```



```{r}
#| endline-results-indiv, results="asis"

endline_data = endline_data %>%
  mutate(
    assigned_treatment = as_factor(assigned_treatment), 
    dist_pot_group = as_factor(dist_pot_group)
  )



dworm_endline_fit = endline_data %>%
  mutate(dworm_rate = dworm_rate/10) %>%
  feols(
    dworm_rate ~ 0 + assigned_treatment:dist_pot_group + dist_to_pot | county,
    cluster = ~cluster_id
  ) 



endline_close_far_preds = predictions(
  dworm_endline_fit,
  newdata = datagrid(
    assigned_treatment = endline_data$assigned_treatment %>% unique(),
    dist_to_pot = endline_data %>%
      group_by(dist_pot_group) %>%
      summarise(dist = mean(dist_to_pot)) %>%
      pull(dist),
    dist_pot_group = c("close", "far")
  )
  )

endline_close_far_hyps = c(
    "ink" = "b1 = b4",
    "calendar" = "b5 = b8",
    "bracelet" = "b9 = b12",
    "control" = "b13 = b16"
  )

endline_close_far_df = map_dfr(
  endline_close_far_hyps,
  ~hypotheses(
    endline_close_far_preds,
    .x
  ) %>%
  tidy(),
  .id = "treatment"
)


d_bar = endline_data %>%
  group_by(dist_pot_group) %>%
  summarise(dist = mean(dist_to_pot)) %>%
  pull(dist) %>%
  sort()

control_mean_close_far_pred = map_dfr(
      c("close", "far"),
    ~avg_predictions(
      dworm_endline_fit, 
      newdata = datagrid(
        assigned_treatment = "control",
        dist_pot_group = .x, 
        dist_to_pot = d_bar
        ),
        by = "dist_to_pot"
    ) %>%
    tidy() %>%
    mutate(term = .x) ) %>%
    filter(
      (term == "close" & dist_to_pot == d_bar[1]) |
      (term == "far" & dist_to_pot == d_bar[2])
    )


dworm_endline_comp_df = map_dfr(
  c("close", "far"), 
  ~avg_comparisons(
    model = dworm_endline_fit, 
    variables = list("assigned_treatment" = "all"), 
    newdata = datagrid(
      dist_pot_group = .x
    )
  ) %>% tidy() %>%
  mutate(term = .x)
) %>%
bind_rows(
  avg_comparisons(
    model = dworm_endline_fit, 
    variables = list("assigned_treatment" = "all")
  ) %>%
  tidy() %>%
  mutate(term = "Combined")
) %>%
  mutate(
    treatment = str_extract(contrast, "^\\w+")
  ) %>%
  bind_rows(
    tidy(dworm_endline_fit) %>%
    filter(str_detect(term, "control")) %>% 
    mutate(treatment = "control",
    term = if_else(
      str_detect(term, "close"), 
      "close", 
      "far"
    ))
  ) %>%
  filter(treatment != "control") %>%
  bind_rows(
    avg_predictions(
      dworm_endline_fit, 
      variables = "assigned_treatment"
    ) %>%
    tidy() %>%
    mutate(term = "Combined")  %>%
    rename(treatment = assigned_treatment) %>%
    filter(treatment == "control")
  )  %>%
  bind_rows(
    control_mean_close_far_pred %>%
      mutate(treatment = "control")
  ) 





subset_dworm_endline_comp_df = dworm_endline_comp_df %>%
  mutate(
    lhs = str_extract(contrast, "^\\w+"),
    rhs = str_extract(contrast, "\\w+$")
  ) %>%
  filter(
    is.na(contrast) | rhs == "control" | (str_detect(contrast, "brac") & str_detect(contrast, "cal") )
  ) %>%
  filter(lhs != "control" | is.na(contrast)) %>%
  mutate(
    bra_cal = if_else(
      rhs != "control" & str_detect(lhs, "bra|cal"),
      TRUE,
      FALSE
    ),
    bra_cal = replace_na(bra_cal, FALSE)
  ) %>%
  filter(
    bra_cal == FALSE | (bra_cal == TRUE & treatment == "bracelet")
  ) 



dworm_endline_comp_tbl = subset_dworm_endline_comp_df  %>%
  filter(bra_cal == FALSE) %>%
  mutate(
    across(c(estimate, std.error), round, 3),
    stars = case_when(
      treatment != "control" & p.value < 0.01 ~ "***",
      treatment != "control" & p.value < 0.05 ~ "**", 
      treatment != "control" & p.value < 0.1 ~ "*" , 
      TRUE ~ ""
    )
  ) %>%
  mutate(
    estim_std = linebreak(paste0(estimate, stars, "\n", str_glue("({std.error})")), align = "c") 
  ) %>%
  bind_rows(
    subset_dworm_endline_comp_df %>%
      filter(bra_cal == TRUE) %>%
      mutate(estim_std = round(p.value, 4) %>% as.character(), treatment = "H0: Bracelet = Calendar, $p$-value")
  ) %>%
  select(term, treatment, estim_std) %>%
  mutate(treatment = if_else(!str_detect(treatment, "value"), str_to_title(treatment), treatment)) %>%
  mutate(treatment = if_else(treatment == "Control", "Control mean", treatment)) %>%
  mutate(
    treatment = factor(
      treatment, 
      levels = c("Control mean", 
      "H0: Bracelet = Calendar, $p$-value",
      "Ink",
      "Calendar",
      "Bracelet")) %>% fct_rev()) %>%
  spread(
    term, 
    estim_std
  )  %>%
  select(treatment, Combined, close, far) 



dworm_endline_comp_tbl = left_join(
 dworm_endline_comp_tbl,
  endline_close_far_df %>%
    select(treatment, p.value) %>%
    mutate(
      treatment = case_when(
        treatment == "bracelet" ~ "Bracelet",
        treatment == "calendar" ~ "Calendar",
        treatment == "ink" ~ "Ink",
        treatment == "control" ~ "Control mean"
      )
    )  %>%
    mutate(p.value = round(p.value, 5) %>% as.character)
)
  



dworm_endline_comp_tbl_knitr = dworm_endline_comp_tbl %>%
  knitr::kable(
      # format = "latex",
      col.names = c(
        "", 
        "Combined",
        "Close", 
        "Far",
        "H0: Close = Far, $p$-value"
        ),
      escape = FALSE, 
      booktabs = TRUE,
      align = "lcccc", 
      caption = "Surveyed individuals' predicted deworming rates"
  )  %>%
  row_spec(4, hline_after = TRUE)

dworm_endline_comp_tbl_knitr

dworm_endline_comp_tbl_knitr %>%
  custom_save_latex_table("endline-dworm-indiv-pred-tbl")


```


```{r}
#| balance-reading

balance_tidy_df = read_csv(
  file.path("temp-data", "balance_tidy_df.csv")
) %>%
  filter(
    !str_detect(term, "county::")
  )


comp_balance_tidy_df = read_csv(
  file.path("temp-data", "comp_balance_tidy_df.csv")
)


balance_data = read_rds(
  file.path(
    "temp-data",
    "saved_balance_data.rds"
  )
)

balance_analysis_data = balance_data$analysis_data
baseline_worm_data = balance_data$baseline_worm_data
endline_vars = balance_data$endline_vars
endline_and_baseline_worm_data = balance_data$endline_and_baseline_worm_data
pretreat_data = balance_data$pretreat_data
clean_census_data = balance_data$clean_census_data

```



```{r}
#| joint-tests

# boot_fits = read_rds(
#   file.path("temp-data", 
#             "wild_boot_balance_fits.rds")
# )

boot_fits = read_rds(
  file.path("temp-data", 
            "cluster_balance_fits.rds")
)

joint_signif_fstats = map_dbl(
  boot_fits, "joint_pval"
) %>% round(4)

close_joint_signif_fstats = map_dbl(
  boot_fits, "close_pval"
) %>% round(4)

far_joint_signif_fstats = map_dbl(
  boot_fits, "far_pval"
) %>%
  round(4)

col_order = c(
  "lhs", 
  paste0(treat_levels_c, "_close"),
  "close_joint_p",
  paste0(treat_levels_c, "_far"),
  "far_joint_p",
  "joint_p"
)

diff_names = c(
  "con",
  "ink - con",
  "cal - con",
  "bra - con",
  "bra - cal"
)

col_diff_order = c(
  "lhs", 
  paste0(diff_names, "_close"),
  "close_joint_p",
  paste0(diff_names, "_far"),
  "far_joint_p",
  "joint_p"
)

create_balance_input = function(tidy_df,  
                                col_order, 
                                digits = 3, 
                                comp_df = FALSE, 
                                show_pval = FALSE) {
  if (comp_df) {
    col_order_we_want = col_diff_order
  } else {
    col_order_we_want = col_order
  }
  bal_input_df = tidy_df %>%
      mutate(
      estimate = round(estimate, digits),
      std.error = round(std.error, digits),
      p.value = round(p.value, digits)
      ) 
  if (show_pval == TRUE) {
    bal_input_df = bal_input_df %>%
      mutate(below_val = p.value)
  } else {
    bal_input_df = bal_input_df %>%
      mutate(below_val = std.error)
  }

    if (comp_df == FALSE) {
      bal_input_df = bal_input_df %>%
        mutate(lhs_treat = str_extract(term, "(?<=disttreat: ).*(?=\\,)")) %>%
        mutate(lhs_dist = str_extract(term, "(?<=dist: ).*$")) 
        # TODO RHS treat
    } else {
      bal_input_df = bal_input_df %>%
        mutate(
          lhs_treat = lhs_treatment, 
          lhs_dist = lhs_dist,
          rhs_dist = rhs_dist,
          rhs_treat = rhs_treatment
        ) 
    } 
  bal_input_df = bal_input_df %>%
      mutate(
        estim_std = if_else(
          lhs_treat == "control",
          linebreak(paste0(estimate, "\n", str_glue("({std.error})")), align = "c"),
          linebreak(paste0(estimate, "\n", "{[", below_val, "]}"), align = "c")
        )
      )  

  if (comp_df == TRUE) {
    wide_bal_input_df = bal_input_df %>%
      select(lhs, lhs_treat, rhs_treat, lhs_dist, estim_std) %>%
      unique()  %>%
      mutate(
        treat_diff = paste0(str_sub(lhs_treat, 1, 3), " - ", str_sub(rhs_treat, 1,3)),
        treat_diff = if_else(is.na(rhs_treat),  str_sub(lhs_treat, 1, 3), treat_diff)
        )  %>%
      mutate(
        treat_diff = factor(treat_diff, levels = c(
          "con",
          "ink - con",
          "cal - con",
          "bra - con",
          "bra - cal"
        )),
        lhs_treat = factor(lhs_treat, treat_levels_c) %>% fct_rev(), 
        lhs_dist = factor(lhs_dist, dist_levels) %>% fct_rev()
      ) %>%
      select(lhs, treat_diff, lhs_dist, estim_std) %>%
      pivot_wider(
      names_from = c(treat_diff, lhs_dist),
      values_from = estim_std, 
      )    %>%
      select(
      any_of(col_order_we_want)
      )  
  } else {

    wide_bal_input_df = bal_input_df %>%
      select(lhs, lhs_treat, estim_std, lhs_dist) %>%
      mutate(
        col_name = paste0(lhs_treat, "_", lhs_dist)
      ) %>%
      select(lhs, estim_std, col_name) %>%
      spread(col_name, estim_std) %>%
      select(
        lhs,

        control_close,
        ink_close,
        calendar_close,
        bracelet_close,

        control_far,
        ink_far,
        calendar_far,
        bracelet_far
      )
  }
  return(wide_bal_input_df)
}






stratum_map = analysis.data %>% 
  mutate(stratum = county) %>%
  mutate(stratum_id = as.integer(stratum)) %>% 
  distinct(stratum_id, stratum)

incentive_choice_data <- analysis.data %>%
  filter(!is.na(gift_choice) & gift_choice != "neither",
          assigned.treatment == "control",
          sms.treatment.2 == "sms.control") %>%
  mutate(offer = 0,
          response = "keep")

incentive_choice_data <- wtp.data %>%
  semi_join(analysis.data, "cluster.id") %>% # Make sure we have the same clusters
  filter(!is.na(first_choice)) %>%
  transmute(county, cluster.id,
            gift_choice = first_choice,
            offer = price,
            response = second_choice) %>%
  bind_rows(incentive_choice_data) %>%
  left_join(stratum_map, c("county" = "stratum")) %>%
  mutate(gift_choice = 2 * (gift_choice == "calendar") - 1,
          response = 2 * (response == "switch") - 1) 


N_pretreat = nrow(pretreat_data)
N_census = nrow(clean_census_data)
N_takeup = nrow(analysis_data)
N_baseline_worm = nrow(baseline_worm_data)
N_endline = nrow(balance_data$endline_worm_data)

N_wtp_obs_df = balance_analysis_data %>%
  filter(KEY.individ %in% incentive_choice_data$KEY.individ) %>%
  filter(!is.na(KEY.individ)) %>%
  group_by(
    treat_dist
  ) %>%
  summarise(
    N_indiv = n_distinct(KEY.individ),
    N_pot = n_distinct(cluster.id)
  )  %>%
  mutate(type = "WTP")

N_baseline_worm_obs  = baseline_worm_data  %>%
  group_by(treat_dist) %>%
  summarise(
    N_indiv = n_distinct(KEY), 
    N_pot = n_distinct(cluster.id)
  ) %>%
  mutate(
    type = "baseline"
  )





```


```{r}
#| baseline-learning

# Here we test if there's a difference in learning between baseline and endline 
# across a range of alternative mechanisms.
comp_endline_vars = endline_vars %>%
  str_remove(., "endline_")
# comp_endline_vars = comp_endline_vars[comp_endline_vars != "know_deworming_stops_worms"]
baseline_endline_worm_fit = feols(
      data = endline_and_baseline_worm_data, 
      .[comp_endline_vars] ~ 0 + treat_dist:type + i(county, ref = "Busia"), 
      ~cluster.id
      ) 

endline_p_val_df = read_csv(
  file.path(
    "temp-data", 
    "endline_balance_p_val_df.csv"
  )
)

endline_tidy_df = read_csv(
  file.path(
    "temp-data",
    "endline_balance_tidy_df.csv"
  )
) %>%
  mutate(rhs_treat = "con")

```

```{r}
#| baseline-covariate-naming

lhs_translation_df = tribble(
  ~lhs, ~clean_name, ~sample,
  "lhs: age.census", "Age", "takeup_sample",
  "lhs: all_can_get_worms", "Know everyone can be infected", "baseline_worm",
  "lhs: treated_lgl", "Dewormed in the past", "baseline_worm",
  "lhs: floor_tile_cement", "Floor made of tile/cement", "pretreat",
  "lhs: completed_primary", "Completed primary schooling", "pretreat",
  "lhs: correct_when_treat", "Know bi-yearly treatment recommended", "baseline_worm",
  "lhs: fully_aware_externalities", "Know worms impose externality", "baseline_worm",
  "lhs: partially_aware_externalities", "Partially understands externalities", "baseline_worm",
  "lhs: female", "Female", "takeup_sample",
  "lhs: have_phone_lgl", "Phone owner", "takeup_sample",
  "lhs: know_how_stop_worms", "Know how to prevent worms", "baseline_worm",
  "lhs: cluster.dist.to.pot", "Distance to PoT", "takeup_sample",
  "lhs: n_per_cluster", "Number of individuals per community", "takeup_sample",
  "lhs: years_schooling", "Years schooling", "pretreat",
  "lhs: ethnicity_luhya", "Main ethnicity/Luhya", "pretreat",
  "lhs: religion_christianity", "Christian", "pretreat",
  "lhs: family_treated_lgl", "$\\geq 1$ Family member dewormed", "baseline_worm",
  "lhs: adult_in_family_treated", "Adults in family dewormed", "baseline_worm",
  "lhs: know_worms_infectious", "Know worms spread by infected", "baseline_worm",
  "lhs: know_deworm", "Know about community-based MDA?", "implementation",
  "lhs: treat_begin", "Know when MDA starts?", "implementation",
  "lhs: treat_end", "Know about MDA ends?", "implementation",
  "lhs: days_available", "Know length of MDA?", "implementation",
  "lhs: chv_visit", "Did a CHV visit you?", "implementation",
  "lhs: stigma_dewor", "Would you stigmatise: Not deworming?", "baseline_worm",
  "lhs: stigma_immuniz", "Would you stigmatise: Not immunizing a child?", "baseline_worm",
  "lhs: praise_dewor", "Would you praise: Deworming?", "baseline_worm",
  "lhs: praise_immuniz", "Would you praise: Immunizing a child?", "baseline_worm",

  "lhs: pct_announce", "Was there an announcement about MDA in your community?", "implementation",
  "lhs: pct_knowledge_message", "Did the CHV share knowledge of deworming practices?", "implementation",
  "lhs: pct_avail_message", "Did the CHV share where to get dewormed?", "implementation"
) %>%
  mutate(
    lhs_no_prefix = str_remove(lhs, "lhs: ")
  ) %>%
    mutate(sample = factor(sample, levels = c("takeup_sample", "pretreat", "baseline_worm", "census", "implementation")))


```

```{r}
#| balance-creation, dependson="balance-setup"

comp_wide_indiv_bal_df = create_balance_input(
    comp_balance_tidy_df %>% 
      filter(comp_type == "treatment") %>%
      mutate(estimate = if_else(str_detect(lhs, "pct_") & lhs_treatment == "control", pmin(1, estimate), estimate)),
    col_order = col_order, 
    digits = 3, 
    comp_df = TRUE,
    show_pval = TRUE
)  %>%
  mutate(
    close_joint_p = close_joint_signif_fstats,
    far_joint_p = far_joint_signif_fstats,
    joint_p = joint_signif_fstats
  ) %>%
 select(all_of(col_diff_order)) %>%
  mutate(across(where(is.character), ~if_else(.x == "", "-", .x))) %>%
  mutate(across(where(is.character), replace_na, "-")) %>%
  inner_join(lhs_translation_df %>% select(lhs, clean_name, sample)) %>%
  mutate(lhs = clean_name) %>%
  select(-clean_name) %>%
  arrange(sample) %>%
  select(-sample)


1+1

```

## Balance

```{r, results="asis"}
#| comp-balance-table,
#| dependson=c("balance-setup", "balance-creation")

colnames(comp_wide_indiv_bal_df) = colnames(comp_wide_indiv_bal_df) %>%
  str_replace(., "_close", "") %>%
  str_replace(., "_far", "") %>%
  str_to_title()


bal_table_names = colnames(comp_wide_indiv_bal_df)
bal_table_names[1] = ""
bal_table_names[bal_table_names == "Joint_p"] = "Joint Test"
bal_table_names[bal_table_names == "Far_joint_p"] = "Joint Test"
bal_table_names[bal_table_names == "Close_joint_p"] = "Joint Test"
1+1

n_per_comp_panel_df = lhs_translation_df %>%
  filter(clean_name %in% comp_wide_indiv_bal_df$Lhs) %>%
  count(sample) %>%
  mutate(sample = factor(sample, levels = c("pretreat", "census", "baseline_worm", "takeup_sample"))) %>%
  data.table::data.table(.) 


panel_names = c(
      str_glue("Panel A: Takeup sample, $N={format(N_takeup, big.mark = ',')}$"),
      str_glue("Panel B: Pretreatment, $N={format(N_pretreat, big.mark = ',')}$"), 
      str_glue("Panel C: Baseline knowledge, $N={format(N_baseline_worm, big.mark = ',')}$"),
      # str_glue("Panel C: Census covariates, $N={format(N_census,  big.mark = ',')}$"), 
      str_glue("Panel D: Implementation, $N={format(N_endline, big.mark = ',')}$")
) 

panel_list = n_per_comp_panel_df$n
names(panel_list) = panel_names

comp_bal_table = comp_wide_indiv_bal_df %>% 
knitr::kable(
    format = "latex",
    escape = FALSE, 
    booktabs = TRUE, 
    col.names = bal_table_names,
    caption = "Balance Table", 
    align = "lccccccccccccc"
) %>%
kable_styling(
  latex_options = c("scale_down")
) %>%
add_header_above(c("", "Close" = 6, "Far" = 6, ""))  %>%
pack_rows(
    index = panel_list,
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space, 
    hline_after = TRUE, 
    hline_before = TRUE,
    bold = TRUE
)




comp_bal_table %>%
  custom_save_latex_table("comp-balance-table")

```


```{r}

dist_comp_df = inner_join(
 comp_balance_tidy_df %>%
  filter(comp_type == "distance")  %>%
  mutate(estimate = if_else(str_detect(lhs, "pct_") & lhs_treatment == "control", pmin(1, estimate), estimate)) %>%
  select(
    lhs,
    contains('lhs'),
    contains("rhs"),
    term,
    estimate,
    std.error,
    p.value
  ) %>%
  filter(
    is.na(rhs_treatment)
  ) %>%
  select(lhs, lhs_treatment, estimate, std.error ) %>%
  mutate(lhs_treatment = factor(lhs_treatment, treat_levels_c)) %>%
  mutate(
    across(c(estimate, std.error), round, 3),
    lhs_treatment = str_to_title(str_sub(lhs_treatment, 1, 3)),
    estim_std = linebreak(paste0(estimate,"\n", str_glue("({std.error})")), align = "c") 
    ) %>%
    select(-estimate, -std.error) %>%
  pivot_wider(
    names_from = lhs_treatment, values_from = estim_std
  ) ,
    # select(1,4, 5, 3, 2 ),

 comp_balance_tidy_df %>%
  filter(comp_type == "distance")  %>%
  select(
    lhs,
    contains('lhs'),
    contains("rhs"),
    term,
    estimate,
    std.error,
    p.value
  ) %>%
  filter(
    !is.na(rhs_treatment)
  ) %>%
  select(lhs, lhs_treatment, estimate, p.value ) %>%
  mutate(lhs_treatment = factor(lhs_treatment, treat_levels_c)) %>%
  mutate(
    across(c(estimate, p.value), round, 3), 
    lhs_treatment = paste0(
    "$\\textrm{", 
    str_to_title(str_sub(lhs_treatment, 1, 3)),
    "}_{\\text{far - close}}",
    "$"
     ),
    estim_std = linebreak(
      paste0(estimate,"\n", str_glue("{{[{p.value}]}}")), align = "c") 
     
     ) %>%
     select(-estimate, -p.value) %>%
  pivot_wider(
    names_from = lhs_treatment, values_from = estim_std
  ) ,
    # select(1,4, 5, 3, 2 ),
  by = "lhs"
) %>%
  select(lhs, contains("Con"), contains("Ink"), contains("Cal"), contains("Bra"))


dist_comp_bal_tbl = dist_comp_df %>%
  inner_join(lhs_translation_df %>% select(lhs, clean_name, sample)) %>%
  mutate(lhs = clean_name) %>%
  arrange(sample) %>%
  select(-clean_name, -sample) %>%
  knitr::kable(
      format = "latex",
      col.names = c("", colnames(.)[2:ncol(.)]),
      escape = FALSE, 
      booktabs = TRUE,
      align = "lcccccccc", 
      linesep = "",
      caption = "Distance Comparison Balance table"
  ) %>%
  kable_styling(
    latex_options = c("scale_down")
  )   %>%
pack_rows(
    index = panel_list,
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space, 
    hline_after = TRUE, 
    hline_before = TRUE,
    bold = TRUE
)

dist_comp_bal_tbl %>%
  custom_save_latex_table("dist-comp-balance-table")

```

```{r}
#| endline-table, eval=TRUE


endline_balance_df = create_balance_input(
    endline_tidy_df %>% filter(!str_detect(term, "county")), 
    col_order = col_order[!str_detect(col_order, "_p$")], 
    digits = 3
)   %>%
  mutate(type = "fit") %>%
  bind_rows(
    endline_p_val_df %>%  
      mutate(across(where(is.numeric), round, 3)) %>%
      mutate_all(as.character) %>%
      mutate(type = "pval")
  ) %>%
  mutate(lhs = str_remove(lhs, "lhs: ")) %>%
  left_join(lhs_translation_df %>% select(lhs = lhs_no_prefix, clean_name)) %>%
  mutate(lhs = clean_name) %>%
  select(-clean_name) %>%
  arrange(lhs, type) %>%
  mutate(lhs = if_else(type == "pval", paste0("$\\Delta$", lhs, ", $p$-value"), lhs)) %>%
  select(-type) %>%
  mutate(across(where(is.character), ~if_else(.x == "", "-", .x))) %>%
  mutate(across(where(is.character), replace_na, "-")) %>%
  select(all_of(col_order)) 

treat_colnames = str_to_title(treat_levels_c)
endline_bal_table = endline_balance_df %>% 
knitr::kable(
    format = "latex",
    escape = FALSE, 
    col.names = c("", treat_colnames, "F-test $p$-value", treat_colnames, "F-test $p$-value", "Joint F-test $p$-value"), 
    booktabs = TRUE, 
    caption = "Endline Table", 
    align = "lccccccccccc",
    linesep = "",
) %>%
kable_styling(
  latex_options = c("scale_down")
) %>%
add_header_above(c("", "Close" = 5, "Far" = 5, "")) 

endline_bal_table %>%
  custom_save_latex_table("endline-table")


```



```{r}
#| cts-distance-pval-table, eval=FALSE
1+1


rename_lhs = function(data, name_var = term) {
  data %>%
    mutate({{name_var}} := str_remove({{name_var}}, "lhs: ")) %>%
      mutate(
        {{ name_var }} := str_replace_all({{ name_var }}, "_", " ") %>% 
          str_to_title()
      )  %>%
  mutate(
    {{name_var}} := case_when(
      {{ name_var  }} == "N Indiv" ~ "N individuals", 
      {{ name_var }} == "N Pot" ~ "N points of treatment",
     {{ name_var}}  == "Cluster Dist To Pot" ~ "Cluster distance to PoT",
     {{ name_var}}  == "Baseline Neighbours Worm Knowledge" ~ "Understand deworming externality, baseline",
     {{ name_var}}  == "Treated Lgl" ~ "Dewormed self", 
     {{ name_var}}  == "Months Since Treatment" ~ "Months since last dewormed",
     {{ name_var}}  == "Know deworming stops worms" ~ "Knowledge of deworming medication", 
     {{ name_var}}  == "All Can Get Worms" ~ "Know everyone can be infected", 
     {{ name_var}}  == "Correct When Treat" ~ "Know bi-yearly treatment recommended", 
     {{ name_var}}  == "Num Recognised" ~ "Number of individuals recognised in community", 
      TRUE ~ {{name_var}}
    )
  )
}

cts_distance_pval_df = read_rds(
  file.path(
    "temp-data",
    "discrete_cts_dist_balance.rds"
  )
) %>%
  enframe(name = "lhs")  %>%
  left_join(
    lhs_translation_df %>% 
    select(lhs, clean_name)) %>%
  mutate(lhs = clean_name) %>%
  select(-clean_name)

```


```{r}
#| baseline-perception-balance

baseline_perception_data = read_rds(
  "temp-data/praise_stigma_baseline.rds"
)

baseline_perception_fits = baseline_perception_data[[1]]
baseline_perception_pvals = baseline_perception_data[[2]]


tidy_b_p_fits = map_dfr(
  baseline_perception_fits,
  tidy,
  .id = "sample"
)  %>%
  mutate(
    topic = str_extract(sample, "(?<=sample: )\\w+$")
  ) %>%
  filter(str_detect(term, "treat_dist")) %>%
  mutate(
    sample = rep(c("praise", "stigma"), each = n()/2)
  ) %>%
  mutate(
    treatment = str_extract(term, "(?<=disttreat: )\\w+"),
    distance = str_extract(term, "(?<=, dist: )\\w+$")
  ) %>%
  select(
    sample, topic, treatment, distance, estimate, std.error
  ) %>%
  mutate(
    across(where(is.numeric), round, 3),
    estim_std = linebreak(
      paste0(
        estimate, "\n",
        str_glue(
          "({std.error})"
        )
      ),
      align = "c"
    )
  )  %>%
  select(-estimate, -std.error) 

wide_tidy_b_p_fits = tidy_b_p_fits %>%
  pivot_wider(
    names_from = c(treatment, distance),
    values_from = estim_std
  ) %>%
  select(
    sample,
    topic,


    control_close,
    ink_close,
    calendar_close,
    bracelet_close,


    control_far,
    ink_far,
    calendar_far,
    bracelet_far
  ) 


joint_baseline_perception_pvals = map_dbl(baseline_perception_pvals, "joint_pval") %>%
  enframe() %>%
  mutate(
    sample = rep(c("praise", "stigma"), each = n()/2)
  ) %>%
  mutate(
    topic = str_extract(name, "(?<=sample: )\\w+$")
  ) %>%
  select(
    sample,
    topic,
    p_val = value
  ) %>%
  mutate(
    p_val = round(p_val, 3)
  )

wide_tidy_b_p_fits = wide_tidy_b_p_fits %>%
  left_join(
    joint_baseline_perception_pvals,
    by = c("sample", "topic")
  ) %>%
  mutate(
    topic = case_when(
      topic == "clothe" & sample == "praise" ~ "Wearing nice clothes to church",
      topic == "defecat" & sample == "praise" ~ "Use latrine",
      topic == "dewor" & sample == "praise" ~ "Deworming during MDA",
      topic == "immuniz" & sample == "praise" ~ "Immunizing children",

      topic == "clothe" & sample == "stigma" ~ "Not wearing nice clothes to church",
      topic == "defecat" & sample == "stigma" ~ "Open defecation",
      topic == "dewor" & sample == "stigma" ~ "Not deworming during MDA",
      topic == "immuniz" & sample == "stigma" ~ "Not immunizing children",
    )
  ) %>%
  mutate(
    sample = str_to_title(sample)
  )

baseline_perception_tbl = wide_tidy_b_p_fits %>%
  select(-sample) %>%
  kbl(
    col.names = c(
      "Topic",

      "Control",
      "Ink",
      "Calendar",
      "Bracelet",

      "Control",
      "Ink",
      "Calendar",
      "Bracelet",

      "Joint Test"
    ), 
    format = "latex", 
    booktabs = TRUE, 
    escape = FALSE, 
    align = "lccccccccc", 
    caption = "Baseline Perception Balance"
  )  %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(
    c(
      " " = 1,
      "Close" = 4, 
      "Far" = 4,
      " " = 1
      )
  ) %>%
  pack_rows(
    index = c(
      "Panel A: Praise" = 4, 
      "Panel A: Stigma" = 4
    ), 
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space, 
    hline_after = TRUE, 
    hline_before = TRUE,
    bold = TRUE
  )  

baseline_perception_tbl %>%
  custom_save_latex_table(
    "baseline-perception-table"
  )


```


```{r, sample_n, results="asis"}

# sample_meta_df = N_by_treat_dist_df %>%
#   gather(variable, value, -type, -lhs) %>%
#   group_by(
#     type, lhs
#   ) %>%
#   summarise(
#     n = sum(value, na.rm = TRUE)
#   ) %>%
#   ungroup() %>%
#   spread(lhs, n) %>%
#   mutate(
#     sample = case_when(
#       type == "beliefs" ~ "Beliefs", 
#       type == "takeup" ~ "Takeup", 
#       type == "WTP" ~ "WTP"
#     )
#   ) %>%
#   select(-type) %>%
#   select(sample, everything())



# sample_meta_tbl = sample_meta_df %>%
#     kbl(
#         booktabs = TRUE, 
#         format = "latex", 
#         caption = "Sample Size Across Experiments", 
#         align = "lcc",
#         col.names = c("Experiment", "N Individuals", "N PoTs")
#     )  %>%
#     kable_styling()
# sample_meta_tbl

```



```{r}
#| pref-fit-table, results="asis"

pref_df = analysis_data %>%
  filter(!is.na(gift_choice), monitored, monitor.consent, !hh.baseline.sample.pool, !is.na(sms.treatment)) %>% 
  filter(
    assigned.treatment %in% c("control", "ink")
  ) %>%
  select(
    gift_choice, 
    assigned_treatment = assigned.treatment, 
    dist_group = dist.pot.group,
    cluster.id,
    county,
    dewormed,
    standard_cluster.dist.to.pot
    ) %>%
    mutate(pref_cal = gift_choice == "calendar") 



pref_fit_control_ink = pref_df %>%
    fixest::feglm(
      pref_cal ~ dist_group | county,
      family = "probit",
      cluster = ~cluster.id
    )

pref_fit_control_ink_cov = pref_df %>%
    fixest::feglm(
      pref_cal ~ assigned_treatment + dist_group + standard_cluster.dist.to.pot + dewormed | county,
      family = "probit",
      cluster = ~cluster.id
    )

pref_fit_control = pref_df %>%
  filter(assigned_treatment == "control") %>%
    fixest::feglm(
      pref_cal ~ dist_group | county,
      family = "probit",
      cluster = ~cluster.id
    )

tex_postprocessing = function(tex) {
    tex %>%
        str_remove("\\\\begin\\{table\\}\\[htbp\\]") %>%
        str_remove("\\\\end\\{table\\}")
}


pref_fit_table_pp = fixest::etable(
  list(
    "(1) Sample: Control" = pref_fit_control,
    "(2) Sample: Control + Ink" = pref_fit_control_ink,
    "(3) Sample: Control + Ink" = pref_fit_control_ink_cov
  ),
  dict = c(
    "dist_groupfar" = "Distance group: Far",
    "assigned_treatmentink" = "Ink Treatment",
    "standard_cluster.dist.to.pot" = "Distance to PoT",
    "dewormedTRUE" = "Dewormed",
    "pref_cal" = "Prefer calendar"
  ),
  tex = TRUE,
  depvar = FALSE,
  title = "Preference for Calendar Gift Across Distance",
  style.tex = fixest::style.tex("aer"),
  file = "presentations/tables/pref-cal-gift.tex",
  replace = TRUE,
  postprocess.tex = tex_postprocessing
)


pref_fit_table_no_pp = fixest::etable(
  list(
    "(1) Sample: Control" = pref_fit_control,
    "(2) Sample: Control + Ink" = pref_fit_control_ink,
    "(3) Sample: Control + Ink" = pref_fit_control_ink_cov
  ),
  dict = c(
    "dist_groupfar" = "Distance group: Far",
    "assigned_treatmentink" = "Ink Treatment",
    "standard_cluster.dist.to.pot" = "Distance to PoT",
    "dewormedTRUE" = "Dewormed",
    "pref_cal" = "Prefer calendar"
  ),
  tex = TRUE,
  depvar = FALSE,
  title = "Preference for Calendar Gift Across Distance",
  style.tex = fixest::style.tex("aer"))


pref_fit_table_no_pp

```


```{r}

pref_gift_fit_not_dewormed = analysis_data %>%
    filter(!is.na(gift_choice), monitored, monitor.consent, !hh.baseline.sample.pool, !is.na(sms.treatment)) %>% 
    group_by(assigned.treatment, dist.pot.group, dewormed) %>% 
    mutate(arm.size = n()) %>% 
    group_by(gift_choice, add = TRUE) %>%
    filter(assigned.treatment %in% c("bracelet", "calendar")) %>%
    filter(
      dewormed == FALSE
    )  %>%
    ungroup() %>%
    select(cluster.id, gift_choice, assigned.treatment, dist.pot.group) %>%
    mutate(
      want_bracelet = gift_choice == "bracelet"
    )  %>%
    group_by(assigned.treatment, dist.pot.group) %>%
    fixest::feols(
      data = .,
      want_bracelet ~ dist.pot.group,
      fsplit = ~assigned.treatment,
      cluster = ~cluster.id
    ) 



pref_gift_fit_dewormed = analysis_data %>%
    filter(!is.na(gift_choice), monitored, monitor.consent, !hh.baseline.sample.pool, !is.na(sms.treatment)) %>% 
    group_by(assigned.treatment, dist.pot.group, dewormed) %>% 
    mutate(arm.size = n()) %>% 
    group_by(gift_choice, add = TRUE) %>%
    filter(assigned.treatment %in% c("bracelet", "calendar")) %>%
    filter(
      dewormed == TRUE
    )  %>%
    ungroup() %>%
    select(cluster.id, gift_choice, assigned.treatment, dist.pot.group) %>%
    mutate(
      want_bracelet = gift_choice == "bracelet"
    )  %>%
    group_by(assigned.treatment, dist.pot.group) %>%
    fixest::feols(
      data = .,
      want_bracelet ~ dist.pot.group,
      fsplit = ~assigned.treatment,
      cluster = ~cluster.id
    ) 

pref_gift_fit_not_dewormed



pref_gift_fit = pref_gift_fit_dewormed 
    
    
pref_gift_fit_tbl = fixest::etable(
  list(
    "(1) Sample: Calendar" = pref_gift_fit[[2]],
    "(2) Sample: Bracelet" = pref_gift_fit[[3]],
    "(3) Sample: Both" = pref_gift_fit[[1]]
  ),
  dict = c(
    "dist.pot.groupfar" = "Distance group: Far",
    "want_bracelet" = "Prefer bracelet",
    "assigned.treatment" = "Treatment Arm"
  ),
  tex = TRUE,
  depvar = FALSE,
  title = "Preference for Bracelet Gift Across Distance",
  style.tex = fixest::style.tex("aer"))

pref_gift_fit_tbl

```



## Robustness ATE Stuff

```{r}


ate_files = fs::dir_ls(
  file.path(
    here::here(),
    "temp-data"
  ),
  regexp = "rvar_processed_dist_fit96_ates.*1-4\\.rds$"
)

robustness_ate_rvar_df = 
  map_dfr(
    ate_files,
    read_rds,
    .id = "filepath"
  ) %>%
  mutate(
    filepath = basename(filepath),
    model_type = if_else(str_detect(model, "STRUCT"), "structural", "reduced form") %>% factor(),
    fit_type = factor(fit_type),
    model = factor(model)
    ) 




rf_robustness_ate_df =  robustness_ate_rvar_df %>%
  filter(fct_match(model, "REDUCED_FORM_NO_RESTRICT_DIST_CTS")) %>%
  create_ate_table(
    .estimand = "overall",
    group_var = treatment
  ) 


rf_robustness_ate_tbl = rf_robustness_ate_df %>%
  mutate(treatment = factor(treatment, levels = 
    ate_tbl_levels
  )) %>%
  mutate(far_minus_close = far - close) %>%
  rename_with(
    ~paste0("rf_", .),
    .cols = c(combined, close, far, far_minus_close)
  ) %>%
  arrange(treatment)   %>%
  create_cis(.width = params$width) %>%
  recode_control_mean()  %>%
  mutate(estimand = "overall") %>%
  select(-model)


rf_robustness_kbl_df = rf_robustness_ate_tbl %>% 
  arrange(treatment) %>%
  select(-estimand) %>%
  kbl(
    col.names = c(
      # "Estimand", 
      # "Treatment", 
      "Dependent variable: Take-up",
      paste0("(", 1:4, ")")
    ), 
    format = "latex", 
    linesep = "",
    booktabs = TRUE, 
    escape = FALSE, 
    align = "lcccc", 
    caption = "Results"
  )  %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(
    c(" ", 
      "Combined", 
      "Close", 
      "Far", 
      "Far - Close"
      ), 
    line = FALSE
  ) %>%
  add_header_above(
    c(
      " " = 1,
      "Reduced Form" = 4
      )
  ) %>%
  row_spec(c(3), hline_after = TRUE) 
rf_robustness_kbl_df %>%
  custom_save_latex_table(
    "robustness-rf-cts-dist-te-table"
  )

```



```{r}

struct_robustness_ate_df = robustness_ate_rvar_df %>%
  filter(fct_match(model_type, "structural")) %>%
  create_ate_table(
    .estimand = "overall",
    group_var = treatment
  ) 


new_model_levels = c(
  "High WTP Prior Mean",
  "High WTP Prior Variance",
  "No WTP Submodel",
  "No Beliefs Submodel",
  "No Submodels"
)

rename_models = function(data, variable) {
  data %>%
    mutate(
      {{variable}} := case_when(
        model == "STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP_HIGH_MU_WTP_VAL" ~ "High WTP Prior Mean",
        model == "STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP_HIGH_SD_WTP_VAL" ~ "High WTP Prior Variance",
        model == "STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP_NO_BELIEFS_SUBMODEL" ~ "No Beliefs Submodel",
        model == "STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP_NO_WTP_SUBMODEL" ~ "No WTP Submodel",
        model == "STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP_NO_SUBMODELS" ~ "No Submodels"
      )
    )
}

struct_robustness_ate_tbl = struct_robustness_ate_df %>%
  mutate(treatment = factor(treatment, levels = 
    ate_tbl_levels
  )) %>%
  mutate(far_minus_close = far - close) %>%
  rename_with(
    ~paste0("struct_", .),
    .cols = c(combined, close, far, far_minus_close)
  ) %>%
  arrange(treatment)   %>%
  create_cis(.width = params$width) %>%
  recode_control_mean()  %>%
  mutate(estimand = "overall")  %>%
  rename_models(model) %>%
  mutate(
    model = factor(model, levels = new_model_levels)
  )




struct_robustness_kbl_df = struct_robustness_ate_tbl %>%
  arrange(treatment, model) %>%
  select(-estimand) %>%
  kbl(
    col.names = c(
      # "Estimand", 
      # "Treatment", 
      "Model",
      "Treatment",
      paste0("(", 1:4, ")")
    ), 
    format = "latex", 
    linesep = "",
    booktabs = TRUE, 
    escape = FALSE, 
    align = "llcccc", 
    caption = "Results"
  )  %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(
    c(" ",
      " ", 
      "Combined", 
      "Close", 
      "Far", 
      "Far - Close"
      ), 
    line = FALSE
  ) %>%
  add_header_above(
    c(
      " " = 2,
      "Structural" = 4
      )
  ) %>%
  row_spec(c(5, 10, 15, 20), hline_after = TRUE) 

struct_robustness_kbl_df

struct_robustness_kbl_df %>%
  custom_save_latex_table(
    "robustness-struct-te-table"
  )


```



```{r}
# pigou-output

dynamic_optim_post_name = "posterior-optimal-distance-dynamic_vstar-lambda_0-externality_0-model_STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP-fit-version_86.csv"
static_optim_post_name = "posterior-optimal-distance-static_vstar-lambda_0-externality_0-model_STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP-fit-version_86.csv"

optim_post_df = imap_dfr(
  lst(
    dynamic_optim_post_name,
    static_optim_post_name
  ),
  ~read_csv(file.path("temp-data", .x)),
  .id = "vstar_type"
) %>%
  mutate(
    # regex to match very first word and stop before underscore
    vstar_type = factor(str_extract(vstar_type, "^[^_]*"))
  )


optim_post_df  %>%
  select(-contains('static')) %>%
  pivot_wider(
    names_from = vstar_type, values_from = optimal_distance
  )  %>%
  mutate(
    difference = static - dynamic
  ) %>%
  group_by(treatment) %>%
  summarise(
    diff_pct = 100*mean(difference/dynamic, na.rm = TRUE),
    mean_difference = mean(difference, na.rm = TRUE)
  )


optim_te_tbl = optim_post_df %>%
  bind_rows(
    optim_post_df  %>%
      select(-contains('static')) %>%
      pivot_wider(
        names_from = vstar_type, values_from = optimal_distance
      )  %>%
      mutate(
        difference = static - dynamic
      )  %>%
      select(
        treatment, draw_id, optimal_distance = difference
      ) %>%
      mutate(vstar_type = "static - dynamic")
  ) %>%
  filter(!is.na(optimal_distance)) %>%
  group_by(
    vstar_type, treatment
  ) %>%
  summarise(
    mean_est = mean(optimal_distance),
    per_0.025 = quantile(optimal_distance, 0.025),
    per_0.975 = quantile(optimal_distance, 0.975)
  ) %>%
  mutate(across(where(is.numeric), round))  %>%
  mutate(
    estim_value = linebreak(
      paste0(mean_est, "\n", "(", per_0.025, ", ", per_0.975, ")"), 
      align = "c"
      )
  ) %>%
  select(vstar_type, treatment, estim_value) %>%
  mutate(
    vstar_type = str_replace(vstar_type, "static", "Fixed"),
    vstar_type = str_replace(vstar_type, "dynamic", "Dynamic")
  ) %>%
  mutate(
    treatment = factor(treatment, levels = c("control", "ink", "calendar", "bracelet")),
    treatment = fct_relabel(treatment, str_to_title) %>% fct_rev,
    vstar_type = factor(vstar_type, levels = c("Fixed - Dynamic", "Fixed", "Dynamic")) %>% fct_rev()
  ) %>%
  arrange(vstar_type, treatment)  %>%
  ungroup()



pigou_optim_te_tbl_tex = optim_te_tbl %>%
  select(-vstar_type) %>%
  kbl(
    col.names = c(
      "Treatment",
      "Optimal Distance"
    ), 
    format = "latex", 
    linesep = "",
    booktabs = TRUE, 
    escape = FALSE, 
    align = "lc", 
    caption = "Welfare Maximising Distance - Results"
  )  %>%
  kable_styling(
    # latex_options = c("scale_down")
  ) %>%
  pack_rows(
    index = c(
      "Panel A: Dynamic $\\Delta(w^*)$" = 4, 
      "Panel B: Fixed $\\Delta(w^*)|_{d=0.5km}$" = 4, 
      "Panel C: Fixed - Dynamic" = 4
    ), 
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space, 
    hline_after = TRUE, 
    hline_before = TRUE,
    bold = TRUE
  )  %>%
  row_spec(c(3, 7, 12), hline_after = TRUE) 




pigou_optim_te_tbl_tex

pigou_optim_te_tbl_tex %>%
  custom_save_latex_table(
    "pigou-optim-te-table"
  )


```


```{r}
#wide-pigou
wide_pigou_optim_te_tbl_tex = optim_te_tbl %>%
  pivot_wider(
    names_from = vstar_type, values_from = estim_value
  )  %>%
  kbl(
    col.names = c(
      "Treatment",
      "Dynamic $\\Delta(w^*)$",
      "Fixed $\\Delta(w^*)|_{d=0.5km}$",
      "Fixed - Dynamic"
    ), 
    format = "latex", 
    linesep = "",
    booktabs = TRUE, 
    escape = FALSE, 
    align = "lccc", 
    caption = "Welfare Maximising Distance - Results"
  )  %>%
  kable_styling(
    # latex_options = c("scale_down")
  ) %>%
  row_spec(c(3), hline_after = TRUE)  %>%
  add_header_above(
    c(
      " " = 1,
      "Welfare Maximising Distance" = 3
      )
  ) 


wide_pigou_optim_te_tbl_tex

wide_pigou_optim_te_tbl_tex %>%
  custom_save_latex_table(
    "wide-pigou-optim-te-table"
  )




```


# Robustness Structural Model With Clustering



```{r}
#| robustness-struct-te-table, eval=FALSE

ate_rvar_struct_robust = read_rds(
    file.path(
      "temp-data",
      str_glue(
          "rvar_processed_dist_fit101_ates_STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP_HIER_FOB_1-4.rds"
      )
    )
  )

struct_ate_robust_df =  ate_rvar_struct_robust %>%
  create_ate_table(
    .estimand = "overall",
    group_var = treatment
  )



signal_ate_robust_df = ate_rvar_struct_robust %>%
  mutate(mu_treatment = str_to_title(mu_treatment)) %>%
  create_ate_table(
    .estimand = "signal",
    group_var = mu_treatment
  )

private_ate_robust_df = ate_rvar_struct_robust %>%
  create_ate_table(
    .estimand = "private",
    group_var = treatment
  )


ate_tbl_levels = c(
    "Bracelet",
    "Calendar",
    "Ink",
    "bracelet_minus_calendar",
    "Control"
)

robust_incentive_ate_tbl = struct_ate_robust_df %>%
  mutate(treatment = factor(treatment, levels = 
    ate_tbl_levels
  )) %>%
  mutate(far_minus_close = far - close) %>%
  arrange(treatment)   %>%
  create_cis(.width = params$width) %>%
  recode_control_mean()  %>%
  mutate(estimand = "overall")

robust_private_ate_tbl = private_ate_robust_df %>%
  mutate(treatment = factor(treatment, levels = 
    ate_tbl_levels
  )) %>%
  arrange(treatment)   %>%
  create_cis(.width = params$width) %>%
  recode_control_mean() %>%
  mutate(estimand = "private")

robust_signal_ate_tbl = signal_ate_robust_df %>%
  rename(treatment = mu_treatment) %>%
  mutate(treatment = factor(treatment, levels = 
    ate_tbl_levels
  )) %>%
  mutate(far_minus_close = far - close) %>%
  arrange(treatment)   %>%
  create_cis(.width = params$width) %>%
  recode_control_mean() %>%
  mutate(estimand = "signal")



robust_all_ate_tbl = bind_rows(
  robust_incentive_ate_tbl,
  robust_signal_ate_tbl,
  robust_private_ate_tbl
) %>%
  mutate(estimand = factor(estimand, levels = c('private', 'signal', 'overall')) %>% fct_rev) %>%
  select(estimand, treatment, everything())

robust_all_ate_tbl
```


```{r}
latex_group_gap_space = "2em"
1+2
```


```{r, results="asis"}
1+3

robust_te_kbl_df = robust_all_ate_tbl %>% 
  arrange(estimand, treatment) %>%
  select(-estimand) %>%
  select(-model) %>%
  kbl(
    col.names = c(
      # "Estimand", 
      # "Treatment", 
      "Dependent variable: Take-up",
      paste0("(", 1:4, ")")
    ), 
    format = "latex", 
    # linesep = "\\addlinespace \\addlinespace \\addlinespace",
    booktabs = TRUE, 
    escape = FALSE, 
    # align = "lcccc", 
    caption = "Results"
  )  %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(
    c(" ", 
      "Combined", 
      "Close", 
      "Far", 
      "Far - Close"
      ), 
    line = FALSE
  ) %>%
  # add_header_above(
  #   c(
  #     " " = 1,
  #     "Structural" = 4
  #     )
  # ) %>%
  pack_rows(
    index = c(
      "Panel A: Overall" = 5, 
      "Panel B: Signalling" = 5, 
      "Panel C: Private" = 5
    ), 
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space, 
    hline_after = TRUE, 
    hline_before = TRUE,
    bold = TRUE
  )  %>%
  row_spec(c(3, 8, 13), hline_after = TRUE) 

robust_te_kbl_df

robust_te_kbl_df %>%
  custom_save_latex_table(
    "cluster-robust-struct-te-table"
  )

x = 1 + 5
```



```{r}

robust_overall_te_kbl_df = robust_all_ate_tbl %>% 
  arrange(estimand, treatment) %>%
  filter(estimand == "overall") %>%
  select(-estimand) %>%
  select(-model) %>%
  kbl(
    col.names = c(
      "Dependent variable: Take-up",
      paste0("(", 1:4, ")")
    ), 
    format = "latex", 
    booktabs = TRUE, 
    escape = FALSE, 
    align = "lcccc", 
    caption = "Overall Results") %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(
    c(" ", 
      "Combined", 
      "Close", 
      "Far", 
      "Far - Close"
      ), 
    line = FALSE
  ) %>%
  add_header_above(
    c(
      " " = 1,
      "Structural" = 4
      )
  ) %>%
  pack_rows(
    index = c(
      "Panel A: Overall" = 5
    ), 
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space, 
    hline_after = TRUE, 
    hline_before = TRUE,
    bold = TRUE
  )  %>%
  row_spec(c(3), hline_after = TRUE) 

robust_overall_te_kbl_df %>%
  custom_save_latex_table("cluster-robust-struct-overall-te-table")


```

# Robustness Structural Model Individual Distance Cost, Community Info


```{r}

ate_rvar_struct_indiv_dist_community_fp = read_rds(
    file.path(
      "temp-data",
      "rvar_processed_dist_fit102_INDIV_incentive_tes_STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP_INDIV_DIST_COMMUNITY_FP_1-2.rds"
    )
  )

ate_tbl_indiv_dist_community_fp = ate_rvar_struct_indiv_dist_community_fp %>%
  create_cis(.width = params$width) %>%
  select(
    treatment, variable, value
  ) %>%
  mutate(variable = factor(variable, levels = c("combined", "close", "far", "far_minus_close"))) %>%
  arrange(variable) %>%
  pivot_wider(
    names_from = variable,
    values_from = value
  ) %>%
  recode_control_mean() %>%
  mutate(
    treatment = factor(treatment, levels = c("Bracelet", "Calendar", "Ink", "Bracelet - Calendar", "Control mean"))
  )  %>%
  arrange(treatment)


create_robustness_tbl = function(data) {
data %>%
  kbl(
    col.names = c(
      "Dependent variable: Take-up",
      paste0("(", 1:4, ")")
    ), 
    format = "latex", 
    booktabs = TRUE, 
    escape = FALSE, 
    align = "lcccc", 
    caption = "Overall Results") %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(
    c(" ", 
      "Combined", 
      "Close", 
      "Far", 
      "Far - Close"
      ), 
    line = FALSE
  ) %>%
  add_header_above(
    c(
      " " = 1,
      "Structural" = 4
      )
  ) %>%
  pack_rows(
    index = c(
      "Panel A: Overall" = 5
    ), 
    italic = TRUE,
    escape = FALSE,
    # latex_gap_space = latex_group_gap_space, 
    hline_after = TRUE, 
    hline_before = TRUE,
    bold = TRUE
  )  %>%
  row_spec(c(3), hline_after = TRUE) 
}


ate_tbl_indiv_dist_community_fp %>%
  create_robustness_tbl()  %>%
  custom_save_latex_table("indiv-dist-community-fp-robust-struct-overall-te-table")



```

# Robustness Structural Model Individual Distance Cost, Individual FP


```{r}

ate_rvar_struct_indiv_dist_indiv_fp = read_rds(
    file.path(
      "temp-data",
      "rvar_processed_dist_fit104_INDIV_incentive_tes_STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP_INDIV_DIST_INDIV_FP_1-2.rds"
    )
  )

ate_tbl_indiv_dist_indiv_fp = ate_rvar_struct_indiv_dist_indiv_fp %>%
  create_cis(.width = params$width) %>%
  select(
    treatment, variable, value
  ) %>%
  mutate(variable = factor(variable, levels = c("combined", "close", "far", "far_minus_close"))) %>%
  arrange(variable) %>%
  pivot_wider(
    names_from = variable,
    values_from = value
  ) %>%
  recode_control_mean() %>%
  mutate(
    treatment = factor(treatment, levels = c("Bracelet", "Calendar", "Ink", "Bracelet - Calendar", "Control mean"))
  )  %>%
  arrange(treatment)



ate_tbl_indiv_dist_indiv_fp %>%
  create_robustness_tbl()  %>%
  custom_save_latex_table("indiv-dist-indiv-fp-robust-struct-overall-te-table")



```
