#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)
source("R/structural/main-core-data.R")
source_path <- main_core_option_value(
  args, "--source-path", "temp-data/main-core-lambda-identification"
)
output_path <- main_core_option_value(
  args,
  "--output-path",
  "presentations/structural-lambda-identification"
)
artifacts <- c(
  "main-core-lambda-nested-multipliers.tex",
  "main-core-lambda-nested-ates.tex",
  "main-core-lambda-prior-sensitivity.tex",
  "main-core-lambda-prior-sensitivity.pdf",
  "main-core-lambda-prior-contraction.pdf",
  "lambda-estimand-summary.csv",
  "lambda-fit-diagnostics.csv",
  "lambda-prior-contraction.csv",
  "lambda-specification-manifest.csv",
  file.path("profile", "main-core-lambda-profile.pdf"),
  file.path("profile", "lambda-profile-summary.csv"),
  file.path("profile", "lambda-profile-support.csv"),
  file.path("recovery", "main-core-lambda-recovery-contrast.pdf"),
  file.path("recovery", "main-core-lambda-recovery-multipliers.pdf"),
  file.path("recovery", "main-core-lambda-recovery-table.tex"),
  file.path("recovery", "lambda-recovery-metrics.csv"),
  file.path("recovery", "lambda-recovery-hmc-diagnostics.csv")
)
missing <- artifacts[!file.exists(file.path(source_path, artifacts))]
if (length(missing) > 0L) {
  stop("Cannot assemble incomplete package; missing: ",
       paste(missing, collapse = ", "), call. = FALSE)
}
dir.create(output_path, recursive = TRUE, showWarnings = FALSE)
for (artifact in artifacts) {
  destination <- file.path(output_path, basename(artifact))
  if (!file.copy(file.path(source_path, artifact), destination, overwrite = TRUE)) {
    stop("Failed to copy: ", artifact, call. = FALSE)
  }
}

writeLines(c(
  "\\subsection{Sensitivity to signal-specific social-image weights}",
  "The baseline model restricts the social-image weight $\\lambda$ to be common across experimental arms. We assess this restriction using nested specifications with a common weight, two weights pooling Ink/Bracelet as Any Signal and Control/Calendar as No Signal, and four arm-specific weights. Flexible specifications parameterize log-weight contrasts around a common geometric mean and report sensitivity to the prior standard deviation of pairwise log-weight ratios.",
  "",
  "\\input{main-core-lambda-nested-ates.tex}",
  "\\input{main-core-lambda-nested-multipliers.tex}",
  "\\input{main-core-lambda-prior-sensitivity.tex}",
  "",
  "\\begin{figure}[htbp]",
  "\\centering",
  "\\includegraphics[width=.78\\linewidth]{main-core-lambda-prior-sensitivity.pdf}",
  "\\caption{Prior sensitivity of signal-specific image weights and social multipliers}",
  "\\end{figure}",
  "",
  "\\begin{figure}[htbp]",
  "\\centering",
  "\\includegraphics[width=.78\\linewidth]{main-core-lambda-profile.pdf}",
  "\\caption{Regularized profile support for the Any Signal--No Signal image-weight contrast}",
  "\\end{figure}",
  "",
  "\\begin{figure}[htbp]",
  "\\centering",
  "\\includegraphics[width=.78\\linewidth]{main-core-lambda-recovery-contrast.pdf}",
  "\\caption{Simulation recovery of the signal-specific image-weight contrast}",
  "\\end{figure}",
  "",
  "\\input{main-core-lambda-recovery-table.tex}"
), file.path(output_path, "lambda-identification-appendix.tex"))

writeLines(c(
  "# Structural lambda identification package",
  "",
  "This directory is generated by `scratch/assemble-main-core-lambda-appendix.R`.",
  "It contains nested-model, prior-sensitivity, profile-support, and simulation-recovery outputs.",
  "The profile is regularized through the baseline nuisance-parameter priors and is not presented as a formal likelihood-ratio confidence interval.",
  "No main-paper TeX inclusion points are modified automatically."
), file.path(output_path, "README.md"))
