---
title: "Reduced Form Tables"
output: 
  pdf_document:
    keep_tex: yes
header-includes:
    - \usepackage{booktabs}
    - \usepackage{longtable}
    - \usepackage{array}
    - \usepackage{multirow}
    - \usepackage{wrapfig}
    - \usepackage{float}
    - \usepackage{colortbl}
    - \usepackage{tabu}
    - \usepackage{threeparttable}
    - \usepackage{threeparttablex}
    - \usepackage[normalem]{ulem}
    - \usepackage[utf8]{inputenc}
    - \usepackage{makecell}
    - \usepackage{xcolor}
    - \usepackage{pdflscape}
    - \newcommand{\blandscape}{\begin{landscape}}
    - \newcommand{\elandscape}{\end{landscape}}
params:
    output_path: temp-data 
    table_output_path: presentations/rf-tables
    show_probs: FALSE
    cache: FALSE
    width: 0.95
    fit: FALSE
    stat: std.error
---



```{r, "startup", include=FALSE}
library(tidyverse)
library(posterior)
library(tidybayes)
library(marginaleffects)
library(broom)
library(data.table)
library(knitr)
library(kableExtra)
library(ggthemes)
library(fixest)
library(magrittr)
library(stringr)

if (interactive()) {
    params = lst(
        table_output_path = "presentations/rf-tables",
        show_probs = FALSE,
        width = 0.95,
        cache = FALSE,
        fit = FALSE,
        stat = "std.error" # "ci", "p", "std.error"
    )
    source(file.path("rct-design-fieldwork", "takeup_rct_assign_clusters.R"))
    source(file.path("analysis_util.R"))
    source(file.path( "dist_structural_util.R"))
    source(file.path("multilvlr", "multilvlr_util.R"))
} else {
    source(file.path("rct-design-fieldwork", "takeup_rct_assign_clusters.R"))
    source(file.path("analysis_util.R"))
    source(file.path( "dist_structural_util.R"))
    source(file.path("multilvlr", "multilvlr_util.R"))
}

models_we_want = c(params$struct_models, params$rf_models)

options(
    dplyr.show_progress = FALSE, 
    digits = 4, 
    knitr.kable.NA = '')

knitr::opts_chunk$set(
    echo = FALSE, 
    cache = params$cache, 
    warnings = FALSE,
    warning = FALSE,
    message = FALSE,
    cache.path = stringr::str_glue("rf-takeup-table-cache/"), 
    fig.path = str_glue("rf-takeup-table-fig-cache/"), 
    fig.align = "center")

dir.create("presentations/rf-tables", showWarnings = FALSE)


ci_width = as.numeric(params$width)
```




```{r, "load_analysis_data"}
treat_levels_c = c("control", "ink", "calendar", "bracelet")
treat_levels = c("ink", "calendar", "bracelet")
dist_levels = c("close", "far")
model_level_order = c("reduced form", "structural")

quant_probs <- c(0.01, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99)

output_basepath = file.path(
  params$output_path,
  str_glue("output_dist_fit{params$fit_version}")
)


canva_palette_vibrant <- "Primary colors with a vibrant twist"

theme_set(theme_minimal() +
            theme(legend.position = "bottom"))

source(file.path("rct-design-fieldwork", "takeup_rct_assign_clusters.R"))
source(file.path("analysis_util.R"))
source(file.path( "dist_structural_util.R"))
source(file.path("multilvlr", "multilvlr_util.R"))

wgs.84 <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
kenya.proj4 <- "+proj=utm +zone=36 +south +ellps=clrk80 +units=m +no_defs"

rct.schools.data <- read_rds(file.path("data", "takeup_rct_schools.rds"))
rct.cluster.selection <- read_rds(file.path("data", "rct_cluster_selection_2.0.rds"))
cluster.strat.data <- read_rds(file.path("data", "takeup_processed_cluster_strat.rds"))
load(file.path("data", "takeup_village_pot_dist.RData"))
load(file.path("data", "analysis.RData"))

baseline.data = read_rds("temp-data/reclean_baseline_data.rds") # Not sampling data!

standardize <- as_mapper(~ (.) / sd(.))
unstandardize <- function(standardized, original) standardized * sd(original)

nosms_data <- analysis.data %>% 
  filter(sms.treatment.2 == "sms.control") %>% 
  left_join(village.centers %>% select(cluster.id, cluster.dist.to.pot = dist.to.pot),
            by = "cluster.id") %>% 
  mutate(standard_cluster.dist.to.pot = standardize(cluster.dist.to.pot)) %>% 
  mutate(standard_dist.to.pot = standardize(dist.to.pot)) %>% 
  group_by(cluster.id) %>% 
  mutate(cluster_id = cur_group_id()) %>% 
  ungroup()



monitored_nosms_data <- analysis.data %>% 
  filter(mon_status == "monitored", sms.treatment.2 == "sms.control") %>% 
  left_join(village.centers %>% select(cluster.id, cluster.dist.to.pot = dist.to.pot),
            by = "cluster.id") %>% 
  mutate(standard_cluster.dist.to.pot = standardize(cluster.dist.to.pot)) %>% 
  mutate(standard_dist.to.pot = standardize(dist.to.pot)) %>% 
  group_by(cluster.id) %>% 
  mutate(cluster_id = cur_group_id()) %>% 
  ungroup()


analysis_data <- monitored_nosms_data

## Load Census Data
census_data_env = new.env()
with_env = function(f, e = parent.frame()) {
    stopifnot(is.function(f))
    environment(f) = e
    f
}
load_census_function = function(){
  load(file.path("data", "takeup_census.RData"))
  return(census.data)
}
census_data = with_env(load_census_function, census_data_env)() %>%
  rename(census.consent = consent) # Rename this to reduce chance of error

n_indiv_df = census_data %>%
    group_by(cluster.id) %>%
    summarise(
        n_per_cluster = sum(num.individuals)
    )


clean_worm_covariates = function(data) {
  cov_data = data %>%
    unnest(when_treat) %>%
    mutate(
      who_worms_other = if_else(is.na(who_worms_other), "", who_worms_other),
      stop_worms_other = replace_na(stop_worms_other, ""),
      when_treat = replace_na(when_treat, "DK"),
      # these are nested lists of responses so we map_lgl and use any()
      all_can_get_worms = map2_lgl(
        who_worms, 
        who_worms_other,
        ~any(
          "everyone" %in% .x | 
          str_detect(str_to_lower(.y), "any") | 
          (("adult" %in% .x) & ("child" %in% .x)) |
          ("adult" %in% .x | str_detect(str_to_lower(.y), "adult|man|woman|men|women|person")) & ("child" %in% .x | str_detect(str_to_lower(.y), "child|under|young|teenager|below"))
      )
      ), 
      correct_when_treat = when_treat %in% c("every 3 months",
                                     "every 6 months"), 
      know_how_stop_worms = map2_lgl(
        stop_worms, 
        stop_worms_other,
        ~any(.x %in% c(
          "medicine", 
          "wearing shoes", 
          "using toilets", 
          "wash hands") | str_detect(.y, "cooked|prepar|cook"))),
      adult_in_family_treated = who_treated %in% c("adult", "both")
    )

  cov_data = cov_data %>%
    mutate(
      fully_aware_externalities = case_when(
        neighbours_worms_affect == "yes" & worms_affect == "yes" ~ TRUE, 
        is.na(neighbours_worms_affect) | is.na(worms_affect) ~ NA,
        TRUE ~ FALSE
      ),
      know_worms_infectious = spread_worms == "yes"
    )
  
    treated_past_present = "treated" %in% colnames(data) 
    if (treated_past_present) {
      cov_data = cov_data %>%
        mutate(
          treated_lgl = case_when(
            treated == "yes" ~ TRUE, 
            treated == "no" ~ FALSE, 
            TRUE ~ NA
          ),
      family_treated_lgl = family_treated == "yes"
        )
    }
    return(cov_data)
}

clean_pretreat_covariates = function(baseline_data, endline_data) {
  drop_vars = c(
    "starttime", 
    "endtime", 
    "age_census", 
    "phone_census", 
    "return",
    "no_return",
    "interview",
    "no_interview",
    "language_return",
    "isValidated"
    )
  cov_data = bind_rows(
    # baseline_data %>% select(-any_of(drop_vars)) %>% mutate(sample_type = "baseline"),
    endline_data %>% select(-any_of(drop_vars)) %>% mutate(sample_type = "endline")
  ) 
  cov_data = cov_data %>%
    mutate(
      floor_tile_cement = floor == "Cement" | floor == "Tiles"
    )
  school_year_df = tribble(
    ~school, ~years_schooling, 
    "Never gone to school", 0,
    "Primary 1", 1,
    "Primary 2", 2,
    "Primary 3", 3,
    "Primary 4", 4,
    "Primary 5", 5,
    "Primary 6", 6,
    "Primary 7", 7,
    "Primary 8", 8,
    "Secondary 1", 9,
    "Secondary 2", 10,
    "Secondary 3", 11,
    "Secondary 4", 12,
    "College", 13,
    "University", 13
  ) 
  cov_data = cov_data %>%
    mutate(
      completed_primary = (school == "Primary 8" | str_detect(school, "Secondary|College|University"))
    ) %>%
    left_join(school_year_df) %>%
    mutate(
      have_phone_lgl = case_when(
        have_phone == "Yes" ~ TRUE, 
        have_phone == "No" ~ FALSE, 
        TRUE ~ NA
      )
    )

  # ethnicity and religion
  cov_data = cov_data %>%
    mutate(
      ethnicity_luhya = ethnicity == "Luhya",
      religion_christianity = religion == 1
    )

    return(cov_data)
}


baseline_worm = baseline.data %>%
  clean_worm_covariates()
clean_takeup_variables = function(data) {
  data %>%
    mutate(
      female = gender == "female",
      have_phone_lgl = phone_owner
    )
}
analysis_data = analysis_data %>%
  clean_takeup_variables()

cluster_treat_df = read_rds(file.path("data", "takeup_processed_cluster_strat.rds"))  %>%
  mutate(
      treat_dist = paste0(
      "treat: ", 
      assigned.treatment,
      ", dist: ", dist.pot.group
      ) %>% factor()
  ) %>%
  select(cluster.id, treat_dist, cluster.dist.to.pot = dist.to.own.pot) %>%
  unique()
# # creating a single treat x distance variable for balance testing
# cluster_treat_df = analysis_data %>%
#   mutate(
#       treat_dist = paste0(
#       "treat: ", 
#       assigned.treatment,
#       ", dist: ", dist.pot.group
#       ) %>% factor()
#   ) %>%
#   select(cluster.id, treat_dist, cluster.dist.to.pot) %>%
#   unique()


pretreat_data = clean_pretreat_covariates(baseline.data, endline.data) %>%
  left_join(cluster_treat_df, by = "cluster.id") %>%
  filter(!is.na(treat_dist))

## Baseline Balance
baseline_worm_data = baseline_worm %>%
  inner_join(
    cluster_treat_df, 
    by = "cluster.id"
  ) %>%
  filter(!is.na(treat_dist))

# monitoring checks
sens_imp_df = read_csv("data/raw-data/Sensitization Monitoring Form.csv")
sens_imp_hh_df = read_csv("data/raw-data/Sensitization Monitoring Form-household.csv")


unique_hh_message_df = sens_imp_hh_df %>%
  mutate(
    message_list = str_split(message, " ")
  ) %>%
  select(PARENT_KEY, message_list) %>%
  unnest(message_list) %>%
  group_by(PARENT_KEY) %>%
  unique() %>%
  summarise(message_list = list(as.numeric(message_list))) %>%
  mutate(
    knowledge_message = map_lgl(message_list, ~all(c(1, 2, 3, 4, 5) %in% .x)
     ),
    availability_message = map_lgl(message_list, ~all(c(6, 7) %in% .x))
    )



clean_sens_imp_df = sens_imp_df %>%
  filter(!is.na(enumerator)) %>%
  filter(!is.na(announcement)) %>%
  mutate(announce_church = str_detect(where, "1")) %>%
  left_join(unique_hh_message_df, by = c("KEY" = "PARENT_KEY")) %>%
  select(
    cluster.id = cluster_id,
    announcement,
    announce_church,
    knowledge_message,
    availability_message
  ) %>%
  inner_join(cluster_treat_df, by = "cluster.id") %>%
  filter(!is.na(treat_dist)) %>%
  left_join(
    cluster.strat.data %>%
      select(cluster.id, county)
  ) 


# Add church and add announce

# aggregate to household level (for messages Q)
# then to community
# first five (knowledge of deworming)
# last two (knowledge of availability)


# PoT verification monitoring
clean_sens_summ_imp_df = clean_sens_imp_df %>%
  group_by(cluster.id, treat_dist, county) %>%
  summarise(
    n_announce = sum(announcement, na.rm = TRUE),
    n_announce_church = sum(announce_church, na.rm = TRUE),
    n_knowledge_message = sum(knowledge_message, na.rm = TRUE),
    n_avail_message = sum(availability_message, na.rm = TRUE),
    n_message = sum(!is.na(knowledge_message) | !is.na(availability_message)),
    n_total = n()
  ) %>%
  mutate(
    pct_announce = n_announce / n_total,
    pct_church = n_announce_church / n_total,
    pct_knowledge_message = n_knowledge_message / n_message,
    pct_avail_message = n_avail_message / n_message
  ) 
  
  


clean_implementation_vars = function(data)  {
  data %>%
    mutate(
      know_deworm = know_deworm == "yes",
      treat_begin = treat_begin == "knows",
      treat_end = treat_end == "knows",
      chv_visit =  chv_visit == "yes",
      flyer = flyer == "yes"
    )
}


worm_vars = c(
  "treated_lgl", 
  "know_how_stop_worms",
  "all_can_get_worms",
  "correct_when_treat",
  "fully_aware_externalities",
  "know_worms_infectious"
)


pretreat_vars = c(
  "completed_primary", 
  "floor_tile_cement",
  "ethnicity_luhya",
  "religion_christianity"
)

implementation_vars = c(
  "chv_visit",
  "flyer"
)


sens_vars = c(
  "pct_announce",
  "pct_church",
  "pct_knowledge_message",
  "pct_avail_message"
  )

# Distance/cluster size balance vars
takeup_vars = c(
  "n_per_cluster",
  "female",
  "have_phone_lgl",
  "age.census",
  "cluster.dist.to.pot"
)


# Indiv level balance variables
census_vars = c(
  "dewormed",
  "know_age" # just include this so fixest creates a list of fits...
)


praise_vars = c(
  "praise_immuniz",
  "praise_dewor"
)

stigma_vars = c(
  "stigma_immuniz",
  "stigma_dewor"
)


clean_census_data = census_data %>%
  filter(!is.na(assigned.treatment)) %>%
  right_join(
    analysis_data %>%
      select(cluster.id, dist.pot.group, cluster.dist.to.pot) %>%
      unique()
  ) %>%
  mutate(
    female = gender == 2,
    age = age.census,
    have_phone_lgl = have_phone == "Yes" 
    )

analysis_data = analysis_data %>%
    left_join(
        n_indiv_df,
        by = "cluster.id"
    ) %>%
    ungroup() %>%
    mutate(have_phone_lgl = have_phone == "Yes")



analysis_data = analysis_data %>%
  mutate(
      treat_dist = paste0(
      "treat: ", 
      assigned.treatment,
      ", dist: ", dist.pot.group
      ) %>% factor()
    )  



#' Save Latex table 
#' 
#' This function saves a latex table to file whilst removing the table environment
#' this means we can just use \input{table} in the main tex file whilst controlling 
#' placement/notes in the tex file itself (Anne doesn't use Rmd for everything :<( )
custom_save_latex_table = function(table, table_name){
  table_conn = file(
    file.path(
      params$table_output_path, paste0(table_name, ".tex")
    )
  )
  # Create space in latex due to rmd bug with \\ immediately followed by [
  # table = table  %>%
  #   str_replace_all(., "removeme12345", "  ")

  attr(table, "kable_meta")$contents = str_replace_all(attr(table, "kable_meta")$contents, "removeme12345", " ")
  table[1] = str_replace_all(table[1], "removeme12345", " ")


  clean_table = table %>%
    str_remove(
      ., 
      fixed("\\begin{table}")
    ) %>%
    str_remove(
      .,
      "\\\\caption\\{.*\\}"
    ) %>%
    str_remove(
      ., 
      "\\\\end\\{table\\}"
    ) 
    
    
    clean_table %>%
      writeLines(
        table_conn
      )
    close(table_conn)

    return(table)
}
```


```{r}
#| comparisons-functions


create_comparisons = function(fit) {
    close_far_tes = avg_comparisons(
        fit, 
        variables = list(assigned_treatment = "reference"),
        by = "assigned_dist_group",
        type = "response"
    )


    combined_tes = avg_comparisons(
        fit,
        variables = list(assigned_treatment = "reference"),
        type = "response"
    )

    create_hyp_bc_combined = function(data) {
        df = data %>%
            as_tibble()  %>%
            mutate(
                bra = str_detect(contrast, "bracelet") ,
                cal = str_detect(contrast, "calendar") 
            )
        bra_idx = which(df$bra)
        cal_idx = which(df$cal)
        hyp_string = paste0("b", bra_idx, " - b", cal_idx, " = 0")
        return(hyp_string)
    }
    create_hyp_bc = function(data, dist) {
        df = data %>%
            as_tibble()  %>%
            mutate(
                bra = str_detect(contrast, "bracelet") & assigned_dist_group == dist,
                cal = str_detect(contrast, "calendar") & assigned_dist_group == dist
            )
        bra_idx = which(df$bra)
        cal_idx = which(df$cal)
        hyp_string = paste0("b", bra_idx, " - b", cal_idx, " = 0")
        return(hyp_string)
    }

    bc_close_string = create_hyp_bc(close_far_tes, "close")
    bc_far_string = create_hyp_bc(close_far_tes, "far") 
    bc_combined_string = create_hyp_bc_combined(combined_tes)


    close_bc = hypotheses(
        close_far_tes,
        hypothesis = bc_close_string)
    far_bc = hypotheses(
        close_far_tes,
        hypothesis = bc_far_string)
    combined_bc = hypotheses(
        combined_tes,
        hypothesis = bc_combined_string
    )



    create_hp_vector = function(data, treat) {
        data %>%
            mutate(
                mat_value =  case_when(
                    lhs_term == treat & assigned_dist_group == "far" ~ 1,
                    lhs_term == treat & assigned_dist_group == "close" ~ -1,
                    TRUE ~ 0
                )
                ) %>%
                pull(mat_value)
    }

    filter_fun = function(data, treat) {
        df_we_want = data %>%
            filter(
                lhs_term == treat
            )
        string = paste0(df_we_want[df_we_want$assigned_dist_group == "far", "b_val"], " - ", df_we_want[df_we_want$assigned_dist_group == "close", "b_val"], " = 0")
        return (string)
    }
    close_far_string_df = close_far_tes %>%
        as_tibble() %>%
        mutate(
            b_val = paste0("b", 1:n())
        ) %>%
        select(contrast, b_val, assigned_dist_group) %>%
    mutate(lhs_term = str_extract(contrast, "(?<=mean\\()\\w+"))

    close_far_hypotheses = map_chr(
        c("bracelet", "calendar", "ink"),
        ~filter_fun(close_far_string_df, .x),
    )
    names(close_far_hypotheses) = c("bracelet", "calendar", "ink")


    close_far_hypotheses_vec = map(
        c("bracelet", "calendar", "ink"),
        ~create_hp_vector(close_far_string_df, .x) 
    ) 
    close_far_hypotheses_vec


    close_far_comp = close_far_hypotheses_vec %>%
        map(
            ~hypotheses(
                close_far_tes,
                hypothesis = .x,
                type = "response"
            )
        ) %>%
        map(as_tibble) %>%
        bind_rows() %>%
        mutate(
            assigned_dist_group = "far - close",
            contrast = c("bracelet", "calendar", "ink")
        )



    

    d1_s = filter_fun(close_far_string_df, "bracelet") %>%
        str_remove(" = 0")
    d2_s = filter_fun(close_far_string_df, "calendar") %>%
        str_remove(" = 0")
    double_diff_hp = str_glue("{d1_s} - ({d2_s}) = 0")

    double_diff_bc_fc = hypotheses(
        close_far_tes,
        double_diff_hp,
        type = "response"
        ) %>%
        mutate(
            contrast = "bracelet - calendar",
            assigned_dist_group = "far - close"
        )
    
    # control means
    cm_combined = avg_predictions(
        fit,
        variables = list(assigned_treatment = "control")
    ) %>%
        as_tibble() %>%
        mutate(
            contrast = "control",
            assigned_dist_group = "combined"
        )
    cts_distance = all(str_detect(coef(fit), "dist_group") == FALSE)
    
    cm_close_far = analysis_data %>%
        filter(
            assigned_treatment == "control"
        ) %>%
        group_by(assigned_dist_group) %>%
        summarise(
            estimate = mean(dewormed)
        ) %>%
        mutate(
            contrast = "control"
        )
    cm_combined = analysis_data %>%
        filter(assigned_treatment == "control") %>%
        summarise(
            estimate = mean(dewormed)
        ) %>%
        mutate(
            contrast = "control",
            assigned_dist_group = "combined"
        )

    cm_close_far_diff = cm_close_far %>%
        summarise(
            estimate = estimate[assigned_dist_group == "far"] - estimate[assigned_dist_group == "close"],
            assigned_dist_group = "far - close",
            contrast = "control"
        )

    # check if p.value present (i.e. not bayes)
    pval_present = "p.value" %in% colnames(close_far_comp)
    if (pval_present) {
        close_far_comp = close_far_comp %>%
            mutate(
                p.value = if_else(
                    contrast == "control",
                    NA_real_,
                    p.value
                ),
                conf.low = if_else(
                    contrast == "control",
                    NA_real_,
                    conf.low
                ),
                conf.high = if_else(
                    contrast == "control",
                    NA_real_,
                    conf.high
                )
            )
        cm_combined = cm_combined %>% 
            mutate(
                p.value = NA,
                conf.low = NA,
                conf.high = NA
                )
        cm_close_far = cm_close_far %>%
            mutate(
                p.value = NA,
                conf.low = NA,
                conf.high = NA
                )
        cm_close_far_diff = cm_close_far_diff %>%
            mutate(
                p.value = NA,
                conf.low = NA,
                conf.high = NA
                )
    }
    tes = bind_rows(
        close_far_tes,
        combined_tes %>% as_tibble()  %>% mutate(assigned_dist_group = "combined"),
        close_bc %>% mutate(contrast = "bracelet - calendar", assigned_dist_group = "close"), 
        far_bc %>% mutate(contrast = "bracelet - calendar", assigned_dist_group = "far"),
        combined_bc %>% mutate(contrast = "bracelet - calendar", assigned_dist_group = "combined"),
        close_far_comp,
        # control means
        cm_combined,
        cm_close_far,
        cm_close_far_diff,
        # double diff
        double_diff_bc_fc
    ) %>% 
        as_tibble() %>%
        mutate(
            contrast = str_remove_all(contrast, "mean\\("),
            contrast = str_remove_all(contrast, "\\)")
        ) %>%
        mutate(
            contrast = str_remove(contrast, " - control")
        )
    return(tes)
}

prep_tbl = function(tes, stat = "ci") {
    tbl_dist_levels = c(
        "combined",
        "close",
        "far",
        "far - close"
    )

    tbl_contrast_levels = c(
        "bracelet",
        "calendar",
        "ink",
        "bracelet - calendar",
        "Any signal - no signal",
        "control",
        "$p$(Any signal > No signal)"
    )




    if (stat == "ci") {
        tes = tes %>%
            mutate(
                val = paste0(
                    "(",
                    round(conf.low, 3),
                    ", ",
                    round(conf.high, 3),
                    ")"
                )
            )
    } else if (stat == "std.error"){
        tes = tes %>%
            mutate(val = paste0("{[", round(std.error, 3), "]}"))
    } else {
        tes = tes %>%
            mutate(
                val = paste0("{[", round(p.value, 3), "]}")
            )
    }
    

    tbl =  tes %>%
        select(contrast, assigned_dist_group, estimate, conf.low, conf.high, val)  %>%
        mutate(across(where(is.numeric), round, 3)) %>%
        mutate(
            estim_std = if_else(
                is.na(conf.low),
                linebreak(paste0(estimate), align = "c"),
                linebreak(paste0(estimate,"\n", str_glue("{val}")), align = "c") 
            )
        ) %>%
        select(-estimate, -any_of(c("p.value", "conf.low", "conf.high")), -val) %>%
        mutate(
            assigned_dist_group = factor(assigned_dist_group, tbl_dist_levels),
            assigned_dist_group = fct_relabel(assigned_dist_group, str_to_title),
            contrast = factor(contrast, tbl_contrast_levels)
        ) %>%
        arrange(assigned_dist_group, contrast) %>%
        pivot_wider(
            names_from = assigned_dist_group,
            values_from = estim_std
        )  %>%
        mutate(
            contrast = fct_relabel(contrast, str_to_title),
            contrast = fct_recode(contrast, "$p$(Any signal > No signal)" = "$P$(Any Signal > No Signal)")
        )
    return(tbl)
}

nice_kbl_table = function(tbl, cap, stat = params$stat) {

  linesep_str = if_else(stat == "ci", "\\addlinespace", "")

  nice_kbl = tbl %>%
  kbl(
    col.names = c(
      # "Estimand", 
      # "Treatment", 
      "Dependent variable: Take-up",
      paste0("(", 1:4, ")")
    ), 
    format = "latex", 
    linesep = linesep_str, 
    booktabs = TRUE, 
    escape = FALSE, 
    align = "lcccc", 
    caption = cap
  )  %>%
  kable_styling(
    latex_options = c("scale_down")
  ) %>%
  add_header_above(
    c(" ", 
      "Combined", 
      "Close", 
      "Far", 
      "Far - Close"
      ), 
    line = FALSE
  ) %>%
  add_header_above(
    c(
      " " = 1,
      "Reduced Form" = 4
      )
  ) %>%
  row_spec(c(3), hline_after = TRUE) 

}
```


```{r}


signal_comparisons = function(fit) {
    close_far_tes = avg_comparisons(
        fit,
        variables = list(signal = c("reference")),
        by = "assigned_dist_group",
        equivalence = c(0, 0)
        ) %>%
        as_tibble() %>%
        mutate(
            contrast = str_extract(contrast, "(?<=mean\\()\\w+")
        )


    combined_tes = avg_comparisons(
        fit,
        variables = list(signal = "reference"),
        equivalence = c(0, 0)
    ) %>%
        as_tibble() %>%
        mutate(
            contrast = str_extract(contrast, "\\w+")
        ) %>%
        mutate(
            assigned_dist_group = "combined"
        )

    nosignal_mean = avg_predictions(
        fit,
        variables = list(signal = "no signal"),
        by = "assigned_dist_group",
        equivalence = c(0, 0)
    ) %>%
    as_tibble() %>%
    mutate(
        contrast = "no signal"
    )

    nosignal_combined = avg_predictions(
        fit,
        variables = list(signal = "no signal"),
        equivalence = c(0, 0)
    ) %>%
        as_tibble() %>%
        mutate(
            assigned_dist_group = "combined"
        ) %>%
        mutate(contrast = "no signal")


    double_diff = avg_comparisons(
        fit,
        variables = list(signal = "reference"),
        by = "assigned_dist_group",
        hypothesis = "b2 - b1 = 0",
        equivalence = c(0, 0)
    ) %>%
    as_tibble() %>%
        mutate(
            assigned_dist_group = "far - close",
            contrast = "signal"
        ) %>%
        mutate(
            pval_onesided = p.value.noninf
        )

    tes_df = bind_rows(
        close_far_tes,
        combined_tes,
        double_diff,
        nosignal_combined,
        nosignal_mean
    ) %>%
    mutate(pval_onesided = p.value.noninf)


    return(tes_df)
} 



```


#### Frequentist Estimates ####

```{r}
#| freq-estimates
analysis_data = analysis_data %>%
    mutate(
        county = factor(county),
        cluster.id = factor(cluster.id),
        assigned_treatment = assigned.treatment,
        assigned_dist_group = dist.pot.group,
        signal = if_else(assigned_treatment %in% c("ink", "bracelet"), "signal", "no signal"),
        signal = factor(signal, levels = c("no signal", "signal"))
    )



probit_fit = analysis_data %>%
    feglm(
        dewormed ~ 0 + assigned_treatment:assigned_dist_group | county, 
        data = ., 
        family = binomial(link = "probit"), 
        cluster = ~cluster.id
    ) 

probit_dist_fit = analysis_data %>%
    feglm(
        dewormed ~ 0 + assigned_treatment:assigned_dist_group + standard_cluster.dist.to.pot | county,
        data = ., 
        family = binomial(link = "probit"), 
        cluster = ~cluster.id
    ) 

probit_hh_dist_cts_fit = analysis_data %>%
    mutate(assigned_treatment = factor(assigned_treatment)) %>%
    feglm(
        dewormed ~ 0 + assigned_treatment + standard_dist.to.pot  + i(assigned_treatment, standard_dist.to.pot, "control") | county,
        data = ., 
        family = binomial(link = "probit"), 
        cluster = ~cluster.id
    )

probit_dist_cts_fit = analysis_data %>%
    mutate(assigned_treatment = factor(assigned_treatment)) %>%
    feglm(
        dewormed ~ 0 + assigned_treatment + standard_cluster.dist.to.pot  + i(assigned_treatment, standard_cluster.dist.to.pot, "control")  | county,
        data = ., 
        family = binomial(link = "probit"), 
        cluster = ~cluster.id
    )


bind_rows(
probit_hh_dist_cts_fit %>%
    tidy() %>%
    select(term, estimate, std.error, p.value) %>%
    mutate(dist = "hh distance"),
probit_dist_cts_fit %>%
    tidy() %>%
    select(term, estimate, std.error, p.value) %>%
    mutate(dist = "cluster centroid")
) %>%
    mutate(p.value = round(p.value, 4))


probit_control_fit = analysis_data %>%
    feglm(
        dewormed ~ 0 + 
                    assigned_treatment:assigned_dist_group + 
                    standard_cluster.dist.to.pot  +
                    n_per_cluster +
                    female +
                    have_phone_lgl +
                    age.census | county,
        data = ., 
        family = binomial(link = "probit"), 
        cluster = ~cluster.id

    )


probit_signal_dist_cts_fit = analysis_data %>%
    feglm(
        dewormed ~ 0 + signal + standard_cluster.dist.to.pot  + i(signal, standard_cluster.dist.to.pot, "no signal")  | county,
        data = .,
        family = binomial(link = "probit"),
        cluster = ~cluster.id
    )

probit_signal_dist_fit = analysis_data %>%
    feglm(
        dewormed ~ 0 + signal:assigned_dist_group + standard_cluster.dist.to.pot | county,
        data = .,
        family = binomial(link = "probit"),
        cluster = ~cluster.id
    )

probit_signal_fit = analysis_data %>%
    feglm(
        dewormed ~ 0 + signal:assigned_dist_group  | county,
        data = .,
        family = binomial(link = "probit"),
        cluster = ~cluster.id
    )




signal_fits = analysis_data %>%
    feglm(
        dewormed ~ signal,
        data = .,
        family = binomial(link = "probit"),
        cluster = ~cluster.id,
        fsplit = ~assigned_dist_group
    ) 

analysis_data %>%
    feglm(
        dewormed ~ signal
    )
signal_fits[[1]]
map(signal_fits, 
    ~hypotheses(
        .x,
        "b2 = 0",
        equivalence = c(0, 0)
    ) %>%
    select(p.value.noninf)
)

hypotheses(
    avg_comparisons(signal_fits[[3]], by = "assigned_dist_group")
    )

comparisonsprobit_signal_dist_cts_fit

ols_fit = analysis_data %>%
    feols(
        dewormed ~ 0 + assigned_treatment:assigned_dist_group | county, 
        data = ., 
        cluster = ~cluster.id
    ) 

ols_dist_fit = analysis_data %>%
    feols(
        dewormed ~ 0 + assigned_treatment*standard_cluster.dist.to.pot | county, 
        data = ., 
        cluster = ~cluster.id
    ) 

ols_dist_fit  %>%
    tidy() %>%
    mutate(p.value = round(p.value, digits = 4))

probit_dist_cts_fit  %>%
    tidy() %>%
    mutate(p.value = round(p.value, digits = 4))


library(margins)



probit_signal_fit = 
    feglm(
        data = analysis_data,
        dewormed ~ 0 + signal:assigned_dist_group  | county,
        family = binomial(link = "probit"),
        cluster = ~cluster.id
    )

margins(probit_signal_fit)

rf_probit_tes = create_comparisons(probit_fit)
rf_probit_dist_tes = create_comparisons(probit_dist_fit)
rf_probit_control_tes = create_comparisons(probit_control_fit)

rf_signal_dist_tes = signal_comparisons(probit_signal_dist_fit)
rf_signal_tes = signal_comparisons(probit_signal_fit)
rf_signal_cts_dist_tes = signal_comparisons(probit_signal_dist_cts_fit)


rf_signal_tes %>%
    select(contrast, assigned_dist_group, estimate, std.error, p.value, pval_onesided) %>%
    mutate(
        p.value = round(p.value, 4)
    )

rf_probit_cts_dist_tes = create_comparisons(probit_dist_cts_fit)

rf_probit_cts_hh_dist_tes = create_comparisons(probit_hh_dist_cts_fit)
rf_ols_tes = create_comparisons(ols_fit)
rf_ols_dist_tes = create_comparisons(ols_dist_fit)

rf_signal_tes %>%
    select(term, contrast, assigned_dist_group, p.value) %>%
    mutate(p.value = round(p.value, 4))

rf_signal_cts_dist_tes %>%
    select(term, contrast, assigned_dist_group, p.value) %>%
    mutate(p.value = round(p.value, 4))

rf_probit_dist_tes %>%
    select(contrast, assigned_dist_group, estimate, std.error, p.value)

rf_probit_cts_dist_tes %>%
    select(contrast, assigned_dist_group, estimate, std.error, p.value)

rf_probit_cts_hh_dist_tes %>%
    select(contrast, assigned_dist_group, estimate, std.error, p.value)

probit_dist_cts_fit %>%
    tidy()


rf_signal_cts_dist_subset_tes = rf_signal_cts_dist_tes %>%
    filter(contrast != "no signal") %>%
    mutate(
        contrast = case_when(
            contrast == "signal" ~ "Any signal - no signal",
            TRUE ~ contrast
        )
    )

rf_signal_dist_subset_tes = rf_signal_dist_tes %>%
    filter(contrast != "no signal") %>%
    mutate(
        contrast = case_when(
            contrast == "signal" ~ "Any signal - no signal",
            TRUE ~ contrast
        )
    )

rf_signal_dist_subset_tes %>%
    select(contrast, assigned_dist_group, pval_onesided)

rf_ols_tbl = prep_tbl(rf_ols_tes, stat = params$stat)
rf_ols_dist_tbl = prep_tbl(rf_ols_dist_tes, stat = params$stat)
rf_probit_tbl = prep_tbl(bind_rows(rf_probit_tes, rf_signal_dist_subset_tes), stat = params$stat)
rf_probit_dist_tbl = prep_tbl(
    bind_rows(
        rf_probit_dist_tes, 
        rf_signal_dist_subset_tes
        ), 
        stat = params$stat)

rf_probit_dist_pval_tbl = prep_tbl(
    bind_rows(
        rf_probit_dist_tes,
        rf_signal_dist_subset_tes %>%
            mutate(
                estimate = pval_onesided,
                conf.low = NA,
                conf.high = NA,
                contrast = "$p$(Any signal > No signal)"
                )
        ),
        stat = params$stat
    )

rf_probit_cts_dist_pval_tbl = prep_tbl(
    bind_rows(
        rf_probit_cts_dist_tes,
        rf_signal_cts_dist_subset_tes %>%
            mutate(
                estimate = pval_onesided,
                conf.low = NA,
                conf.high = NA,
                contrast = "$p$(Any signal > No signal)"
                )
        ),
        stat = params$stat
    )


rf_probit_control_tbl = prep_tbl(rf_probit_control_tes, stat = params$stat)
rf_probit_cts_dist_tbl = prep_tbl(rf_probit_cts_dist_tes, stat = params$stat)


rf_probit_dist_all_pval_tbl = prep_tbl(
    bind_rows(
        rf_probit_dist_tes,
        rf_signal_dist_subset_tes %>%
            mutate(
                estimate = pval_onesided,
                conf.low = NA,
                conf.high = NA,
                contrast = "$p$(Any signal > No signal)"
                )
        ),
        stat = "p" 
    )


rf_ols_kbl = nice_kbl_table(rf_ols_tbl, "Frequentist OLS (Clustering)")
rf_ols_dist_kbl = nice_kbl_table(rf_ols_dist_tbl, "Frequentist OLS with Distance (Clustering)")
rf_probit_kbl = nice_kbl_table(rf_probit_tbl, "Frequentist Probit (Clustering)")
rf_probit_dist_kbl = nice_kbl_table(rf_probit_dist_tbl, "Frequentist Probit with Distance (Clustering)")
rf_probit_control_kbl = nice_kbl_table(rf_probit_control_tbl, "Frequentist Probit with Controls (Clustering)")
rf_probit_cts_dist_kbl = nice_kbl_table(rf_probit_cts_dist_tbl, "Frequentist Probit with CTS Distance (Clustering + CTS Distance)")
rf_probit_dist_pval_kbl = nice_kbl_table(rf_probit_dist_pval_tbl, "Frequentist Probit with Distance (Clustering + P-Value)")

rf_probit_dist_all_pval_kbl = nice_kbl_table(rf_probit_dist_all_pval_tbl, "Frequentist Probit with Distance (Clustering + P-Value) Only P-values")

rf_probit_cts_dist_pval_kbl = nice_kbl_table(rf_probit_cts_dist_pval_tbl, "Frequentist Probit with CTS Distance (Clustering + CTS Distance) + P-Values")


```

```{r}
#| signal-dist-estimates, results="asis"
rf_signal_dist_kbl = rf_signal_dist_tes %>%
    mutate(across(where(is.numeric), round, 3)) %>%
    mutate(
        estim_std = if_else(
            is.na(pval_onesided),
            linebreak(paste0(estimate,"\n", str_glue("({conf.low}, {conf.high})")), align = "c"),
            linebreak(paste0(
                estimate,"\n", 
                str_glue("({conf.low}, {conf.high})"), "\n",
                str_glue("pval: {pval_onesided}")
                ), align = "c")
        )
    ) %>%
    select(
        contrast,
        assigned_dist_group,
        estim_std
    ) %>%
    mutate(assigned_dist_group = factor(assigned_dist_group, levels = c("combined", "close", "far", "far - close"))) %>%
    arrange(assigned_dist_group) %>%
    pivot_wider(
        names_from = assigned_dist_group,
        values_from = estim_std
    )  %>%
    kbl(
        escape = FALSE,
        caption = "Frequentist Probit with Signal (Clustering + Distance)"
    )
rf_signal_dist_kbl %>%
    custom_save_latex_table("rf-signal-dist")    


```

```{r}
#| signal-estimates, results="asis"

rf_signal_kbl = rf_signal_tes %>%
    mutate(across(where(is.numeric), round, 3)) %>%
    mutate(
        estim_std = if_else(
            is.na(pval_onesided),
            linebreak(paste0(estimate,"\n", str_glue("({conf.low}, {conf.high})")), align = "c"),
            linebreak(paste0(
                estimate,"\n", 
                str_glue("({conf.low}, {conf.high})"), "\n",
                str_glue("pval: {pval_onesided}")
                ), align = "c")
        )
    ) %>%
    select(
        contrast,
        assigned_dist_group,
        estim_std
    ) %>%
    mutate(assigned_dist_group = factor(assigned_dist_group, levels = c("combined", "close", "far", "far - close"))) %>%
    arrange(assigned_dist_group) %>%
    pivot_wider(
        names_from = assigned_dist_group,
        values_from = estim_std
    )  %>%
    kbl(
        escape = FALSE,
        caption = "Frequentist Probit with Signal (Clustering)"
    )
rf_signal_kbl %>%
    custom_save_latex_table("rf-signal")    


```

```{r}
#| rf-probit-tbl, results="asis"
rf_probit_kbl %>%
    custom_save_latex_table("rf-probit")
```


```{r}
#| rf-probit-dist-tbl, results="asis"
rf_probit_dist_kbl %>%
    custom_save_latex_table("rf-probit-dist")
```


```{r}
#| rf-probit-dist-pval-tbl, results="asis"
rf_probit_dist_pval_kbl %>%
    custom_save_latex_table("rf-probit-dist-pval")
```


```{r}
rf_probit_cts_dist_pval_kbl %>%
    custom_save_latex_table("rf-probit-cts-dist-pval")

```


```{r}
rf_probit_dist_all_pval_kbl %>%
    custom_save_latex_table("rf-probit-dist-all-pval")

```


```{r}
#| rf-probit-cts-dist-tbl, results="asis"
rf_probit_cts_dist_kbl %>%
    custom_save_latex_table("rf-probit-cts-dist")
```



```{r}
#| rf-probit-control-tbl, results="asis"
rf_probit_control_kbl %>%
    custom_save_latex_table("rf-probit-control")
```



```{r}
rf_ols_kbl %>%
    custom_save_latex_table("rf-ols")
```

```{r}
rf_ols_dist_kbl %>%
    custom_save_latex_table("rf-ols-dist")
```


```{r}

library(brms)
options(mc.cores = 4)
analysis_data = analysis_data %>%
    mutate(
        county = factor(county),
        cluster.id = factor(cluster.id)
    )
if (params$fit) {
    brm_rf_fit_no_cluster = brm(
        data = analysis_data,
        dewormed ~ 0 + county + (assigned_treatment*assigned_dist_group), 
        family = bernoulli(link = "probit")
    )

    brm_rf_no_cluster_comp_df = brm_rf_fit_no_cluster %>%
        create_comparisons()
    brm_rf_no_cluster_comp_df %>%
        write_csv(
            file.path(
                params$table_output_path,
                "brm_rf_no_cluster_comp_df.csv"
            )
        )

} else {
    brm_rf_no_cluster_comp_df = read_csv(
        file.path(
            params$table_output_path,
            "brm_rf_no_cluster_comp_df.csv"
        )
    )
}


```

```{r}
if (params$fit) {

brm_flat_dist = brm(
    data = analysis_data,
    dewormed ~ (1 | cluster.id)  + county + standard_cluster.dist.to.pot + (assigned_treatment*assigned_dist_group),
    family = bernoulli(link = "probit")
)

saveRDS(
    list(brm_model = brm_flat_dist, data = analysis_data),
    file.path(
        "data",
        "stan_analysis_data",
        "brm_flat_dist_fit.rds"
    )
    )

brm_flat_dist_comp_df = brm_flat_dist %>%
    create_comparisons()
brm_flat_dist_comp_df %>%
    write_csv(
        file.path(
            params$table_output_path,
            "brm_flat_dist_comp_df.csv"
        )
    )
} else {


brm_flat_dist_comp_df =
    read_csv(
        file.path(
            params$table_output_path,
            "brm_flat_dist_comp_df.csv"
        )
    )
}
```


```{r}


install.packages("fixest", force = TRUE)

probit_signal_dist_fit = analysis_data %>%
    feglm(
        dewormed ~ 0 + signal:assigned_dist_group + cluster.dist.to.pot | county,
        data = .,
        family = binomial(link = "probit"),
        cluster = ~cluster.id
    )

```


```{r}
if (params$fit) {

brm_rf_fit_hier_cluster = brm(
    data = analysis_data,
    dewormed ~ (1 | cluster.id)  + county + (assigned_treatment*assigned_dist_group),
    family = bernoulli(link = "probit")
)

saveRDS(
    list(brm_model = brm_rf_fit_hier_cluster, data = analysis_data),
    file.path(
        "data",
        "stan_analysis_data",
        "brm_rf_fit_hier_cluster_fit.rds"
    )
    )
brm_rf_hier_cluster_comp_df = brm_rf_fit_hier_cluster %>%
    create_comparisons()
brm_rf_hier_cluster_comp_df %>%
    write_csv(
        file.path(
            params$table_output_path,
            "brm_rf_hier_cluster_comp_df.csv"
        )
    )
} else {


brm_rf_hier_cluster_comp_df =
    read_csv(
        file.path(
            params$table_output_path,
            "brm_rf_hier_cluster_comp_df.csv"
        )
    )
}
```



```{r}
#| tighter-hier-priors
if (params$fit) {
default_priors = get_prior(
    data = analysis_data,
    dewormed ~ (1 | cluster.id) + county + (assigned_treatment*assigned_dist_group), 
    family = bernoulli(link = "probit")
)

manual_priors = set_prior(
    "normal(0, 0.1)",
    lb = 0,
    class = "sd",
    group = "cluster.id"

    )



brm_rf_fit_tight_hier_cluster = brm(
    data = analysis_data,
    dewormed ~ (1 | cluster.id)  + county + (assigned_treatment*assigned_dist_group),
    family = bernoulli(link = "probit"),
    prior = manual_priors
)

brm_rf_tight_hier_cluster_comp_df = brm_rf_fit_tight_hier_cluster %>%
    create_comparisons()
brm_rf_tight_hier_cluster_comp_df %>%
    write_csv(
        file.path(
            params$table_output_path,
            "brm_rf_tight_hier_cluster_comp_df.csv"
        )
    )
} else {


brm_rf_tight_hier_cluster_comp_df =
    read_csv(
        file.path(
            params$table_output_path,
            "brm_rf_tight_hier_cluster_comp_df.csv"
        )
    )
}
```



```{r}
#| tighter-hier-priors-county
if (params$fit) {


default_priors = get_prior(
    data = analysis_data,
    dewormed ~ (1 | cluster.id) + (1 | county) + (assigned_treatment*assigned_dist_group), 
    family = bernoulli(link = "probit")
)

manual_priors = c(
    set_prior(
        "normal(0, 0.1)",
        lb = 0,
        class = "sd",
        group = "cluster.id"
    ),
    set_prior(
        "normal(0, 0.1)",
        lb = 0,
        class = "sd",
        group = "county"
    ),
    set_prior(
        "normal(0, 0.25)",
        class = "b"
    ),
    set_prior(
        "normal(0, 0.75)",
        class = "Intercept"
    )
)


brm_rf_fit_tight_hier_county_cluster = brm(
    data = analysis_data,
    dewormed ~ (1 | cluster.id) + (1 | county) + (assigned_treatment:assigned_dist_group),
    family = bernoulli(link = "probit"),
    prior = manual_priors
)

brm_rf_tight_hier_county_cluster_comp_df = brm_rf_fit_tight_hier_county_cluster %>%
    create_comparisons()

brm_rf_tight_hier_county_cluster_comp_df %>%
    write_csv(
        file.path(
            params$table_output_path,
            "brm_rf_tight_hier_county_cluster_comp_df.csv"
        )
    )
} else {


brm_rf_tight_hier_county_cluster_comp_df =
    read_csv(
        file.path(
            params$table_output_path,
            "brm_rf_tight_hier_county_cluster_comp_df.csv"
        )
    )
}
```


```{r}
if (params$fit) {
default_priors = get_prior(
    data = analysis_data,
    dewormed ~ 0 + (1 | cluster.id) + county + (assigned_treatment*assigned_dist_group), 
    family = bernoulli(link = "probit")
)

manual_priors = c(
    set_prior(
        "normal(0, 0.1)",
        lb = 0,
        class = "sd",
        group = "cluster.id"
        ),
    set_prior(
        "normal(0, 0.25)",
        class = "b"
    ),
    set_prior(
        "normal(0, 0.75)",
        class = "b",
        coef = c("countyBusia", "countyKakamega", "countySiaya")
    )
)



brm_nonflat_priors = brm(
    data = analysis_data,
    dewormed ~ 0 + (1 | cluster.id)  + county + (assigned_treatment*assigned_dist_group),
    family = bernoulli(link = "probit"),
    prior = manual_priors
)


code = stancode(brm_nonflat_priors)

brm_non_flat_prior_comp_df = brm_nonflat_priors %>%
    create_comparisons()

brm_non_flat_prior_comp_df %>%
    write_csv(
        file.path(
            params$table_output_path,
            "brm_non_flat_prior_comp_df.csv"
        )
    )

} else {
brm_non_flat_prior_comp_df =
    read_csv(
        file.path(
            params$table_output_path,
            "brm_non_flat_prior_comp_df.csv"
        )
    )

}




```


```{r}
if (params$fit) {
default_priors = get_prior(
    data = analysis_data,
    dewormed ~ 0 + (1 | cluster.id) + county + (assigned_treatment*assigned_dist_group), 
    family = bernoulli(link = "probit")
)


manual_priors = c(
    set_prior(
        "normal(0, 0.1)",
        lb = 0,
        class = "sd",
        group = "cluster.id"
        ),
    set_prior(
        "normal(0, 0.25)",
        class = "b"
    ),
    set_prior(
        "normal(0, 0.75)",
        class = "b",
        coef = c("countyBusia", "countyKakamega", "countySiaya")
    ),
    set_prior(
        "normal(0, 1)",
        class = "b",
        coef = "standard_cluster.dist.to.pot"
    )
)


brm_nonflat_priors_dist = brm(
    data = analysis_data,
    dewormed ~ 0 + (1 | cluster.id)  + county + (assigned_treatment*assigned_dist_group) + standard_cluster.dist.to.pot,
    family = bernoulli(link = "probit"),
    prior = manual_priors
)


brm_non_flat_prior_dist_comp_df = brm_nonflat_priors_dist %>%
    create_comparisons()

brm_non_flat_prior_dist_comp_df %>%
    write_csv(
        file.path(
            params$table_output_path,
            "brm_non_flat_prior_dist_comp_df.csv"
        )
    )

} else {
brm_non_flat_prior_dist_comp_df =
    read_csv(
        file.path(
            params$table_output_path,
            "brm_non_flat_prior_dist_comp_df.csv"
        )
    )

}




```




```{r}

brm_rf_no_cluster_prep_tbl = brm_rf_no_cluster_comp_df %>%
    prep_tbl(., stat = "ci") %>%
    nice_kbl_table("Bayesian Probit: No Clustering")

brm_rf_no_cluster_prep_tbl %>%
    custom_save_latex_table("bayes-rf-probit-no-clustering")

```


```{r}

brm_rf_hier_cluster_prep_tbl = brm_rf_hier_cluster_comp_df %>%
    prep_tbl(., stat = "ci") %>%
    nice_kbl_table("Bayesian Probit: Hierarchical Clustering")

brm_rf_hier_cluster_prep_tbl %>%
    custom_save_latex_table("bayes-rf-probit-hierarchical-clustering")

```

```{r}
brm_flat_dist_prep_tbl = brm_flat_dist_comp_df %>%
    prep_tbl(., stat = "ci") %>%
    nice_kbl_table("Bayesian Probit: Flat Priors + Distance")
brm_flat_dist_prep_tbl %>%
    custom_save_latex_table("bayes-rf-probit-flat-priors-distance")

```


```{r}

brm_rf_tight_hier_cluster_prep_tbl = brm_rf_tight_hier_cluster_comp_df %>%
    prep_tbl(., stat = "ci") %>%
    nice_kbl_table("Bayesian Probit: Tight Hierarchical Clustering")

brm_rf_tight_hier_cluster_prep_tbl %>%
    custom_save_latex_table("bayes-rf-probit-tight-hierarchical-clustering")

```



```{r}

brm_rf_tight_hier_county_cluster_prep_tbl = brm_rf_tight_hier_county_cluster_comp_df %>%
    prep_tbl(., stat = "ci") %>%
    nice_kbl_table("Bayesian Probit: Tight Hierarchical Clustering + County")

brm_rf_tight_hier_county_cluster_prep_tbl %>%
    custom_save_latex_table("bayes-rf-probit-tight-hierarchical-county-clustering")

```

```{r}

brm_non_flat_prior_prep_tbl = brm_non_flat_prior_comp_df %>%
    prep_tbl(., stat = "ci") %>%
    nice_kbl_table("Bayesian Probit: Non-Flat Priors")

brm_non_flat_prior_prep_tbl %>%
    custom_save_latex_table("bayes-rf-probit-non-flat-priors")


```

```{r}

brm_non_flat_prior_dist_prep_tbl = brm_non_flat_prior_dist_comp_df %>%
    prep_tbl(., stat = "ci") %>%
    nice_kbl_table("Bayesian Probit: Non-Flat Priors - Distance")

brm_non_flat_prior_dist_prep_tbl %>%
    custom_save_latex_table("bayes-rf-probit-non-flat-priors-distance")


```

#### Stan ####


```{r}
#| stan

library(tidyverse)


rfnr = "REDUCED_FORM_NO_RESTRICT"
rfnrngp = "REDUCED_FORM_NO_RESTRICT_NO_GP"
rfnrdb = "REDUCED_FORM_NO_RESTRICT_DIFFUSE_BETA"
struct_dbdc = "STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP_DIFFUSE_BETA_DIFFUSE_CLUSTER"
struct_hier_s = "STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP_HIER_SOB"
struct_hier_f = "STRUCTURAL_LINEAR_U_SHOCKS_PHAT_MU_REP_HIER_FOB"

models_we_want = tribble(
    ~model, ~fit_version,
    rfnr, 97,
    rfnr, 98,
    rfnrngp, 98,
    rfnrdb, 99,
    rfnr, 99,
    struct_dbdc, 98,
    struct_hier_s, 98,
    struct_hier_f, 98

)

ate_rvar_df = models_we_want %>%
    mutate(
        fp = file.path(
            "temp-data",
            str_glue(
                "rvar_processed_dist_fit{fit_version}_ates_{model}_1-4.rds"
            )
        )
    ) %>%
    select(-fit_version, -model) %>%
    mutate(data = map(fp, read_rds)) %>%
    select(-fp) %>%
    unnest(data)




ate_rvar_df = ate_rvar_df %>%
    mutate(
        model_type = if_else(str_detect(model, "STRUCT"), "structural", "reduced form") %>% factor(),
        fit_type = factor(fit_type),
        model = factor(model)
    )




# ate_rvar_df$value = c(ate_rvar_rf$value)

create_cis = function(.data, .width = 0.9) {
  med_fun = function(x) {
    mean_x = mean(x) %>% round(3)
    conf.low = quantile(x, (1 - .width)/2) %>% round(3)
    conf.high = quantile(x, 1 - (1 - .width)/2) %>% round(3)
  
    return_val = linebreak(
      paste0(
        mean_x, "\n", str_glue(
          "({conf.low}, {conf.high})"
        )
      ), align = "c"
    )
    return(return_val)
  }
  .data %>%
    mutate(across(where(is_rvar), med_fun))
}


create_ate_table = function(.data, .estimand, group_var = treatment) {
  .data %>%
    filter(estimand == .estimand) %>%
    select(
      model,
      {{ group_var }},
      dist_group,
      value
    ) %>%
    pivot_wider(
      names_from = dist_group,
      values_from = value
    ) %>%
    select(model, {{ group_var }}, any_of(c("combined", "close", "far"))) %>%
    arrange({{ group_var }}) %>%
    bind_rows(
      # bracelet minus calendar row
      .data %>%
        filter({{ group_var }} %in% c("Bracelet", "Calendar")) %>%
        filter(estimand == .estimand) %>%
        pivot_wider(names_from = {{ group_var }}, values_from = value) %>%
        mutate(
          bracelet_minus_calendar = Bracelet - Calendar
        ) %>%
        select(model, dist_group, bracelet_minus_calendar) %>%
        pivot_wider(
          names_from = dist_group,
          values_from = bracelet_minus_calendar
        ) %>%
        mutate("{{ group_var }}" := "bracelet_minus_calendar")
    )
}


incentive_ate_df =  ate_rvar_df %>%
    group_by(
        model, fit_version
    ) %>%
    group_nest() %>%
    mutate(
        data = map2(data, model, ~mutate(.x, model = .y)),
        ate_table = map(data, ~create_ate_table(.x, .estimand = "overall", group_var = treatment))
    )




ate_tbl_levels = c(
    "Bracelet",
    "Calendar",
    "Ink",
    "bracelet_minus_calendar",
    "Control"
)

recode_control_mean = function(data) {
  data %>%
    mutate(
      treatment = fct_recode(treatment, "Control mean" = "Control", "Bracelet - Calendar" = "bracelet_minus_calendar")
    )
}

spread_rf = function(data) {
  data %>%
    # mutate(model_type = "rf") %>%
    select(-model) %>%
    pivot_wider(
      names_from = model_type,
      id_cols = treatment,
      names_glue = "{model_type}_{.value}",
      values_from = any_of(c("combined", "close", "far", "far_minus_close"))
    ) %>%
    select(treatment, starts_with("rf"), starts_with("struct"))
}

incentive_ate_df = incentive_ate_df %>%
    mutate(
        tbl = map(
            ate_table,
            ~mutate(
                .x,
                model_type = if_else(str_detect(model, "STRUCT"), "struct", "rf") %>% factor(),
                fit_type = "fit",
                model = factor(model)
            ) %>%
            mutate(treatment = factor(treatment, levels = 
                ate_tbl_levels
            )) %>%
            mutate(far_minus_close = far - close) %>%
            arrange(treatment)   %>%
            create_cis(.width = params$width) %>%
            recode_control_mean()  %>%
            spread_rf() 
        )
    )

incentive_ate_df = incentive_ate_df %>%
    mutate(
        cap_string = str_glue(
            "Stan: {str_replace_all(model, '_', ' ')}, Version: {fit_version}"
        ),
        kbl_table = map2(
            tbl, cap_string,
            nice_kbl_table
        )
    )




```


```{r}
#| stan-tables, results="asis"

incentive_ate_df %>%
    pull(kbl_table) %>%
    map(print)

```

## Frequentist Probit (p-values) ##


```{r}

rf_probit_tes %>%
    prep_tbl(., stat = "p") %>%
    nice_kbl_table("Frequentist Probit (p-values)")

rf_probit_dist_tes %>%
    prep_tbl(., stat = "p") %>%
    nice_kbl_table("Frequentist Probit with Distance (p-values)")

```





```{r}
#| bootstrap-fit
# clusbootglm(
# model,
# data,
# clusterid,
# family = gaussian,
# B = 5000,
# confint.level = 0.95,
# n.cores = 1
# )


library(ClusterBootstrap)
fit = clusbootglm(
    dewormed ~ 0 + assigned_treatment*standard_cluster.dist.to.pot + county,
    data = analysis_data,
    clusterid = cluster.id,
    family = binomial(link = probit),
    B = 5,
    confint.level = 0.95
)

fit$coefficients


boot_fit = function(
    
    subset_data = analysis_data
)

    feglm(
        dewormed ~ 0 + assigned_treatment + standard_cluster.dist.to.pot + i(assigned_treatment, standard_cluster.dist.to.pot, "control") | county,
        data = analysis_data,
        family = binomial(link = probit)
    )

probit_signal_dist_cts_fit = analysis_data %>%
    feglm(
        dewormed ~ 0 + signal + standard_cluster.dist.to.pot  + i(signal, standard_cluster.dist.to.pot, "no signal")  | county,
        data = .,
        family = binomial(link = "probit"),
        cluster = ~cluster.id
    )




```